/*  Creator: make/0

    Purpose: Provide index for autoload
*/

index((avoidHeadLoop), 2, common_logic_boxlog, common_logic_boxlog).
index((body_for_mpred_1), 5, common_logic_boxlog, common_logic_boxlog).
index((body_for_mpred_2), 5, common_logic_boxlog, common_logic_boxlog).
index((body_for_pfc), 5, common_logic_boxlog, common_logic_boxlog).
index((boxlog_to_compile), 2, common_logic_boxlog, common_logic_boxlog).
index((boxlog_to_compile), 3, common_logic_boxlog, common_logic_boxlog).
index((boxlog_to_compile2), 4, common_logic_boxlog, common_logic_boxlog).
index((can_use_hack), 1, common_logic_boxlog, common_logic_boxlog).
index((conjoin_body), 3, common_logic_boxlog, common_logic_boxlog).
index((conjoin_maybe), 3, common_logic_boxlog, common_logic_boxlog).
index((correct_mode), 3, common_logic_boxlog, common_logic_boxlog).
index((did_use_hack), 1, common_logic_boxlog, common_logic_boxlog).
index((get_op_alias_compile), 2, common_logic_boxlog, common_logic_boxlog).
index((get_reln), 2, common_logic_boxlog, common_logic_boxlog).
index((is_unit), 2, common_logic_boxlog, common_logic_boxlog).
index((is_unit), 3, common_logic_boxlog, common_logic_boxlog).
index((is_unit), 4, common_logic_boxlog, common_logic_boxlog).
index((is_units_b), 1, common_logic_boxlog, common_logic_boxlog).
index((is_units_h), 1, common_logic_boxlog, common_logic_boxlog).
index((make_must_ground), 3, common_logic_boxlog, common_logic_boxlog).
index((make_vg), 4, common_logic_boxlog, common_logic_boxlog).
index((overlaping), 3, common_logic_boxlog, common_logic_boxlog).
index((overlapingFunctors), 2, common_logic_boxlog, common_logic_boxlog).
index((reduce_literal), 2, common_logic_boxlog, common_logic_boxlog).
index((set_clause_compile), 1, common_logic_boxlog, common_logic_boxlog).
index((vg), 1, common_logic_boxlog, common_logic_boxlog).
index((vg), 3, common_logic_boxlog, common_logic_boxlog).
index((nnf), 3, common_logic_compiler, common_logic_compiler).
index((pnf), 3, common_logic_compiler, common_logic_compiler).
index((cf), 4, common_logic_compiler, common_logic_compiler).
index((atom_compat), 3, common_logic_compiler, common_logic_compiler).
index((axiom_lhs_to_rhs), 2, common_logic_compiler, common_logic_compiler).
index((axiom_lhs_to_rhs), 3, common_logic_compiler, common_logic_compiler).
index((b_d_p), 2, common_logic_compiler, common_logic_compiler).
index((boxRule), 3, common_logic_compiler, common_logic_compiler).
index((cf), 4, common_logic_compiler, common_logic_compiler).
index((cf_to_flattened_clauses), 4, common_logic_compiler, common_logic_compiler).
index((cf_to_flattened_clauses_0), 4, common_logic_compiler, common_logic_compiler).
index((cirRule), 3, common_logic_compiler, common_logic_compiler).
index((clausify), 4, common_logic_compiler, common_logic_compiler).
index((clean_repeats_d), 2, common_logic_compiler, common_logic_compiler).
index((cnf), 3, common_logic_compiler, common_logic_compiler).
index((cnf1), 3, common_logic_compiler, common_logic_compiler).
index((correct_boxlog), 4, common_logic_compiler, common_logic_compiler).
index((correct_boxlog_0), 4, common_logic_compiler, common_logic_compiler).
index((correct_cls), 3, common_logic_compiler, common_logic_compiler).
index((correct_cls0), 3, common_logic_compiler, common_logic_compiler).
index((corrected_modal), 3, common_logic_compiler, common_logic_compiler).
index((corrected_modal0), 3, common_logic_compiler, common_logic_compiler).
index((corrected_modal_recurse), 3, common_logic_compiler, common_logic_compiler).
index((corrected_modal_recurse0), 3, common_logic_compiler, common_logic_compiler).
index((ct_op), 1, common_logic_compiler, common_logic_compiler).
index((delete_sublits), 3, common_logic_compiler, common_logic_compiler).
index((demodal), 3, common_logic_compiler, common_logic_compiler).
index((demodal_sents), 3, common_logic_compiler, common_logic_compiler).
index((diaRule), 3, common_logic_compiler, common_logic_compiler).
index((display_form), 2, common_logic_compiler, common_logic_compiler).
index((dnf), 3, common_logic_compiler, common_logic_compiler).
index((dnf1), 3, common_logic_compiler, common_logic_compiler).
index((expand_cl), 3, common_logic_compiler, common_logic_compiler).
index((flattenConjs), 3, common_logic_compiler, common_logic_compiler).
index((flatten_clauses), 2, common_logic_compiler, common_logic_compiler).
index((get_quantifier_isa), 3, common_logic_compiler, common_logic_compiler).
index((inclause), 6, common_logic_compiler, common_logic_compiler).
index((incorrect_cl), 2, common_logic_compiler, common_logic_compiler).
index((invert_modal), 2, common_logic_compiler, common_logic_compiler).
index((is_lit_atom), 1, common_logic_compiler, common_logic_compiler).
index((is_sent_op_modality), 1, common_logic_compiler, common_logic_compiler).
index((logical_neg), 3, common_logic_compiler, common_logic_compiler).
index((logical_pos), 3, common_logic_compiler, common_logic_compiler).
index((logically_matches), 3, common_logic_compiler, common_logic_compiler).
index((make_1_cl), 4, common_logic_compiler, common_logic_compiler).
index((make_clause_from_set), 3, common_logic_compiler, common_logic_compiler).
index((make_clause_set), 3, common_logic_compiler, common_logic_compiler).
index((make_clauses), 3, common_logic_compiler, common_logic_compiler).
index((make_each), 3, common_logic_compiler, common_logic_compiler).
index((mk_skolem), 5, common_logic_compiler, common_logic_compiler).
index((mk_skolem_name), 5, common_logic_compiler, common_logic_compiler).
index((modal2sent), 2, common_logic_compiler, common_logic_compiler).
index((mpred_quf), 2, common_logic_compiler, common_logic_compiler).
index((mpred_quf_0), 2, common_logic_compiler, common_logic_compiler).
index((neg_op), 1, common_logic_compiler, common_logic_compiler).
index((negate), 3, common_logic_compiler, common_logic_compiler).
index((negate0), 3, common_logic_compiler, common_logic_compiler).
index((negate_one), 3, common_logic_compiler, common_logic_compiler).
index((negate_one_maybe), 3, common_logic_compiler, common_logic_compiler).
index((nnf), 3, common_logic_compiler, common_logic_compiler).
index((nnf), 5, common_logic_compiler, common_logic_compiler).
index((nnf_label), 5, common_logic_compiler, common_logic_compiler).
index((nnf_shared), 5, common_logic_compiler, common_logic_compiler).
index((nonegate), 3, common_logic_compiler, common_logic_compiler).
index((nonvar_unify), 2, common_logic_compiler, common_logic_compiler).
index((notin), 2, common_logic_compiler, common_logic_compiler).
index((nowrap_one), 3, common_logic_compiler, common_logic_compiler).
index((pnf), 3, common_logic_compiler, common_logic_compiler).
index((pnf), 4, common_logic_compiler, common_logic_compiler).
index((putin), 3, common_logic_compiler, common_logic_compiler).
index((removeQ), 3, common_logic_compiler, common_logic_compiler).
index((removeQ), 4, common_logic_compiler, common_logic_compiler).
index((removeQ_LC), 4, common_logic_compiler, common_logic_compiler).
index((removes_literal), 2, common_logic_compiler, common_logic_compiler).
index((same_var), 2, common_logic_compiler, common_logic_compiler).
index((share_scopes), 2, common_logic_compiler, common_logic_compiler).
index((simplify_atom), 2, common_logic_compiler, common_logic_compiler).
index((simplify_cheap), 2, common_logic_compiler, common_logic_compiler).
index((simplify_cheap_must), 2, common_logic_compiler, common_logic_compiler).
index((skolem_bad), 4, common_logic_compiler, common_logic_compiler).
index((skolem_f), 5, common_logic_compiler, common_logic_compiler).
index((skolem_fn), 6, common_logic_compiler, common_logic_compiler).
index((skolem_fn_shared), 6, common_logic_compiler, common_logic_compiler).
index((skolem_setting), 1, common_logic_compiler, common_logic_compiler).
index((third_order), 1, common_logic_compiler, common_logic_compiler).
index((to_poss), 2, common_logic_compiler, common_logic_compiler).
index((to_regular_cl), 4, common_logic_compiler, common_logic_compiler).
index((unbuiltin_negate), 3, common_logic_compiler, common_logic_compiler).
index((unbuiltin_negate), 4, common_logic_compiler, common_logic_compiler).
index((until_op), 1, common_logic_compiler, common_logic_compiler).
index((variants_are_equal), 3, common_logic_compiler, common_logic_compiler).
index((kbp_t), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((with_el_holds_disabled), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((noGenlPreds), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((cyckb_t), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((link_to_holds2), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((assert_next_queue), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((assert_to_db_list), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((assertion_f), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((assertion_t), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((big_kb_ASSERTION), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_f), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_f), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_f), 5, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_f), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_f), 7, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_f), 8, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_f), 9, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_f), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_f), 5, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_f), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_f), 7, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_f), 8, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_f), 9, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_f), 10, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_f), 11, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_t), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_t), 5, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_t), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_t), 7, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_t), 8, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_t), 9, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_t), 10, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_mt_t), 11, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_which_t), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_which_t), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_which_t), 5, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_which_t), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_which_t), 7, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_which_t), 8, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_which_t), 9, common_logic_kb_hooks, common_logic_kb_hooks).
index((call_whichlist_t), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((callable_tf), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((convert_easy_strings), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((convert_easy_strings2), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((cyckb_t), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((cyckb_t), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((cyckb_t_call), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((cyckb_t_implies), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((cyckb_t_via_genlPreds), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((cyckb_t_via_implies), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((drain_assert_next_buffer), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((el_holds_DISABLED_KB), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((fix_sentence), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((get_assertions), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((get_b_dnf), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((get_dnf_props), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((get_props), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((get_varsp), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((hide_empty_strings), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((hide_term_rewrites), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f), 5, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f), 7, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f), 8, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_f_p2), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_relaxed_0_f), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((holds_relaxed_f), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((kb_f), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((kb_mt), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((kb_t), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((kb_t), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_t), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_t_list), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_t_list), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_t_list), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_t_list_0), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_t_list_1), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_t_list_prehook), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_to_mpred_0), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_to_mpred_no_more), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((kbp_to_mpred_t), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((link_to_holds), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((link_to_holds), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((link_to_holds2), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((link_to_holds2), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((link_to_holds_DYNAMIC), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((link_to_holds_list), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((move_implied), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((move_kb_assertions_matching), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((mpred_f), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((noGenlPreds), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((nv1000), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((print_sentence), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((proof_from_clause), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((prove_calllist), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((relax_term), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((tiny_kb_ASSERTION), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((which_f), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((with_el_holds_disabled), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((with_el_holds_enabled), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((with_kb_assertions_matching), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((write_assertions), 0, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 5, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 7, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 8, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 9, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_f), 10, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 1, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 2, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 3, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 4, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 5, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 6, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 7, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 8, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 9, common_logic_kb_hooks, common_logic_kb_hooks).
index((xcall_t), 10, common_logic_kb_hooks, common_logic_kb_hooks).
index((codelist_to_forms), 2, common_logic_sexpr, common_logic_sexpr).
index((svar_fixvarname), 2, common_logic_sexpr, common_logic_sexpr).
index((input_to_forms), 2, common_logic_sexpr, common_logic_sexpr).
index((input_to_forms), 3, common_logic_sexpr, common_logic_sexpr).
index((sexpr_sterm_to_pterm_list), 2, common_logic_sexpr, common_logic_sexpr).
index((sexpr_sterm_to_pterm), 2, common_logic_sexpr, common_logic_sexpr).
index((lisp_read_from_input), 2, common_logic_sexpr, common_logic_sexpr).
index((parse_sexpr), 2, common_logic_sexpr, common_logic_sexpr).
index((add_nesc), 2, common_logic_snark, common_logic_snark).
index((add_poss), 2, common_logic_snark, common_logic_snark).
index((add_poss_to), 3, common_logic_snark, common_logic_snark).
index((add_preconds), 2, common_logic_snark, common_logic_snark).
index((add_preconds2), 2, common_logic_snark, common_logic_snark).
index((adjust_kif), 3, common_logic_snark, common_logic_snark).
index((adjust_kif0), 3, common_logic_snark, common_logic_snark).
index((adjust_kif0), 4, common_logic_snark, common_logic_snark).
index((adjust_kif0), 5, common_logic_snark, common_logic_snark).
index((adjust_kif5), 5, common_logic_snark, common_logic_snark).
index((alt_kif_to_boxlog), 4, common_logic_snark, common_logic_snark).
index((as_dlog), 2, common_logic_snark, common_logic_snark).
index((as_prolog), 2, common_logic_snark, common_logic_snark).
index((as_symlog), 2, common_logic_snark, common_logic_snark).
index((boxlog_to_pfc), 2, common_logic_snark, common_logic_snark).
index((boxlog_to_prolog), 2, common_logic_snark, common_logic_snark).
index((check_is_kb), 1, common_logic_snark, common_logic_snark).
index((clif_to_prolog), 2, common_logic_snark, common_logic_snark).
index((clauses_to_boxlog), 4, common_logic_snark, common_logic_snark).
index((clauses_to_boxlog_0), 4, common_logic_snark, common_logic_snark).
index((clauses_to_boxlog_1), 4, common_logic_snark, common_logic_snark).
index((clauses_to_boxlog_2), 4, common_logic_snark, common_logic_snark).
index((clauses_to_boxlog_5), 4, common_logic_snark, common_logic_snark).
index((convertAndCall), 2, common_logic_snark, common_logic_snark).
index((correct_arities), 3, common_logic_snark, common_logic_snark).
index((fix_input_vars), 2, common_logic_snark, common_logic_snark).
index((flatten_or_list), 3, common_logic_snark, common_logic_snark).
index((fmtl), 1, common_logic_snark, common_logic_snark).
index((fresh_varname), 2, common_logic_snark, common_logic_snark).
index((generate_ante), 4, common_logic_snark, common_logic_snark).
index((get_1_var_name), 3, common_logic_snark, common_logic_snark).
index((get_constraints), 2, common_logic_snark, common_logic_snark).
index((get_lits), 2, common_logic_snark, common_logic_snark).
index((get_var_names), 3, common_logic_snark, common_logic_snark).
index((is_clif), 1, common_logic_snark, common_logic_snark).
index((are_clauses_entailed), 1, common_logic_snark, common_logic_snark).
index((is_prolog_entailed), 1, common_logic_snark, common_logic_snark).
index((delistify_last_arg), 3, common_logic_snark, common_logic_snark).
index((kb_incr), 2, common_logic_snark, common_logic_snark).
index((kif), 0, common_logic_snark, common_logic_snark).
index((kif_ask), 1, common_logic_snark, common_logic_snark).
index((kif_ask), 2, common_logic_snark, common_logic_snark).
index((kif_ask_sent), 1, common_logic_snark, common_logic_snark).
index((kif_hook), 1, common_logic_snark, common_logic_snark).
index((kif_io), 2, common_logic_snark, common_logic_snark).
index((kif_process), 1, common_logic_snark, common_logic_snark).
index((kif_process), 2, common_logic_snark, common_logic_snark).
index((kif_read), 3, common_logic_snark, common_logic_snark).
index((kif_add), 1, common_logic_snark, common_logic_snark).
index((kif_add_adding_constraints), 3, common_logic_snark, common_logic_snark).
index((kif_add_boxes1), 2, common_logic_snark, common_logic_snark).
index((kif_add_boxes3), 3, common_logic_snark, common_logic_snark).
index((kif_test_string), 1, common_logic_snark, common_logic_snark).
index((kif_to_boxlog), 2, common_logic_snark, common_logic_snark).
index((kif_to_boxlog), 3, common_logic_snark, common_logic_snark).
index((kif_to_boxlog), 4, common_logic_snark, common_logic_snark).
index((kif_to_prolog), 2, common_logic_snark, common_logic_snark).
index((kif_unnumbervars), 2, common_logic_snark, common_logic_snark).
index((lit_cost), 3, common_logic_snark, common_logic_snark).
index((litcost_compare), 4, common_logic_snark, common_logic_snark).
index((local_pterm_to_sterm), 2, common_logic_snark, common_logic_snark).
index((local_pterm_to_sterm2), 2, common_logic_snark, common_logic_snark).
index((local_sterm_to_pterm), 2, common_logic_snark, common_logic_snark).
index((ain_h), 3, common_logic_snark, common_logic_snark).
index((mpred_t_tell_kif), 2, common_logic_snark, common_logic_snark).
index((mudEquals), 2, common_logic_snark, common_logic_snark).
index((neg_b_if_neg), 3, common_logic_snark, common_logic_snark).
index((neg_h_if_neg), 2, common_logic_snark, common_logic_snark).
index((not_mudEquals), 2, common_logic_snark, common_logic_snark).
index((nots_to), 3, common_logic_snark, common_logic_snark).
index((numbervars_with_names), 2, common_logic_snark, common_logic_snark).
index((is_quantifier), 1, common_logic_snark, common_logic_snark).
index((save_in_code_buffer), 2, common_logic_snark, common_logic_snark).
index((save_wfs), 2, common_logic_snark, common_logic_snark).
index((should_be_poss), 1, common_logic_snark, common_logic_snark).
index((simp_code), 2, common_logic_snark, common_logic_snark).
index((simple_negate_literal), 3, common_logic_snark, common_logic_snark).
index((simplify_bodies), 2, common_logic_snark, common_logic_snark).
index((simplify_list), 3, common_logic_snark, common_logic_snark).
index((skolem), 3, common_logic_snark, common_logic_snark).
index((sort_body), 3, common_logic_snark, common_logic_snark).
index((sort_body_0), 3, common_logic_snark, common_logic_snark).
index((subsT_each), 3, common_logic_snark, common_logic_snark).
index((tkif), 0, common_logic_snark, common_logic_snark).
index((to_dlog_ops), 1, common_logic_snark, common_logic_snark).
index((to_nonvars), 3, common_logic_snark, common_logic_snark).
index((to_prolog_ops), 1, common_logic_snark, common_logic_snark).
index((to_symlog_ops), 1, common_logic_snark, common_logic_snark).
index((tsn), 0, common_logic_snark, common_logic_snark).
index((type_of_var), 3, common_logic_snark, common_logic_snark).
index((use_was_isa_h), 3, common_logic_snark, common_logic_snark).
index((var_count_num), 4, common_logic_snark, common_logic_snark).
index((wdmsgl), 1, common_logic_snark, common_logic_snark).
index((wdmsgl_2), 2, common_logic_snark, common_logic_snark).
index((wdmsgl_3), 3, common_logic_snark, common_logic_snark).
index((wdmsgl_4), 3, common_logic_snark, common_logic_snark).
index((why_to_id), 3, common_logic_snark, common_logic_snark).
index((write_list), 1, common_logic_snark, common_logic_snark).
index((is_entailed), 1, common_logic_snark, common_logic_snark).
index((is_not_entailed), 1, common_logic_snark, common_logic_snark).
