/*  Creator: make/0

    Purpose: Provide index for autoload
*/

index((asserta_if_ground), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((atom_contains666), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((bad_idea), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((beenCaught), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((bin_ecall), 4, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_atom_change), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_atom_change), 6, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_atom_change0), 6, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_error_info), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_expand_goal), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_expand_term), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_flag), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_flag), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_goal_expansion), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_goal_expansion), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_prolog_exception_hook), 4, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_t_expansion), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_term_expansion), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((bugger_term_expansion), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((buggeroo), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((call_or_list), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((call_skipping_n_clauses), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((caller_module), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((caller_module), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((callsc), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((cli_ntrace), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((contains_atom), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((debugFmt), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((debugFmtList), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((debugFmtList0), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((debugFmtList1), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_f_debug), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((debugOnFailureEach), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((default_dumptrace), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((default_ecall), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((define_if_missing), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((differnt_modules), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((disabled_this), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((do_gc), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((do_gc0), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((do_gc1), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((do_ref_job), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((doHideTrace), 4, logicmoo_util_bugger, logicmoo_util_bugger).
index((fmtString), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((fmtString), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((forall_member), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((format_safe), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((fresh_line), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((fresh_line), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((functor_h0), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((functor_source_file), 5, logicmoo_util_bugger, logicmoo_util_bugger).
index((functor_source_file0), 5, logicmoo_util_bugger, logicmoo_util_bugger).
index((gmust), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((gripe_time), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_f_debug), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_f_debug_ignore), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_x_debug), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_x_debug_cont), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_x_rtraceEach), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((has_gui_debug), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((hideRest), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((hideTrace), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((hideTrace), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((hideTraceMFA), 4, logicmoo_util_bugger, logicmoo_util_bugger).
index((hideTraceMFAT), 4, logicmoo_util_bugger, logicmoo_util_bugger).
index((hideTraceMP), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((hidetrace), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((hook_message_hook), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((ifThen), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((if_interactive), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((if_interactive0), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((if_prolog), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_x_cont), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((ignore_each), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((in_file_directive), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((in_file_expansion), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((in_toplevel), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((isConsole), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((is_deterministic), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((kill_term_expansion), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((list_difference_eq), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((list_difference_eq_memberchk_eq), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((listify), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((loading_module), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((loading_module), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((local_predicate), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_f_log_fail), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((logOnFailure0), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((logOnFailureEach), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_f_log_ignore), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((loggerFmtReal), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((loggerReFmt), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((logger_property), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((logicmoo_bugger_loaded), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((matches_term), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((matches_term0), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((meta_interp), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((meta_interp_signal), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((module_hotrace), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((module_stack), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((must_assign), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((must_assign), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((must_each), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((must_each0), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((must_maplist), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((must_maplist), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((must_maplist), 4, logicmoo_util_bugger, logicmoo_util_bugger).
index((new_a2s), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((new_a2s0), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((nodebugx), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((non_user_console), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((nth_frame), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((nth_frame_attribute), 5, logicmoo_util_bugger, logicmoo_util_bugger).
index((nth_goal), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((nth_pi), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_prolog_ecall), 4, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_prolog_ecall_override), 5, logicmoo_util_bugger, logicmoo_util_bugger).
index((once_if_ground), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((once_if_ground), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((one_must), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((pop_def), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((predicate_module), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((printPredCount), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((programmer_error), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((prolog_call), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((prolog_current_frame_or_parent), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((prolog_current_frames), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((with_each), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((with_each), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((with_each), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((prolog_ecall_fa), 5, logicmoo_util_bugger, logicmoo_util_bugger).
index((prolog_must), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((prolog_must_l), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((prolog_must_not), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((push_def), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((randomVars), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((real_builtin_predicate), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((replace_elements), 4, logicmoo_util_bugger, logicmoo_util_bugger).
index((rmust_det), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((saveUserInput), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((setLogLevel), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((set_bugger_flag), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((set_gui_debug), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((set_no_debug), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((set_no_debug_thread), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((set_optimize), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((set_yes_debug), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((set_yes_debug_thread), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((showProfilerStatistics), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_and_do), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_call), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_call), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((dcall0), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_entry), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_entry), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_failure), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_failure), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_success), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_success), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_goal_rethrow), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((show_module), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((shrink_clause), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((shrink_clause), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((singletons), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((test_for_release), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((test_for_release_problems), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((test_tl), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((test_tl), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((test_tl), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((thread_local_leaks), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((on_f_throw), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((throw_safe), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((time_call), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((to_list_of), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((traceAll), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((traceIf), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((dtrace_msg), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((traceok), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((tryCatchIgnore), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((tryHide), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((unlistify), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((wdmsg), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((wdmsg), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((willTrace), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((will_debug_else_throw), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((with_no_term_expansions), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((with_skip_bugger), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((writeErrMsg), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((writeErrMsg), 3, logicmoo_util_bugger, logicmoo_util_bugger).
index((writeFileToStream), 2, logicmoo_util_bugger, logicmoo_util_bugger).
index((writeOverwritten), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((writeSTDERR0), 1, logicmoo_util_bugger, logicmoo_util_bugger).
index((writeSavedPrompt), 0, logicmoo_util_bugger, logicmoo_util_bugger).
index((!), 1, logicmoo_util_catch, logicmoo_util_catch).
index((addLibraryDir), 0, logicmoo_util_catch, logicmoo_util_catch).
index((source_variables_l), 1, logicmoo_util_catch, logicmoo_util_catch).
index((as_clause_no_m), 3, logicmoo_util_catch, logicmoo_util_catch).
index((as_clause_w_m), 4, logicmoo_util_catch, logicmoo_util_catch).
index((as_clause_w_m), 5, logicmoo_util_catch, logicmoo_util_catch).
index((source_module), 1, logicmoo_util_catch, logicmoo_util_catch).
index((bad_functor), 1, logicmoo_util_catch, logicmoo_util_catch).
index((current_why), 1, logicmoo_util_catch, logicmoo_util_catch).
index((badfood), 1, logicmoo_util_catch, logicmoo_util_catch).
index((block), 2, logicmoo_util_catch, logicmoo_util_catch).
index((block), 3, logicmoo_util_catch, logicmoo_util_catch).
index((bubbled_ex), 1, logicmoo_util_catch, logicmoo_util_catch).
index((bubbled_ex_check), 1, logicmoo_util_catch, logicmoo_util_catch).
index((catchv), 3, logicmoo_util_catch, logicmoo_util_catch).
index((catchvvnt), 3, logicmoo_util_catch, logicmoo_util_catch).
index((current_source_location), 1, logicmoo_util_catch, logicmoo_util_catch).
index((current_main_error_stream), 1, logicmoo_util_catch, logicmoo_util_catch).
index((dbgsubst), 4, logicmoo_util_catch, logicmoo_util_catch).
index((dbgsubst0), 4, logicmoo_util_catch, logicmoo_util_catch).
index((ddmsg), 1, logicmoo_util_catch, logicmoo_util_catch).
index((ddmsg), 2, logicmoo_util_catch, logicmoo_util_catch).
index((ddmsg_call), 1, logicmoo_util_catch, logicmoo_util_catch).
index((det_lm), 2, logicmoo_util_catch, logicmoo_util_catch).
index((dif_safe), 2, logicmoo_util_catch, logicmoo_util_catch).
index((errx), 0, logicmoo_util_catch, logicmoo_util_catch).
index((on_x_fail), 1, logicmoo_util_catch, logicmoo_util_catch).
index((format_to_error), 2, logicmoo_util_catch, logicmoo_util_catch).
index((fresh_line_to_err), 0, logicmoo_util_catch, logicmoo_util_catch).
index((functor_catch), 3, logicmoo_util_catch, logicmoo_util_catch).
index((functor_safe), 3, logicmoo_util_catch, logicmoo_util_catch).
index((get_must), 2, logicmoo_util_catch, logicmoo_util_catch).
index((ib_multi_transparent33), 1, logicmoo_util_catch, logicmoo_util_catch).
index((if_defined), 1, logicmoo_util_catch, logicmoo_util_catch).
index((if_defined), 2, logicmoo_util_catch, logicmoo_util_catch).
index((if_defined_else), 2, logicmoo_util_catch, logicmoo_util_catch).
index((input_key), 1, logicmoo_util_catch, logicmoo_util_catch).
index((is_ftCompound), 1, logicmoo_util_catch, logicmoo_util_catch).
index((is_ftNonvar), 1, logicmoo_util_catch, logicmoo_util_catch).
index((is_ftVar), 1, logicmoo_util_catch, logicmoo_util_catch).
index((is_hiding_dmsgs), 0, logicmoo_util_catch, logicmoo_util_catch).
index((is_main_thread), 0, logicmoo_util_catch, logicmoo_util_catch).
index((is_pdt_like), 0, logicmoo_util_catch, logicmoo_util_catch).
index((is_release), 0, logicmoo_util_catch, logicmoo_util_catch).
index((keep), 2, logicmoo_util_catch, logicmoo_util_catch).
index((loading_file), 1, logicmoo_util_catch, logicmoo_util_catch).
index((on_x_log_throw), 1, logicmoo_util_catch, logicmoo_util_catch).
index((on_x_log_cont), 1, logicmoo_util_catch, logicmoo_util_catch).
index((on_x_log_fail), 1, logicmoo_util_catch, logicmoo_util_catch).
index((maplist_safe), 2, logicmoo_util_catch, logicmoo_util_catch).
index((maplist_safe), 3, logicmoo_util_catch, logicmoo_util_catch).
index((module_functor), 4, logicmoo_util_catch, logicmoo_util_catch).
index((trace_or_throw), 1, logicmoo_util_catch, logicmoo_util_catch).
index((trace_or_throw), 1, logicmoo_util_catch, logicmoo_util_catch).
index((must), 1, logicmoo_util_catch, logicmoo_util_catch).
index((must_det), 1, logicmoo_util_catch, logicmoo_util_catch).
index((must_det), 2, logicmoo_util_catch, logicmoo_util_catch).
index((must_det_l), 1, logicmoo_util_catch, logicmoo_util_catch).
index((must_det_lm), 2, logicmoo_util_catch, logicmoo_util_catch).
index((must_l), 1, logicmoo_util_catch, logicmoo_util_catch).
index((nd_dbgsubst), 4, logicmoo_util_catch, logicmoo_util_catch).
index((nd_dbgsubst1), 5, logicmoo_util_catch, logicmoo_util_catch).
index((nd_dbgsubst2), 4, logicmoo_util_catch, logicmoo_util_catch).
index((nop), 1, logicmoo_util_catch, logicmoo_util_catch).
index((not_is_release), 0, logicmoo_util_catch, logicmoo_util_catch).
index((one_must), 2, logicmoo_util_catch, logicmoo_util_catch).
index((one_must_det), 2, logicmoo_util_catch, logicmoo_util_catch).
index((sanity), 1, logicmoo_util_catch, logicmoo_util_catch).
index((save_streams), 0, logicmoo_util_catch, logicmoo_util_catch).
index((save_streams), 1, logicmoo_util_catch, logicmoo_util_catch).
index((set_block_exit), 2, logicmoo_util_catch, logicmoo_util_catch).
index((showHiddens), 0, logicmoo_util_catch, logicmoo_util_catch).
index((show_new_src_location), 1, logicmoo_util_catch, logicmoo_util_catch).
index((show_new_src_location), 2, logicmoo_util_catch, logicmoo_util_catch).
index((show_source_location), 0, logicmoo_util_catch, logicmoo_util_catch).
index((skipWrapper), 0, logicmoo_util_catch, logicmoo_util_catch).
index((slow_sanity), 1, logicmoo_util_catch, logicmoo_util_catch).
index((strip_arity), 3, logicmoo_util_catch, logicmoo_util_catch).
index((strip_f_module), 2, logicmoo_util_catch, logicmoo_util_catch).
index((thread_current_error_stream), 1, logicmoo_util_catch, logicmoo_util_catch).
index((throwNoLib), 0, logicmoo_util_catch, logicmoo_util_catch).
index((to_m_f_arity_pi), 5, logicmoo_util_catch, logicmoo_util_catch).
index((to_pi), 2, logicmoo_util_catch, logicmoo_util_catch).
index((to_pi0), 3, logicmoo_util_catch, logicmoo_util_catch).
index((warn_bad_functor), 1, logicmoo_util_catch, logicmoo_util_catch).
index((when_defined), 1, logicmoo_util_catch, logicmoo_util_catch).
index((with_main_error_to_output), 1, logicmoo_util_catch, logicmoo_util_catch).
index((with_main_input), 1, logicmoo_util_catch, logicmoo_util_catch).
index((with_main_io), 1, logicmoo_util_catch, logicmoo_util_catch).
index((with_preds), 6, logicmoo_util_catch, logicmoo_util_catch).
index((without_must), 1, logicmoo_util_catch, logicmoo_util_catch).
index((y_must), 2, logicmoo_util_catch, logicmoo_util_catch).
index((addCtxValue), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((addCtxValue1), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((addKeyValue), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((appendAttributes), 4, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((bestSetterFn), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((checkCtx), 1, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((copy_term_numvars), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((currentContext), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((delete_safe), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((eqmember), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((evil_term), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((getCtxValue), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((getKeyValue), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_frame_holder), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_frame_holder1), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_holder), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_holder1), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_holderFreeSpot), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_holderFreeSpot0), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_holderFreeSpot1), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_holderFreeSpot1), 5, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_ctx_value), 4, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_n_value), 6, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_o_value), 4, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_o_value0), 4, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((get_o_value1), 4, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((hideIfNeeded), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((lastMemberCtx), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((lastMemberCtx), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((makeLocalContext), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((makeLocalContext1), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((mergeAppend0), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((no_cyclic_terms), 0, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((popCtxFrame), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((pushCtxFrame), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((remCtxValue), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((revappend_0), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((reverseA), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((setCtxValue), 3, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((to_open_list), 4, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((unwrapValue), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((unwrapValue1), 2, logicmoo_util_ctx_frame, logicmoo_util_ctx_frame).
index((ain), 1, logicmoo_util_database, logicmoo_util_database).
index((ain0), 1, logicmoo_util_database, logicmoo_util_database).
index((aina), 1, logicmoo_util_database, logicmoo_util_database).
index((ainz), 1, logicmoo_util_database, logicmoo_util_database).
index((paina), 1, logicmoo_util_database, logicmoo_util_database).
index((pain), 1, logicmoo_util_database, logicmoo_util_database).
index((painz), 1, logicmoo_util_database, logicmoo_util_database).
index((ainz_clause), 1, logicmoo_util_database, logicmoo_util_database).
index((ainz_clause), 2, logicmoo_util_database, logicmoo_util_database).
index((append_term), 3, logicmoo_util_database, logicmoo_util_database).
index((as_clause), 3, logicmoo_util_database, logicmoo_util_database).
index((assert_if_new), 1, logicmoo_util_database, logicmoo_util_database).
index((asserta_if_new), 1, logicmoo_util_database, logicmoo_util_database).
index((asserta_new), 1, logicmoo_util_database, logicmoo_util_database).
index((assertz_if_new), 1, logicmoo_util_database, logicmoo_util_database).
index((assertz_new), 1, logicmoo_util_database, logicmoo_util_database).
index((call_provider), 1, logicmoo_util_database, logicmoo_util_database).
index((call_provider), 2, logicmoo_util_database, logicmoo_util_database).
index((clause_asserted), 1, logicmoo_util_database, logicmoo_util_database).
index((clause_asserted), 2, logicmoo_util_database, logicmoo_util_database).
index((clause_asserted), 3, logicmoo_util_database, logicmoo_util_database).
index((clause_eq), 3, logicmoo_util_database, logicmoo_util_database).
index((clause_safe), 2, logicmoo_util_database, logicmoo_util_database).
index((debugCallWhy), 2, logicmoo_util_database, logicmoo_util_database).
index((erase_safe), 2, logicmoo_util_database, logicmoo_util_database).
index((eraseall), 2, logicmoo_util_database, logicmoo_util_database).
index((find_and_call), 1, logicmoo_util_database, logicmoo_util_database).
index((find_and_call), 3, logicmoo_util_database, logicmoo_util_database).
index((mpred_mop), 3, logicmoo_util_database, logicmoo_util_database).
index((mpred_op_prolog), 2, logicmoo_util_database, logicmoo_util_database).
index((mpred_split_op_data), 3, logicmoo_util_database, logicmoo_util_database).
index((retract_eq), 1, logicmoo_util_database, logicmoo_util_database).
index((safe_univ), 2, logicmoo_util_database, logicmoo_util_database).
index((safe_univ0), 2, logicmoo_util_database, logicmoo_util_database).
index((my_module_sensitive_code), 1, logicmoo_util_database, logicmoo_util_database).
index((do_dcg_util_tests), 0, logicmoo_util_dcg, logicmoo_util_dcg).
index((isVar), 1, logicmoo_util_dcg, logicmoo_util_dcg).
index((isQVar), 1, logicmoo_util_dcg, logicmoo_util_dcg).
index((isVarOrVAR), 1, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgOptional), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgOptionalGreedy), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgAnd), 4, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgAnd), 5, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgAnd), 6, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgMust), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((dumpList), 1, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgOr), 4, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgNot), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((theString), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((theString), 4, logicmoo_util_dcg, logicmoo_util_dcg).
index((theText), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((theCode), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgLenBetween), 4, logicmoo_util_dcg, logicmoo_util_dcg).
index((do_dcgTest), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((do_dcgTest_startsWith), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((decl_dcgTest_startsWith), 2, logicmoo_util_dcg, logicmoo_util_dcg).
index((decl_dcgTest_startsWith), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((decl_dcgTest), 2, logicmoo_util_dcg, logicmoo_util_dcg).
index((decl_dcgTest), 3, logicmoo_util_dcg, logicmoo_util_dcg).
index((dcgReorder), 4, logicmoo_util_dcg, logicmoo_util_dcg).
index((ansi_control_conv), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((ansicall), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((ansicall), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((ansicall0), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((ansicall1), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((ansifmt), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((ansifmt), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((colormsg), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((contrasting_color), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((defined_message_color), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dfmt), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dfmt), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((debugm), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((cls), 0, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg0), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg0), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg1), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg2), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg3), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg4), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg5), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg5), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg_hide), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg_hides_message), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg_show), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg_showall), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsg_text_to_string_safe), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((dmsginfo), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((f_word), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fg_color), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((flush_output_safe), 0, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((flush_output_safe), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt0), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt0), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt0), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt9), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt_ansi), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt_or_pp), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((fmt_portray_clause), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((functor_color), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((get_indent_level), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((good_next_color), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((if_color_debug), 0, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((if_color_debug), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((if_color_debug), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((in_cmt), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((indent_e), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((indent_to_spaces), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((is_sgr_on_code), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((is_tty), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((keep_line_pos), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((last_used_fg_color), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((mesg_arg1), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((mesg_color), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((msg_to_string), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((next_color), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((portray_clause_w_vars), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((portray_clause_w_vars), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((portray_clause_w_vars), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((portray_clause_w_vars), 4, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((predef_functor_color), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((prepend_each_line), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((print_prepended), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((print_prepended_lines), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((random_color), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((sformat), 4, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((sgr_code_on_off), 3, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((sgr_off_code), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((sgr_on_code), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((sgr_on_code0), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((to_stderror), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((tst_color), 0, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((tst_color), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((tst_fmt), 0, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((unliked_ctrl), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((vdmsg), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((withFormatter), 4, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_all_dmsg), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_current_indent), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_dmsg), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_no_dmsg), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_no_dmsg), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_output_to_console), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_output_to_main), 1, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_output_to_stream), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((with_show_dmsg), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((writeFailureLog), 2, logicmoo_util_dmsg, logicmoo_util_dmsg).
index((getPFA), 3, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((getPFA1), 3, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((getPFA2), 3, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((get_m_opt), 4, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((fdmsg), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((fdmsg1), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((neg1_numbervars), 3, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((clauseST), 2, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dtrace), 0, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dtrace), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dtrace), 2, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumptrace), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumptrace), 2, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumptrace_ret), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((drain_framelist), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((drain_framelist_ele), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dump_st), 0, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((to_wmsg), 2, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((simplify_goal_printed), 2, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST), 0, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST1), 0, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST0), 0, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST0), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST0), 2, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST9), 0, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST9), 1, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST9), 2, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((dumpST_now), 2, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((printFrame), 3, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((frame_to_fmsg), 4, logicmoo_util_dumpst, logicmoo_util_dumpst).
index((copy_stream), 2, logicmoo_util_filestreams, logicmoo_util_filestreams).
index((file_to_stream), 2, logicmoo_util_filestreams, logicmoo_util_filestreams).
index((file_to_stream_ssl_verify), 5, logicmoo_util_filestreams, logicmoo_util_filestreams).
index((l_open_input), 2, logicmoo_util_filestreams, logicmoo_util_filestreams).
index((l_open_input0), 2, logicmoo_util_filestreams, logicmoo_util_filestreams).
index((l_open_input1), 2, logicmoo_util_filestreams, logicmoo_util_filestreams).
index((text_to_stream), 2, logicmoo_util_filestreams, logicmoo_util_filestreams).
index((with_stream_pos), 2, logicmoo_util_filestreams, logicmoo_util_filestreams).
index((add_to_search_path), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((add_to_search_path), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((add_to_search_path_first), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((add_to_search_path_last), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((atom_concat_safe), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((atom_ensure_endswtih), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((canonical_pathname), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((clip_dir_sep), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((concat_paths), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((concat_paths), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((current_dirs), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((current_dirs0), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((current_filedir), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((current_filesource), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((enumerate_files), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((enumerate_files0), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((enumerate_files00), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((enumerate_files1), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((enumerate_files2), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((enumerate_m_files), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((exists_directory_safe), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((exists_dirf), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((exists_file_or_dir), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((exists_file_safe), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((expand_file_name_safe), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((expand_wfm), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((filematch), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((filematch3), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((filematch_ext), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((global_pathname), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((if_file_exists), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((if_startup_script), 0, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((if_startup_script), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((in_search_path), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((is_directory), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((join_path), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((join_path_if_needed), 3, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((local_directory_search_combined), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((local_directory_search_combined2), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((locally_to_dir), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((my_absolute_file_name), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((normalize_path), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((os_to_prolog_filename), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((prolog_file_dir), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((prolog_file_dir), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((relative_pathname), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((remove_search_path), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((time_file_safe), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((to_filename), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((upcase_atom_safe), 2, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((with_filematch), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((with_filematches), 1, logicmoo_util_filesystem, logicmoo_util_filesystem).
index((safe_numbervars), 1, logicmoo_util_first, logicmoo_util_first).
index((safe_numbervars), 2, logicmoo_util_first, logicmoo_util_first).
index((user_ensure_loaded), 1, logicmoo_util_first, logicmoo_util_first).
index((user_use_module), 1, logicmoo_util_first, logicmoo_util_first).
index((alldiscontiguous), 0, logicmoo_util_first, logicmoo_util_first).
index((arg_is_transparent), 1, logicmoo_util_first, logicmoo_util_first).
index((all_module_predicates_are_transparent), 1, logicmoo_util_first, logicmoo_util_first).
index((alldiscontiguous), 0, logicmoo_util_first, logicmoo_util_first).
index((arg_is_transparent), 1, logicmoo_util_first, logicmoo_util_first).
index((module_meta_predicates_are_transparent), 1, logicmoo_util_first, logicmoo_util_first).
index((module_predicate), 3, logicmoo_util_first, logicmoo_util_first).
index((module_predicate), 4, logicmoo_util_first, logicmoo_util_first).
index((module_predicates_are_exported), 0, logicmoo_util_first, logicmoo_util_first).
index((module_predicates_are_exported), 1, logicmoo_util_first, logicmoo_util_first).
index((module_predicates_are_exported0), 1, logicmoo_util_first, logicmoo_util_first).
index((module_predicates_are_not_exported_list), 2, logicmoo_util_first, logicmoo_util_first).
index((quiet_all_module_predicates_are_transparent), 1, logicmoo_util_first, logicmoo_util_first).
index((export_all_preds), 0, logicmoo_util_first, logicmoo_util_first).
index((export_all_preds), 1, logicmoo_util_first, logicmoo_util_first).
index((export_if_noconflict), 2, logicmoo_util_first, logicmoo_util_first).
index((if_may_hide), 1, logicmoo_util_first, logicmoo_util_first).
index((match_predicates), 2, logicmoo_util_first, logicmoo_util_first).
index((match_predicates), 5, logicmoo_util_first, logicmoo_util_first).
index((mpred_trace_childs), 1, logicmoo_util_first, logicmoo_util_first).
index((mpred_trace_less), 1, logicmoo_util_first, logicmoo_util_first).
index((mpred_trace_nochilds), 1, logicmoo_util_first, logicmoo_util_first).
index((mpred_trace_none), 1, logicmoo_util_first, logicmoo_util_first).
index((add_newvar), 2, logicmoo_util_first, logicmoo_util_first).
index((add_newvars), 1, logicmoo_util_first, logicmoo_util_first).
index((always_show_dmsg), 0, logicmoo_util_first, logicmoo_util_first).
index((mustvv), 1, logicmoo_util_first, logicmoo_util_first).
index((name_to_var), 3, logicmoo_util_first, logicmoo_util_first).
index((source_context_module), 1, logicmoo_util_first, logicmoo_util_first).
index((register_var), 3, logicmoo_util_first, logicmoo_util_first).
index((register_var), 4, logicmoo_util_first, logicmoo_util_first).
index((register_var_0), 4, logicmoo_util_first, logicmoo_util_first).
index((remove_grounds), 2, logicmoo_util_first, logicmoo_util_first).
index((renumbervars_prev), 2, logicmoo_util_first, logicmoo_util_first).
index((renumbervars1), 2, logicmoo_util_first, logicmoo_util_first).
index((renumbervars1), 4, logicmoo_util_first, logicmoo_util_first).
index((samify), 2, logicmoo_util_first, logicmoo_util_first).
index((snumbervars), 1, logicmoo_util_first, logicmoo_util_first).
index((snumbervars), 3, logicmoo_util_first, logicmoo_util_first).
index((snumbervars), 4, logicmoo_util_first, logicmoo_util_first).
index((term_to_string), 2, logicmoo_util_first, logicmoo_util_first).
index((unnumbervars), 2, logicmoo_util_first, logicmoo_util_first).
index((unnumbervars_and_save), 2, logicmoo_util_first, logicmoo_util_first).
index((var_to_name), 3, logicmoo_util_first, logicmoo_util_first).
index((current_predicate_mfa), 3, logicmoo_util_help, logicmoo_util_help).
index((end_l_sum), 2, logicmoo_util_help, logicmoo_util_help).
index((export_file_preds), 0, logicmoo_util_help, logicmoo_util_help).
index((export_file_preds), 1, logicmoo_util_help, logicmoo_util_help).
index((export_file_preds), 6, logicmoo_util_help, logicmoo_util_help).
index((export_module_preds), 0, logicmoo_util_help, logicmoo_util_help).
index((list_item_per_line), 3, logicmoo_util_help, logicmoo_util_help).
index((functor_compare), 3, logicmoo_util_help, logicmoo_util_help).
index((helper_name), 1, logicmoo_util_help, logicmoo_util_help).
index((list_file_preds), 0, logicmoo_util_help, logicmoo_util_help).
index((list_file_preds), 1, logicmoo_util_help, logicmoo_util_help).
index((list_file_preds), 2, logicmoo_util_help, logicmoo_util_help).
index((longer_sumry), 2, logicmoo_util_help, logicmoo_util_help).
index((make_l_summary), 2, logicmoo_util_help, logicmoo_util_help).
index((make_module_name), 2, logicmoo_util_help, logicmoo_util_help).
index((make_summary), 2, logicmoo_util_help, logicmoo_util_help).
index((module_meta_transparent), 1, logicmoo_util_help, logicmoo_util_help).
index((mpred_prolog_only_module), 1, logicmoo_util_help, logicmoo_util_help).
index((mpred_show_doc), 1, logicmoo_util_help, logicmoo_util_help).
index((mpred_show_doc), 2, logicmoo_util_help, logicmoo_util_help).
index((mpred_source_file), 2, logicmoo_util_help, logicmoo_util_help).
index((name_modes), 3, logicmoo_util_help, logicmoo_util_help).
index((no_location), 3, logicmoo_util_help, logicmoo_util_help).
index((portray_clause_pi_LR), 2, logicmoo_util_help, logicmoo_util_help).
index((portray_clause_pi_UD), 2, logicmoo_util_help, logicmoo_util_help).
index((predicate_decl_module), 2, logicmoo_util_help, logicmoo_util_help).
index((print_fake_doc), 2, logicmoo_util_help, logicmoo_util_help).
index((scan_and_list_file_preds), 1, logicmoo_util_help, logicmoo_util_help).
index((some_flocation), 3, logicmoo_util_help, logicmoo_util_help).
index((some_location), 3, logicmoo_util_help, logicmoo_util_help).
index((mpred_type_module), 1, logicmoo_util_help, logicmoo_util_help).
index((target_module), 2, logicmoo_util_help, logicmoo_util_help).
index((list_item_per_line), 4, logicmoo_util_help, logicmoo_util_help).
index((write_modules), 0, logicmoo_util_help, logicmoo_util_help).
index((helper_name0), 1, logicmoo_util_help, logicmoo_util_help).
index((is_crossfile_module_0), 1, logicmoo_util_help, logicmoo_util_help).
index((make_summary0), 2, logicmoo_util_help, logicmoo_util_help).
index((mpred_source_file_0), 2, logicmoo_util_help, logicmoo_util_help).
index((skip_functor_export_0), 1, logicmoo_util_help, logicmoo_util_help).
index((to_comparable_fa0), 3, logicmoo_util_help, logicmoo_util_help).
index((to_mfa_0), 4, logicmoo_util_help, logicmoo_util_help).
index((any_term_overlap), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((any_term_overlap_atoms_of), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((atoms_of_0), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((call_setof_tabled), 4, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((call_t), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((call_tabled), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((call_tabled), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((call_tabled0), 4, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((call_tabled1), 4, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((call_vars_tabled), 3, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((can_fail), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((cannot_table_call), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((cannot_use_tables), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((cc_key), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((ex), 0, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((expire_dont_add), 0, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((expire_tabled_list), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((findall_nodupes), 3, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((get_where), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((get_where0), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((is_loop_checked), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((lco_goal_expansion), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((lex), 0, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((loop_check), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((loop_check), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((loop_check_early), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((loop_check_term), 3, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((loop_check_term_key), 3, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((make_key), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((make_tabled_perm), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((mpred_expire_caches), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((no_loop_check), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((no_loop_check), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((no_loop_check_term_key), 3, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((outside_of_loop_check), 0, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((really_can_table), 0, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((reduce_make_key), 2, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((retract_can_table), 0, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((skipped_table_call), 1, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((transitive), 3, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((transitive_except), 4, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((transitive_lc), 3, logicmoo_util_loop_check, logicmoo_util_loop_check).
index((memberchk_pred), 3, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((memberchk_pred_rev), 3, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((memberchk_same), 2, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((must_not_repeat), 1, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats), 1, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats), 2, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats_av), 0, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats_findall5), 5, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats_findall_r), 5, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats_old), 1, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats_old), 2, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats_save), 2, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats_save), 4, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((no_repeats_u), 2, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((subtract_eq), 3, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((succeeds_n_times), 2, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((term), 2, logicmoo_util_no_repeats, logicmoo_util_no_repeats).
index((call_if_defined), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((convert_to_dynamic), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((convert_to_dynamic), 3, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((current_predicate_module), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((context_module_of_file), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((def_meta_predicate), 3, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((dynamic_if_missing), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((dynamic_multifile), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((shared_multifile), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((dynamic_safe), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((dynamic_safe), 3, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((dynamic_transparent), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((fill_args), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((get_module_of), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((get_module_of_4), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((get_pi), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((only_3rd), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((make_transparent), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((multi_transparent), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((must_pi), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((p_predicate_property), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((to_canonical_mpi), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((pred_prop), 3, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((pred_prop), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((rebuild_as_dyn), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((rebuild_pred_into), 3, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((rebuild_pred_into), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((remove_pred), 3, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((static_predicate), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((static_predicate), 3, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((save_was), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((was_dynamic), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((was_multifile), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((was_module_transparent), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((was_export), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((shared_multifile), 1, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_mfa), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((make_shared_multifile), 3, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_pfa), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_pfa), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((m_m_fa_to_m_p_fa), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((m_fa_to_m_p_fa), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_pfa_single), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_pfa_group), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_mfa_of), 5, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_pi), 2, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_pi_selected), 4, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((with_pi_stub), 5, logicmoo_util_preddefs, logicmoo_util_preddefs).
index((current_frames), 4, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((current_next_frames), 4, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((in_pengines), 0, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((find_parent_frame_attribute), 5, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((parent_goal), 2, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((prolog_frame_match), 3, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((relative_frame), 3, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((stack_check), 0, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((stack_check), 1, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((stack_check), 2, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((stack_check_else), 2, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((stack_depth), 1, logicmoo_util_prolog_frames, logicmoo_util_prolog_frames).
index((with_err_to_pred), 2, logicmoo_util_prolog_streams, logicmoo_util_prolog_streams).
index((with_input_from_pred), 2, logicmoo_util_prolog_streams, logicmoo_util_prolog_streams).
index((with_output_to_pred), 2, logicmoo_util_prolog_streams, logicmoo_util_prolog_streams).
index((with_output_to_stream_pred), 4, logicmoo_util_prolog_streams, logicmoo_util_prolog_streams).
index((gftrace), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((ggtrace), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((grtrace), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((hotrace), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((nortrace), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((pop_tracer), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((push_tracer), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((restore_guitracer), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((rtrace), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((save_guitracer), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((reset_tracer), 0, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((cnotrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((fixhotrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((gftrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((grtrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((ggtrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((motrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((rtrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((ftrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((restore_trace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((restore_trace), 2, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((on_x_rtrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((hotrace), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((thread_leash), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((traceafter_call), 1, logicmoo_util_rtrace, logicmoo_util_rtrace).
index((wrap_shared), 3, logicmoo_util_shared_dynamic, logicmoo_util_shared_dynamic).
index((decl_shared), 1, logicmoo_util_shared_dynamic, logicmoo_util_shared_dynamic).
index((system_goal_expansion_sd), 2, logicmoo_util_shared_dynamic, logicmoo_util_shared_dynamic).
index((addSpaceBeforeSym), 2, logicmoo_util_strings, logicmoo_util_strings).
index((all_upper_atom), 1, logicmoo_util_strings, logicmoo_util_strings).
index((any_to_atom), 2, logicmoo_util_strings, logicmoo_util_strings).
index((any_to_string), 2, logicmoo_util_strings, logicmoo_util_strings).
index((any_to_string1), 2, logicmoo_util_strings, logicmoo_util_strings).
index((any_to_string_or_var), 2, logicmoo_util_strings, logicmoo_util_strings).
index((append_ci), 3, logicmoo_util_strings, logicmoo_util_strings).
index((append_ci0), 3, logicmoo_util_strings, logicmoo_util_strings).
index((as_atom), 2, logicmoo_util_strings, logicmoo_util_strings).
index((as_nc_str), 2, logicmoo_util_strings, logicmoo_util_strings).
index((atomSplit), 2, logicmoo_util_strings, logicmoo_util_strings).
index((atomSplit), 3, logicmoo_util_strings, logicmoo_util_strings).
index((atomSplit2), 3, logicmoo_util_strings, logicmoo_util_strings).
index((atomSplitEasy), 2, logicmoo_util_strings, logicmoo_util_strings).
index((atom_contains), 2, logicmoo_util_strings, logicmoo_util_strings).
index((atom_subst), 4, logicmoo_util_strings, logicmoo_util_strings).
index((atomic_concat), 4, logicmoo_util_strings, logicmoo_util_strings).
index((atomic_list_concat_catch), 3, logicmoo_util_strings, logicmoo_util_strings).
index((atomic_list_concat_safe), 2, logicmoo_util_strings, logicmoo_util_strings).
index((atomic_list_concat_safe), 3, logicmoo_util_strings, logicmoo_util_strings).
index((atomsSameCI), 2, logicmoo_util_strings, logicmoo_util_strings).
index((atoms_of), 2, logicmoo_util_strings, logicmoo_util_strings).
index((both_empty), 2, logicmoo_util_strings, logicmoo_util_strings).
index((breaked_codes), 2, logicmoo_util_strings, logicmoo_util_strings).
index((camelSplitters), 1, logicmoo_util_strings, logicmoo_util_strings).
index((capitalized), 1, logicmoo_util_strings, logicmoo_util_strings).
index((catch_read_term_from_atom), 3, logicmoo_util_strings, logicmoo_util_strings).
index((char_type_this), 2, logicmoo_util_strings, logicmoo_util_strings).
index((clean_codes), 2, logicmoo_util_strings, logicmoo_util_strings).
index((clean_out_atom), 2, logicmoo_util_strings, logicmoo_util_strings).
index((concat_atom_safe), 2, logicmoo_util_strings, logicmoo_util_strings).
index((concat_atom_safe), 3, logicmoo_util_strings, logicmoo_util_strings).
index((convert_members), 3, logicmoo_util_strings, logicmoo_util_strings).
index((convert_to_string), 2, logicmoo_util_strings, logicmoo_util_strings).
index((ctype_continue), 2, logicmoo_util_strings, logicmoo_util_strings).
index((ctype_switch), 2, logicmoo_util_strings, logicmoo_util_strings).
index((ctype_switcher), 1, logicmoo_util_strings, logicmoo_util_strings).
index((destringify), 2, logicmoo_util_strings, logicmoo_util_strings).
index((divide_list), 3, logicmoo_util_strings, logicmoo_util_strings).
index((either_empty), 2, logicmoo_util_strings, logicmoo_util_strings).
index((either_starts_with_icase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((empty_str), 1, logicmoo_util_strings, logicmoo_util_strings).
index((empty_string), 1, logicmoo_util_strings, logicmoo_util_strings).
index((ends_with_icase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((equals_icase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((escapeCodes), 4, logicmoo_util_strings, logicmoo_util_strings).
index((escapeString), 2, logicmoo_util_strings, logicmoo_util_strings).
index((first_char_to_lower), 2, logicmoo_util_strings, logicmoo_util_strings).
index((first_char_to_upper), 2, logicmoo_util_strings, logicmoo_util_strings).
index((hide_char_type), 1, logicmoo_util_strings, logicmoo_util_strings).
index((interleave), 3, logicmoo_util_strings, logicmoo_util_strings).
index((isWhitespace), 1, logicmoo_util_strings, logicmoo_util_strings).
index((is_charlist), 1, logicmoo_util_strings, logicmoo_util_strings).
index((is_codelist), 1, logicmoo_util_strings, logicmoo_util_strings).
index((is_ending), 1, logicmoo_util_strings, logicmoo_util_strings).
index((is_ftString2), 1, logicmoo_util_strings, logicmoo_util_strings).
index((is_simple_split), 1, logicmoo_util_strings, logicmoo_util_strings).
index((list_replace), 4, logicmoo_util_strings, logicmoo_util_strings).
index((longest_string), 3, logicmoo_util_strings, logicmoo_util_strings).
index((ltrim), 2, logicmoo_util_strings, logicmoo_util_strings).
index((map_tree_to_list), 3, logicmoo_util_strings, logicmoo_util_strings).
index((member_ci), 2, logicmoo_util_strings, logicmoo_util_strings).
index((merge_vars), 3, logicmoo_util_strings, logicmoo_util_strings).
index((must_nonvar), 1, logicmoo_util_strings, logicmoo_util_strings).
index((noCaseChange), 1, logicmoo_util_strings, logicmoo_util_strings).
index((non_empty), 1, logicmoo_util_strings, logicmoo_util_strings).
index((ommitable), 1, logicmoo_util_strings, logicmoo_util_strings).
index((quoteAtomString), 2, logicmoo_util_strings, logicmoo_util_strings).
index((read_stream_to_arglist), 2, logicmoo_util_strings, logicmoo_util_strings).
index((rejoined), 3, logicmoo_util_strings, logicmoo_util_strings).
index((remove_predupes), 2, logicmoo_util_strings, logicmoo_util_strings).
index((replace_in_string), 4, logicmoo_util_strings, logicmoo_util_strings).
index((replace_in_string), 5, logicmoo_util_strings, logicmoo_util_strings).
index((replace_periods), 2, logicmoo_util_strings, logicmoo_util_strings).
index((replace_periods_string_list), 2, logicmoo_util_strings, logicmoo_util_strings).
index((sort_by_strlen), 2, logicmoo_util_strings, logicmoo_util_strings).
index((splt_words), 3, logicmoo_util_strings, logicmoo_util_strings).
index((splt_words_0), 3, logicmoo_util_strings, logicmoo_util_strings).
index((splt_words_0_atom), 3, logicmoo_util_strings, logicmoo_util_strings).
index((starts_or_ends_with_icase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((starts_with_icase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((str_contains_all), 2, logicmoo_util_strings, logicmoo_util_strings).
index((str_contains_all0), 2, logicmoo_util_strings, logicmoo_util_strings).
index((stringToCodelist), 2, logicmoo_util_strings, logicmoo_util_strings).
index((stringToCodelist2), 2, logicmoo_util_strings, logicmoo_util_strings).
index((stringToList), 2, logicmoo_util_strings, logicmoo_util_strings).
index((string_ci), 2, logicmoo_util_strings, logicmoo_util_strings).
index((string_dedupe), 2, logicmoo_util_strings, logicmoo_util_strings).
index((string_equal_ci), 2, logicmoo_util_strings, logicmoo_util_strings).
index((string_equal_ci0), 2, logicmoo_util_strings, logicmoo_util_strings).
index((string_equal_ci1), 2, logicmoo_util_strings, logicmoo_util_strings).
index((string_to_atom_safe), 2, logicmoo_util_strings, logicmoo_util_strings).
index((text_to_string_safe), 2, logicmoo_util_strings, logicmoo_util_strings).
index((toCamelcase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((toCase), 3, logicmoo_util_strings, logicmoo_util_strings).
index((toCaseSplit), 4, logicmoo_util_strings, logicmoo_util_strings).
index((toLowercase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((toPropercase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((toUppercase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((to_case_breaks), 2, logicmoo_util_strings, logicmoo_util_strings).
index((to_case_breaks), 5, logicmoo_util_strings, logicmoo_util_strings).
index((to_first_break), 2, logicmoo_util_strings, logicmoo_util_strings).
index((to_first_break), 5, logicmoo_util_strings, logicmoo_util_strings).
index((to_first_break_w), 6, logicmoo_util_strings, logicmoo_util_strings).
index((to_list_of_sents), 2, logicmoo_util_strings, logicmoo_util_strings).
index((to_titlecase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((to_word_list), 2, logicmoo_util_strings, logicmoo_util_strings).
index((to_word_list_0), 2, logicmoo_util_strings, logicmoo_util_strings).
index((to_word_list_2), 2, logicmoo_util_strings, logicmoo_util_strings).
index((trim), 2, logicmoo_util_strings, logicmoo_util_strings).
index((trim2), 2, logicmoo_util_strings, logicmoo_util_strings).
index((unCamelcase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((unquoteAtom), 2, logicmoo_util_strings, logicmoo_util_strings).
index((vars_to_ucase), 2, logicmoo_util_strings, logicmoo_util_strings).
index((vars_to_ucase_0), 2, logicmoo_util_strings, logicmoo_util_strings).
index((attr_portray_hook), 2, logicmoo_util_structs, logicmoo_util_structs).
index((attr_unify_hook), 2, logicmoo_util_structs, logicmoo_util_structs).
index((by_name_datatype), 2, logicmoo_util_structs, logicmoo_util_structs).
index((compile_argtypes), 3, logicmoo_util_structs, logicmoo_util_structs).
index((compile_struct_slots), 6, logicmoo_util_structs, logicmoo_util_structs).
index((datatype_to_init), 2, logicmoo_util_structs, logicmoo_util_structs).
index((decl_argtypes), 1, logicmoo_util_structs, logicmoo_util_structs).
index((decl_struct), 1, logicmoo_util_structs, logicmoo_util_structs).
index((default_point), 1, logicmoo_util_structs, logicmoo_util_structs).
index((ensure_instance), 2, logicmoo_util_structs, logicmoo_util_structs).
index((ensure_instance), 3, logicmoo_util_structs, logicmoo_util_structs).
index((ensure_struct), 2, logicmoo_util_structs, logicmoo_util_structs).
index((ensure_struct), 3, logicmoo_util_structs, logicmoo_util_structs).
index((extract_struct_parameter), 4, logicmoo_util_structs, logicmoo_util_structs).
index((extract_struct_parameter), 5, logicmoo_util_structs, logicmoo_util_structs).
index((gvar_get), 2, logicmoo_util_structs, logicmoo_util_structs).
index((gvar_put), 2, logicmoo_util_structs, logicmoo_util_structs).
index((if_changed), 3, logicmoo_util_structs, logicmoo_util_structs).
index((is_point), 1, logicmoo_util_structs, logicmoo_util_structs).
index((key_match), 2, logicmoo_util_structs, logicmoo_util_structs).
index((make_point), 2, logicmoo_util_structs, logicmoo_util_structs).
index((make_point), 3, logicmoo_util_structs, logicmoo_util_structs).
index((member_arg_convert), 5, logicmoo_util_structs, logicmoo_util_structs).
index((member_datatype), 2, logicmoo_util_structs, logicmoo_util_structs).
index((merge_values), 3, logicmoo_util_structs, logicmoo_util_structs).
index((nb_set_pairlist), 3, logicmoo_util_structs, logicmoo_util_structs).
index((nb_set_pairlist0), 3, logicmoo_util_structs, logicmoo_util_structs).
index((nb_set_s2list), 4, logicmoo_util_structs, logicmoo_util_structs).
index((nb_set_s2list0), 4, logicmoo_util_structs, logicmoo_util_structs).
index((nb_set_x_of_point), 2, logicmoo_util_structs, logicmoo_util_structs).
index((nb_set_y_of_point), 2, logicmoo_util_structs, logicmoo_util_structs).
index((nb_setarg_ex), 3, logicmoo_util_structs, logicmoo_util_structs).
index((new_struct), 2, logicmoo_util_structs, logicmoo_util_structs).
index((point_data), 3, logicmoo_util_structs, logicmoo_util_structs).
index((point_x), 2, logicmoo_util_structs, logicmoo_util_structs).
index((point_y), 2, logicmoo_util_structs, logicmoo_util_structs).
index((prop_get), 1, logicmoo_util_structs, logicmoo_util_structs).
index((prop_get), 3, logicmoo_util_structs, logicmoo_util_structs).
index((prop_get_map), 3, logicmoo_util_structs, logicmoo_util_structs).
index((prop_get_nvlist), 2, logicmoo_util_structs, logicmoo_util_structs).
index((prop_get_try), 4, logicmoo_util_structs, logicmoo_util_structs).
index((prop_merge), 3, logicmoo_util_structs, logicmoo_util_structs).
index((prop_put_extra_extra), 2, logicmoo_util_structs, logicmoo_util_structs).
index((prop_set), 1, logicmoo_util_structs, logicmoo_util_structs).
index((prop_set), 3, logicmoo_util_structs, logicmoo_util_structs).
index((prop_set_dict_real), 4, logicmoo_util_structs, logicmoo_util_structs).
index((prop_set_map), 3, logicmoo_util_structs, logicmoo_util_structs).
index((prop_set_nvlist), 2, logicmoo_util_structs, logicmoo_util_structs).
index((prop_set_try), 4, logicmoo_util_structs, logicmoo_util_structs).
index((record_onto_var), 3, logicmoo_util_structs, logicmoo_util_structs).
index((record_var_names), 1, logicmoo_util_structs, logicmoo_util_structs).
index((record_var_names), 2, logicmoo_util_structs, logicmoo_util_structs).
index((record_var_type), 2, logicmoo_util_structs, logicmoo_util_structs).
index((set_point_field), 3, logicmoo_util_structs, logicmoo_util_structs).
index((set_point_fields), 3, logicmoo_util_structs, logicmoo_util_structs).
index((set_point_fields), 4, logicmoo_util_structs, logicmoo_util_structs).
index((set_x_of_point), 2, logicmoo_util_structs, logicmoo_util_structs).
index((set_x_of_point), 3, logicmoo_util_structs, logicmoo_util_structs).
index((set_y_of_point), 2, logicmoo_util_structs, logicmoo_util_structs).
index((set_y_of_point), 3, logicmoo_util_structs, logicmoo_util_structs).
index((sisctus_key), 2, logicmoo_util_structs, logicmoo_util_structs).
index((struct_sclass), 2, logicmoo_util_structs, logicmoo_util_structs).
index((t2ot), 2, logicmoo_util_structs, logicmoo_util_structs).
index((t2ot_0), 2, logicmoo_util_structs, logicmoo_util_structs).
index((term_to_ord_term), 2, logicmoo_util_structs, logicmoo_util_structs).
index((to_datatype), 3, logicmoo_util_structs, logicmoo_util_structs).
index((b_i), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((use_listing_vars), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((use_listing_vars), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((use_xlisting), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((use_xlisting), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((bad_pred), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((blob_info), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((bookeepingPredicateXRef), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((buggery_ok), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((clause_ref), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((cur_predicate), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((current_atom_or_blob), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((get_matcher_code), 4, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((get_search_ref), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((get_search_ref0), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((get_search_ref_tl), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((hide_data0), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((listing_filter), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((m_clause), 4, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((m_clause0), 4, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((m_clause_no_missing), 4, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((make_headkey), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((make_search_key), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((make_searchable), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((make_searchable_index), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((make_searchable_list_ref), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((make_searchable_ref), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((maybe_separate), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((maybe_separate_0), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((mmake), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((mp), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((mpred_match_listing), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((mpred_match_listing_skip_pi), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((mstatistics), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((new_atoms), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((nonvar_search), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((ok_show), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((plisting), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((portray_hb), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((portray_hbr), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((portray_one_line), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((pp_listing), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((predicateUsesCall), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((printAll), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((printAll), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((print_clause_properties), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((print_record_properties), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((process_unify_in_thread), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((real_list_undefined), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((remove_undef_search), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((save_atoms), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((save_search_ref), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((save_search_ref_0), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((save_search_ref_recorded), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((save_search_ref_tl), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((scansrc_list_undefined), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((search_refs_use_recorded), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((searchable_of_clause), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((searchable_of_clause_0), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((searchable_of_clause_1), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((searchable_of_clause_1), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((searchable_terms), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((searchable_terms_tl), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((sourceTextPredicate), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((sourceTextPredicateSource), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((synth_clause_for_l2), 5, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((synth_clause_for_large), 6, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((synth_clause_ref), 5, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((synth_in_listing), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((term_matches_hb), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((term_matches_hb), 4, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((term_matches_unify), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((unify_in_thread), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((unify_in_thread_tl), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((unify_listing), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((unify_listing), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((unify_listing_header), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((unify_listing_header), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((unmake_search_key), 2, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((update_changed_files), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((update_changed_files0), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((update_changed_files1), 0, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((xlisting), 1, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((xlisting_inner), 3, logicmoo_util_term_listing, logicmoo_util_term_listing).
index((call_n_times), 2, logicmoo_util_terms, logicmoo_util_terms).
index((makeArgIndexes), 1, logicmoo_util_terms, logicmoo_util_terms).
index((doall), 1, logicmoo_util_terms, logicmoo_util_terms).
index((subst), 4, logicmoo_util_terms, logicmoo_util_terms).
index((predsubst), 3, logicmoo_util_terms, logicmoo_util_terms).
index((wsubst), 4, logicmoo_util_terms, logicmoo_util_terms).
index((remove_dupes), 2, logicmoo_util_terms, logicmoo_util_terms).
index((get_functor), 2, logicmoo_util_terms, logicmoo_util_terms).
index((get_functor), 3, logicmoo_util_terms, logicmoo_util_terms).
index((functor_h), 2, logicmoo_util_terms, logicmoo_util_terms).
index((functor_h), 3, logicmoo_util_terms, logicmoo_util_terms).
index((flatten_set), 2, logicmoo_util_terms, logicmoo_util_terms).
index((at_start), 1, logicmoo_util_terms, logicmoo_util_terms).
index((in_thread_and_join), 1, logicmoo_util_terms, logicmoo_util_terms).
index((in_thread_and_join), 2, logicmoo_util_terms, logicmoo_util_terms).
index((make_list), 3, logicmoo_util_terms, logicmoo_util_terms).
index((throw_if_true_else_fail), 2, logicmoo_util_terms, logicmoo_util_terms).
index((at_start), 1, logicmoo_util_terms, logicmoo_util_terms).
index((call_n_times), 2, logicmoo_util_terms, logicmoo_util_terms).
index((call_no_cuts), 1, logicmoo_util_terms, logicmoo_util_terms).
index((conjoin), 3, logicmoo_util_terms, logicmoo_util_terms).
index((conjoin_op), 4, logicmoo_util_terms, logicmoo_util_terms).
index((conjuncts_to_list), 2, logicmoo_util_terms, logicmoo_util_terms).
index((delete_eq), 3, logicmoo_util_terms, logicmoo_util_terms).
index((disjuncts_to_list), 2, logicmoo_util_terms, logicmoo_util_terms).
index((doall), 1, logicmoo_util_terms, logicmoo_util_terms).
index((dynamic_load_pl), 1, logicmoo_util_terms, logicmoo_util_terms).
index((each_subterm), 2, logicmoo_util_terms, logicmoo_util_terms).
index((each_subterm), 3, logicmoo_util_terms, logicmoo_util_terms).
index((flatten_dedupe), 2, logicmoo_util_terms, logicmoo_util_terms).
index((flatten_set), 2, logicmoo_util_terms, logicmoo_util_terms).
index((functor_h), 2, logicmoo_util_terms, logicmoo_util_terms).
index((functor_h), 3, logicmoo_util_terms, logicmoo_util_terms).
index((get_functor), 2, logicmoo_util_terms, logicmoo_util_terms).
index((get_functor), 3, logicmoo_util_terms, logicmoo_util_terms).
index((identical_member), 2, logicmoo_util_terms, logicmoo_util_terms).
index((in_thread_and_join), 1, logicmoo_util_terms, logicmoo_util_terms).
index((in_thread_and_join), 2, logicmoo_util_terms, logicmoo_util_terms).
index((is_proof), 1, logicmoo_util_terms, logicmoo_util_terms).
index((is_true), 1, logicmoo_util_terms, logicmoo_util_terms).
index((lastMember2), 2, logicmoo_util_terms, logicmoo_util_terms).
index((list_retain), 3, logicmoo_util_terms, logicmoo_util_terms).
index((list_to_conjuncts), 2, logicmoo_util_terms, logicmoo_util_terms).
index((list_to_conjuncts), 3, logicmoo_util_terms, logicmoo_util_terms).
index((list_to_set_safe), 2, logicmoo_util_terms, logicmoo_util_terms).
index((load_assert), 3, logicmoo_util_terms, logicmoo_util_terms).
index((load_dirrective), 2, logicmoo_util_terms, logicmoo_util_terms).
index((load_term), 2, logicmoo_util_terms, logicmoo_util_terms).
index((load_term2), 2, logicmoo_util_terms, logicmoo_util_terms).
index((logicmoo_library_file_loaded), 0, logicmoo_util_terms, logicmoo_util_terms).
index((makeArgIndexes), 1, logicmoo_util_terms, logicmoo_util_terms).
index((makeArgIndexes), 2, logicmoo_util_terms, logicmoo_util_terms).
index((make_list), 3, logicmoo_util_terms, logicmoo_util_terms).
index((maptree), 3, logicmoo_util_terms, logicmoo_util_terms).
index((nd_predsubst), 3, logicmoo_util_terms, logicmoo_util_terms).
index((nd_predsubst1), 4, logicmoo_util_terms, logicmoo_util_terms).
index((nd_predsubst2), 3, logicmoo_util_terms, logicmoo_util_terms).
index((nd_subst), 4, logicmoo_util_terms, logicmoo_util_terms).
index((nd_subst1), 5, logicmoo_util_terms, logicmoo_util_terms).
index((nd_subst2), 4, logicmoo_util_terms, logicmoo_util_terms).
index((pred_delete), 4, logicmoo_util_terms, logicmoo_util_terms).
index((pred_juncts_to_list), 2, logicmoo_util_terms, logicmoo_util_terms).
index((pred_juncts_to_list), 3, logicmoo_util_terms, logicmoo_util_terms).
index((pred_subst), 5, logicmoo_util_terms, logicmoo_util_terms).
index((pred_term_parts), 3, logicmoo_util_terms, logicmoo_util_terms).
index((pred_term_parts_l), 3, logicmoo_util_terms, logicmoo_util_terms).
index((predsubst), 3, logicmoo_util_terms, logicmoo_util_terms).
index((proccess_status), 3, logicmoo_util_terms, logicmoo_util_terms).
index((read_each_term), 3, logicmoo_util_terms, logicmoo_util_terms).
index((remove_dupes), 2, logicmoo_util_terms, logicmoo_util_terms).
index((remove_dupes), 3, logicmoo_util_terms, logicmoo_util_terms).
index((subst), 4, logicmoo_util_terms, logicmoo_util_terms).
index((term_parts), 2, logicmoo_util_terms, logicmoo_util_terms).
index((term_parts_l), 2, logicmoo_util_terms, logicmoo_util_terms).
index((throw_if_true_else_fail), 2, logicmoo_util_terms, logicmoo_util_terms).
index((univ_safe), 2, logicmoo_util_terms, logicmoo_util_terms).
index((univ_term), 2, logicmoo_util_terms, logicmoo_util_terms).
index((weak_nd_subst), 4, logicmoo_util_terms, logicmoo_util_terms).
index((weak_nd_subst1), 5, logicmoo_util_terms, logicmoo_util_terms).
index((weak_nd_subst2), 4, logicmoo_util_terms, logicmoo_util_terms).
index((wsubst), 4, logicmoo_util_terms, logicmoo_util_terms).
index((expand_var_functors), 5, logicmoo_util_varfunctors, logicmoo_util_varfunctors).
index((set_functor_wrap), 1, logicmoo_util_varfunctors, logicmoo_util_varfunctors).
index((unset_functor_wrap), 0, logicmoo_util_varfunctors, logicmoo_util_varfunctors).
index((ain00), 1, logicmoo_varnames, logicmoo_util_varnames).
index((count_members_eq), 3, logicmoo_varnames, logicmoo_util_varnames).
index((all_different_vals), 1, logicmoo_varnames, logicmoo_util_varnames).
index((all_different_vals), 2, logicmoo_varnames, logicmoo_util_varnames).
index((set_varname), 2, logicmoo_varnames, logicmoo_util_varnames).
index((set_varname), 3, logicmoo_varnames, logicmoo_util_varnames).
index((write_functor), 2, logicmoo_varnames, logicmoo_util_varnames).
index((atom_subst_frak_0), 4, logicmoo_varnames, logicmoo_util_varnames).
index((renumbervars), 3, logicmoo_varnames, logicmoo_util_varnames).
index((b_implode_varnames), 1, logicmoo_varnames, logicmoo_util_varnames).
index((b_implode_varnames0), 1, logicmoo_varnames, logicmoo_util_varnames).
index((bad_varnamez), 1, logicmoo_varnames, logicmoo_util_varnames).
index((call_not_not), 1, logicmoo_varnames, logicmoo_util_varnames).
index((call_return_tf), 2, logicmoo_varnames, logicmoo_util_varnames).
index((check_varnames), 1, logicmoo_varnames, logicmoo_util_varnames).
index((clause_ref_file), 2, logicmoo_varnames, logicmoo_util_varnames).
index((clause_ref_vars), 2, logicmoo_varnames, logicmoo_util_varnames).
index((contains_badvarnames), 1, logicmoo_varnames, logicmoo_util_varnames).
index((contains_singletons), 1, logicmoo_varnames, logicmoo_util_varnames).
index((del_attr_type), 2, logicmoo_varnames, logicmoo_util_varnames).
index((copy_term_and_varnames), 2, logicmoo_varnames, logicmoo_util_varnames).
index((mpred_numbervars_with_names), 1, logicmoo_varnames, logicmoo_util_varnames).
index((ensure_vars_labled), 2, logicmoo_varnames, logicmoo_util_varnames).
index((ensure_vars_labled_r), 2, logicmoo_varnames, logicmoo_util_varnames).
index((fix_varcase_name), 2, logicmoo_varnames, logicmoo_util_varnames).
index((get_clause_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((get_clause_vars), 2, logicmoo_varnames, logicmoo_util_varnames).
index((get_clause_vars_copy), 2, logicmoo_varnames, logicmoo_util_varnames).
index((get_clause_vars_hb_int), 2, logicmoo_varnames, logicmoo_util_varnames).
index((imploded_copyvars), 2, logicmoo_varnames, logicmoo_util_varnames).
index((locate_clause_ref), 5, logicmoo_varnames, logicmoo_util_varnames).
index((lock_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((logicmoo_util_varnames_file), 0, logicmoo_varnames, logicmoo_util_varnames).
index((make_subterm_path), 3, logicmoo_varnames, logicmoo_util_varnames).
index((maybe_record_scanned_file), 0, logicmoo_varnames, logicmoo_util_varnames).
index((no_varnaming), 1, logicmoo_varnames, logicmoo_util_varnames).
index((no_vars_needed), 1, logicmoo_varnames, logicmoo_util_varnames).
index((not_member_eq), 2, logicmoo_varnames, logicmoo_util_varnames).
index((print_numbervars_maybe), 1, logicmoo_varnames, logicmoo_util_varnames).
index((print_numbervars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((read_source_file_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((read_source_file_vars_1), 1, logicmoo_varnames, logicmoo_util_varnames).
index((read_source_vars), 2, logicmoo_varnames, logicmoo_util_varnames).
index((replace_in_string_frak_0), 4, logicmoo_varnames, logicmoo_util_varnames).
index((save_clause_vars), 2, logicmoo_varnames, logicmoo_util_varnames).
index((save_clause_vars), 3, logicmoo_varnames, logicmoo_util_varnames).
index((save_clause_vars), 6, logicmoo_varnames, logicmoo_util_varnames).
index((save_file_source_vars), 3, logicmoo_varnames, logicmoo_util_varnames).
index((save_to_clause_ref), 3, logicmoo_varnames, logicmoo_util_varnames).
index((scan_source_files_for_varnames), 0, logicmoo_varnames, logicmoo_util_varnames).
index((dcall_if_verbose), 1, logicmoo_varnames, logicmoo_util_varnames).
index((dcall_when), 3, logicmoo_varnames, logicmoo_util_varnames).
index((snumbervars4), 4, logicmoo_varnames, logicmoo_util_varnames).
index((snumbervars5), 4, logicmoo_varnames, logicmoo_util_varnames).
index((subterm_path), 3, logicmoo_varnames, logicmoo_util_varnames).
index((term_expansion_save_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((try_get_body_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((try_get_head_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((try_get_inner_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((set_varname), 2, logicmoo_varnames, logicmoo_util_varnames).
index((try_save_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((unlock_vars), 1, logicmoo_varnames, logicmoo_util_varnames).
index((v_dif_rest), 2, logicmoo_varnames, logicmoo_util_varnames).
index((vmust), 1, logicmoo_varnames, logicmoo_util_varnames).
index((init_varname_stores), 1, logicmoo_varnames, logicmoo_util_varnames).
index((maybe_scan_source_files_for_varnames), 0, logicmoo_varnames, logicmoo_util_varnames).
index((check_thread_local_1m), 1, logicmoo_util_with_assertions, logicmoo_util_with_assertions).
index((to_thread_head_1m), 4, logicmoo_util_with_assertions, logicmoo_util_with_assertions).
index((w_tl), 2, logicmoo_util_with_assertions, logicmoo_util_with_assertions).
index((wno_tl), 2, logicmoo_util_with_assertions, logicmoo_util_with_assertions).
index((wtg), 2, logicmoo_util_with_assertions, logicmoo_util_with_assertions).
index((with_no_x), 1, logicmoo_util_with_assertions, logicmoo_util_with_assertions).
