
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu May 26 21:23:42 BST 2005
//----------------------------------------------------

package jplan.tools.lifeHist;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 17;
  public static final int INCREASE = 11;
  public static final int PLUS = 13;
  public static final int OR = 18;
  public static final int TEST = 7;
  public static final int SCALEDOWN = 10;
  public static final int NOT = 19;
  public static final int RBRA = 3;
  public static final int GREATER = 21;
  public static final int NAME = 5;
  public static final int RKET = 4;
  public static final int SCALEUP = 9;
  public static final int EQUALS = 20;
  public static final int COMMA = 2;
  public static final int NUMBER = 26;
  public static final int EOF = 0;
  public static final int MULT = 15;
  public static final int TIME = 25;
  public static final int GREATEREQ = 23;
  public static final int DIV = 16;
  public static final int DECREASE = 12;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int LESSEQ = 24;
  public static final int ASSIGN = 8;
  public static final int VAR = 6;
  public static final int LESS = 22;
  public static final int DOUBLE = 27;
}

