/*  Creator: make/0

    Purpose: Provide index for autoload
*/

index((will_call_after), 2, mpred_agenda, mpred_agenda).
index((add_later), 1, mpred_agenda, mpred_agenda).
index((after_mpred_load_pass2), 0, mpred_agenda, mpred_agenda).
index((agenda_do_prequery), 0, mpred_agenda, mpred_agenda).
index((agenda_mpred_repropigate), 0, mpred_agenda, mpred_agenda).
index((agenda_rescan_for_module_ready), 0, mpred_agenda, mpred_agenda).
index((agenda_rescan_mpred_ops), 0, mpred_agenda, mpred_agenda).
index((agenda_slow_op_enqueue), 1, mpred_agenda, mpred_agenda).
index((agenda_slow_op_restart), 0, mpred_agenda, mpred_agenda).
index((agenda_slow_op_todo), 1, mpred_agenda, mpred_agenda).
index((assertOnLoad), 1, mpred_agenda, mpred_agenda).
index((assert_next), 2, mpred_agenda, mpred_agenda).
index((call_after), 2, mpred_agenda, mpred_agenda).
index((call_after_mpred_load), 1, mpred_agenda, mpred_agenda).
index((call_after_mpred_load_slow), 1, mpred_agenda, mpred_agenda).
index((call_after_next), 2, mpred_agenda, mpred_agenda).
index((do_all_of), 1, mpred_agenda, mpred_agenda).
index((do_all_of_ilc), 1, mpred_agenda, mpred_agenda).
index((do_all_of_when), 1, mpred_agenda, mpred_agenda).
index((do_call_OnEachLoad), 0, mpred_agenda, mpred_agenda).
index((do_stuff_of_ilc), 1, mpred_agenda, mpred_agenda).
index((doing_agenda_slow_op), 0, mpred_agenda, mpred_agenda).
index((englishServerInterface), 1, mpred_agenda, mpred_agenda).
index((ensure_at_least_one_region), 0, mpred_agenda, mpred_agenda).
index((expire_post_change), 2, mpred_agenda, mpred_agenda).
index((expire_pre_change), 2, mpred_agenda, mpred_agenda).
index((finish_processing_dbase), 0, mpred_agenda, mpred_agenda).
index((gather_fact_heads), 2, mpred_agenda, mpred_agenda).
index((kb_db_op), 2, mpred_agenda, mpred_agenda).
index((more_to_do), 1, mpred_agenda, mpred_agenda).
index((mpred_one_minute_timer), 0, mpred_agenda, mpred_agenda).
index((mpred_one_second_timer), 0, mpred_agenda, mpred_agenda).
index((onEachLoad), 1, mpred_agenda, mpred_agenda).
index((onLoad), 1, mpred_agenda, mpred_agenda).
index((reduce_fact_heads), 4, mpred_agenda, mpred_agenda).
index((register_timer_thread), 3, mpred_agenda, mpred_agenda).
index((rerun_database_hooks), 0, mpred_agenda, mpred_agenda).
index((rescan_all), 0, mpred_agenda, mpred_agenda).
index((rescan_duplicated_facts), 0, mpred_agenda, mpred_agenda).
index((rescan_duplicated_facts), 2, mpred_agenda, mpred_agenda).
index((rescan_duplicated_facts), 3, mpred_agenda, mpred_agenda).
index((rescan_mpred_facts_local), 0, mpred_agenda, mpred_agenda).
index((rescan_mpred_loaded), 0, mpred_agenda, mpred_agenda).
index((rescan_mpred_loaded_pass2), 0, mpred_agenda, mpred_agenda).
index((rescandb), 0, mpred_agenda, mpred_agenda).
index((run_database_hooks), 2, mpred_agenda, mpred_agenda).
index((run_database_hooks_0), 2, mpred_agenda, mpred_agenda).
index((run_database_hooks_depth_1), 2, mpred_agenda, mpred_agenda).
index((setTemplate), 1, mpred_agenda, mpred_agenda).
index((show_cgoal), 1, mpred_agenda, mpred_agenda).
index((start_one_minute_timer), 0, mpred_agenda, mpred_agenda).
index((start_one_second_timer), 0, mpred_agenda, mpred_agenda).
index((suspend_timers), 0, mpred_agenda, mpred_agenda).
index((tick_every), 3, mpred_agenda, mpred_agenda).
index((time_tick), 2, mpred_agenda, mpred_agenda).
index((wfAssert), 1, mpred_agenda, mpred_agenda).
index((acceptable_xform), 2, mpred_expansion, mpred_expansion).
index((alt_calls), 1, mpred_expansion, mpred_expansion).
index((any_op_to_call_op), 2, mpred_expansion, mpred_expansion).
index((as_is_term), 1, mpred_expansion, mpred_expansion).
index((as_is_term0), 1, mpred_expansion, mpred_expansion).
index((compare_op), 4, mpred_expansion, mpred_expansion).
index((compound_all_open), 1, mpred_expansion, mpred_expansion).
index((conjoin_l), 3, mpred_expansion, mpred_expansion).
index((db_expand_0), 3, mpred_expansion, mpred_expansion).
index((db_expand_1), 3, mpred_expansion, mpred_expansion).
index((db_expand_2), 3, mpred_expansion, mpred_expansion).
index((db_expand_3), 3, mpred_expansion, mpred_expansion).
index((db_expand_4), 3, mpred_expansion, mpred_expansion).
index((db_expand_5), 3, mpred_expansion, mpred_expansion).
index((db_expand_a), 3, mpred_expansion, mpred_expansion).
index((db_expand_a_noloop), 3, mpred_expansion, mpred_expansion).
index((db_expand_chain), 3, mpred_expansion, mpred_expansion).
index((db_expand_final), 3, mpred_expansion, mpred_expansion).
index((db_expand_maplist), 5, mpred_expansion, mpred_expansion).
index((db_expand_term), 3, mpred_expansion, mpred_expansion).
index((db_expand_term0), 3, mpred_expansion, mpred_expansion).
index((db_expand_up), 4, mpred_expansion, mpred_expansion).
index((db_op_sentence), 4, mpred_expansion, mpred_expansion).
index((db_op_simpler), 3, mpred_expansion, mpred_expansion).
index((db_quf), 4, mpred_expansion, mpred_expansion).
index((db_quf_l), 5, mpred_expansion, mpred_expansion).
index((cyclic_break), 1, mpred_expansion, mpred_expansion).
index((db_quf_l_0), 5, mpred_expansion, mpred_expansion).
index((default_te), 3, mpred_expansion, mpred_expansion).
index((demodulize), 3, mpred_expansion, mpred_expansion).
index((do_expand_args), 3, mpred_expansion, mpred_expansion).
index((do_expand_args_c), 3, mpred_expansion, mpred_expansion).
index((do_expand_args_l), 3, mpred_expansion, mpred_expansion).
index((do_expand_args_pa), 4, mpred_expansion, mpred_expansion).
index((ex_argIsa), 3, mpred_expansion, mpred_expansion).
index((expand_goal_correct_argIsa), 2, mpred_expansion, mpred_expansion).
index((expand_props), 3, mpred_expansion, mpred_expansion).
index((expand_props), 4, mpred_expansion, mpred_expansion).
index((expand_to_hb), 3, mpred_expansion, mpred_expansion).
index((expanded_different), 2, mpred_expansion, mpred_expansion).
index((expanded_different_1), 2, mpred_expansion, mpred_expansion).
index((expanded_different_ic), 2, mpred_expansion, mpred_expansion).
index((expands_on), 2, mpred_expansion, mpred_expansion).
index((foreach_arg), 7, mpred_expansion, mpred_expansion).
index((from_univ), 4, mpred_expansion, mpred_expansion).
index((fully_expand), 3, mpred_expansion, mpred_expansion).
index((fully_expand), 2, mpred_expansion, mpred_expansion).
index((fully_expand0), 3, mpred_expansion, mpred_expansion).
index((fully_expand_clause), 3, mpred_expansion, mpred_expansion).
index((fully_expand_goal), 3, mpred_expansion, mpred_expansion).
index((fully_expand_head), 3, mpred_expansion, mpred_expansion).
index((fully_expand_now), 3, mpred_expansion, mpred_expansion).
index((fully_expand_warn), 3, mpred_expansion, mpred_expansion).
index((functor_declares_collectiontype), 2, mpred_expansion, mpred_expansion).
index((functor_declares_instance), 2, mpred_expansion, mpred_expansion).
index((functor_declares_instance_0), 2, mpred_expansion, mpred_expansion).
index((holds_args), 2, mpred_expansion, mpred_expansion).
index((if_expands_on), 3, mpred_expansion, mpred_expansion).
index((instTypePropsToType), 2, mpred_expansion, mpred_expansion).
index((into_functor_form), 3, mpred_expansion, mpred_expansion).
index((into_functor_form), 5, mpred_expansion, mpred_expansion).
index((into_mpred_form), 2, mpred_expansion, mpred_expansion).
index((into_mpred_form6), 6, mpred_expansion, mpred_expansion).
index((into_mpred_form_ilc), 2, mpred_expansion, mpred_expansion).
index((is_arity_pred), 1, mpred_expansion, mpred_expansion).
index((is_meta_functor), 3, mpred_expansion, mpred_expansion).
index((is_pred_declarer), 1, mpred_expansion, mpred_expansion).
index((is_relation_type), 1, mpred_expansion, mpred_expansion).
index((infix_op), 2, mpred_expansion, mpred_expansion).
index((is_unit), 1, mpred_expansion, mpred_expansion).
index((is_unit_functor), 1, mpred_expansion, mpred_expansion).
index((listToE), 2, mpred_expansion, mpred_expansion).
index((map_f), 2, mpred_expansion, mpred_expansion).
index((mpred_expand), 2, mpred_expansion, mpred_expansion).
index((must_expand), 1, mpred_expansion, mpred_expansion).
index((reduce_clause), 3, mpred_expansion, mpred_expansion).
index((same_terms), 2, mpred_expansion, mpred_expansion).
index((show_doall), 1, mpred_expansion, mpred_expansion).
index((show_doall), 1, mpred_expansion, mpred_expansion).
index((simply_functors), 3, mpred_expansion, mpred_expansion).
index((to_reduced_hb), 4, mpred_expansion, mpred_expansion).
index((transform_functor_holds), 5, mpred_expansion, mpred_expansion).
index((transform_holds), 3, mpred_expansion, mpred_expansion).
index((transform_holds_3), 3, mpred_expansion, mpred_expansion).
index((translateListOps), 8, mpred_expansion, mpred_expansion).
index((translateOneArg), 8, mpred_expansion, mpred_expansion).
index((translate_args), 9, mpred_expansion, mpred_expansion).
index((was_isa_syntax), 3, mpred_expansion, mpred_expansion).
index((additiveOp), 1, mpred_expansion, mpred_expansion).
index((comparitiveOp), 1, mpred_expansion, mpred_expansion).
index((which_t), 1, mpred_hooks, mpred_hooks).
index((add_arg_parts_of_speech), 4, mpred_hooks, mpred_hooks).
index((agent_action_queue), 3, mpred_hooks, mpred_hooks).
index((agent_session), 2, mpred_hooks, mpred_hooks).
index((agent_text_command), 4, mpred_hooks, mpred_hooks).
index((argIsa_call_or_undressed), 4, mpred_hooks, mpred_hooks).
index((call_f), 3, mpred_hooks, mpred_hooks).
index((call_f), 4, mpred_hooks, mpred_hooks).
index((call_f), 5, mpred_hooks, mpred_hooks).
index((call_f), 6, mpred_hooks, mpred_hooks).
index((call_f), 7, mpred_hooks, mpred_hooks).
index((call_f), 8, mpred_hooks, mpred_hooks).
index((call_mt_f), 10, mpred_hooks, mpred_hooks).
index((call_mt_f), 4, mpred_hooks, mpred_hooks).
index((call_mt_f), 5, mpred_hooks, mpred_hooks).
index((call_mt_f), 6, mpred_hooks, mpred_hooks).
index((call_mt_f), 7, mpred_hooks, mpred_hooks).
index((call_mt_f), 8, mpred_hooks, mpred_hooks).
index((call_mt_f), 9, mpred_hooks, mpred_hooks).
index((call_mt_t), 10, mpred_hooks, mpred_hooks).
index((call_mt_t), 4, mpred_hooks, mpred_hooks).
index((call_mt_t), 5, mpred_hooks, mpred_hooks).
index((call_mt_t), 6, mpred_hooks, mpred_hooks).
index((call_mt_t), 7, mpred_hooks, mpred_hooks).
index((call_mt_t), 8, mpred_hooks, mpred_hooks).
index((call_mt_t), 9, mpred_hooks, mpred_hooks).
index((call_t), 3, mpred_hooks, mpred_hooks).
index((call_t), 4, mpred_hooks, mpred_hooks).
index((call_t), 5, mpred_hooks, mpred_hooks).
index((call_t), 6, mpred_hooks, mpred_hooks).
index((call_t), 7, mpred_hooks, mpred_hooks).
index((call_t), 8, mpred_hooks, mpred_hooks).
index((call_which_t), 3, mpred_hooks, mpred_hooks).
index((call_which_t), 4, mpred_hooks, mpred_hooks).
index((call_which_t), 5, mpred_hooks, mpred_hooks).
index((call_which_t), 6, mpred_hooks, mpred_hooks).
index((call_which_t), 7, mpred_hooks, mpred_hooks).
index((call_which_t), 8, mpred_hooks, mpred_hooks).
index((compute_value), 2, mpred_hooks, mpred_hooks).
index((compute_value_no_dice), 2, mpred_hooks, mpred_hooks).
index((create_random_fact), 1, mpred_hooks, mpred_hooks).
index((deduce_facts), 2, mpred_hooks, mpred_hooks).
index((fact_always_true), 1, mpred_hooks, mpred_hooks).
index((fact_is_false), 2, mpred_hooks, mpred_hooks).
index((fact_maybe_deduced), 1, mpred_hooks, mpred_hooks).
index((flatten_append), 3, mpred_hooks, mpred_hooks).
index((fskel), 7, mpred_hooks, mpred_hooks).
index((holds_f), 1, mpred_hooks, mpred_hooks).
index((holds_f), 2, mpred_hooks, mpred_hooks).
index((holds_f), 3, mpred_hooks, mpred_hooks).
index((holds_f), 4, mpred_hooks, mpred_hooks).
index((holds_f), 5, mpred_hooks, mpred_hooks).
index((holds_f), 6, mpred_hooks, mpred_hooks).
index((holds_f), 7, mpred_hooks, mpred_hooks).
index((holds_f), 8, mpred_hooks, mpred_hooks).
index((holds_plist_t), 2, mpred_hooks, mpred_hooks).
index((holds_relaxed_0_t), 4, mpred_hooks, mpred_hooks).
index((holds_relaxed_t), 3, mpred_hooks, mpred_hooks).
index((holds_t), 1, mpred_hooks, mpred_hooks).
index((holds_t), 2, mpred_hooks, mpred_hooks).
index((holds_t), 3, mpred_hooks, mpred_hooks).
index((holds_t), 4, mpred_hooks, mpred_hooks).
index((holds_t), 5, mpred_hooks, mpred_hooks).
index((holds_t), 6, mpred_hooks, mpred_hooks).
index((holds_t), 7, mpred_hooks, mpred_hooks).
index((holds_t), 8, mpred_hooks, mpred_hooks).
index((hooked_random_instance), 3, mpred_hooks, mpred_hooks).
index((if_result), 2, mpred_hooks, mpred_hooks).
index((insert_into), 4, mpred_hooks, mpred_hooks).
index((into_plist), 2, mpred_hooks, mpred_hooks).
index((into_plist_arities), 4, mpred_hooks, mpred_hooks).
index((inverse_args), 2, mpred_hooks, mpred_hooks).
index((isCycPredArity_ignoreable), 2, mpred_hooks, mpred_hooks).
index((list_update_op), 3, mpred_hooks, mpred_hooks).
index((loaded_external_kbs), 0, mpred_hooks, mpred_hooks).
index((loading_module_h), 1, mpred_hooks, mpred_hooks).
index((local_term_anglify), 2, mpred_hooks, mpred_hooks).
index((loop_check_mpred), 1, mpred_hooks, mpred_hooks).
index((mpred_fact_arity), 2, mpred_hooks, mpred_hooks).
index((mpred_module_ready), 0, mpred_hooks, mpred_hooks).
index((mpred_pa_call), 3, mpred_hooks, mpred_hooks).
index((mpred_plist_t), 2, mpred_hooks, mpred_hooks).
index((never_mpred_mpred), 1, mpred_hooks, mpred_hooks).
index((prologHybridFact), 1, mpred_hooks, mpred_hooks).
index((replace_arg), 4, mpred_hooks, mpred_hooks).
index((replace_nth_arglist), 4, mpred_hooks, mpred_hooks).
index((replace_nth_ref), 5, mpred_hooks, mpred_hooks).
index((same_vars), 2, mpred_hooks, mpred_hooks).
index((session_agent), 2, mpred_hooks, mpred_hooks).
index((session_io), 4, mpred_hooks, mpred_hooks).
index((telnet_fmt_shown), 3, mpred_hooks, mpred_hooks).
index((term_anglify_last), 2, mpred_hooks, mpred_hooks).
index((term_anglify_np), 3, mpred_hooks, mpred_hooks).
index((term_anglify_np_last), 3, mpred_hooks, mpred_hooks).
index((tf_result), 2, mpred_hooks, mpred_hooks).
index((tms_reject_why), 2, mpred_hooks, mpred_hooks).
index((update_value), 3, mpred_hooks, mpred_hooks).
index((use_cyc_database), 0, mpred_hooks, mpred_hooks).
index((use_kif), 2, mpred_hooks, mpred_hooks).
index((verb_after_arg), 3, mpred_hooks, mpred_hooks).
index((xcall_f), 1, mpred_hooks, mpred_hooks).
index((xcall_f), 2, mpred_hooks, mpred_hooks).
index((xcall_f), 3, mpred_hooks, mpred_hooks).
index((xcall_f), 4, mpred_hooks, mpred_hooks).
index((xcall_f), 5, mpred_hooks, mpred_hooks).
index((xcall_f), 6, mpred_hooks, mpred_hooks).
index((xcall_f), 7, mpred_hooks, mpred_hooks).
index((xcall_t), 1, mpred_hooks, mpred_hooks).
index((xcall_t), 2, mpred_hooks, mpred_hooks).
index((xcall_t), 3, mpred_hooks, mpred_hooks).
index((xcall_t), 4, mpred_hooks, mpred_hooks).
index((xcall_t), 5, mpred_hooks, mpred_hooks).
index((xcall_t), 6, mpred_hooks, mpred_hooks).
index((xcall_t), 7, mpred_hooks, mpred_hooks).
index((deducedSimply), 1, mpred_kb_ops, mpred_kb_ops).
index((how_to_op), 2, mpred_kb_ops, mpred_kb_ops).
index((is_callable), 1, mpred_kb_ops, mpred_kb_ops).
index((lookup_inverted_op), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_1), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_2), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_3), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_op), 2, mpred_kb_ops, mpred_kb_ops).
index((naf), 1, mpred_kb_ops, mpred_kb_ops).
index((oncely), 1, mpred_kb_ops, mpred_kb_ops).
index((reduce_mpred_op), 2, mpred_kb_ops, mpred_kb_ops).
index((second_order), 2, mpred_kb_ops, mpred_kb_ops).
index((whenAnd), 2, mpred_kb_ops, mpred_kb_ops).
index((draw_line), 0, mpred_listing, mpred_listing).
index((loop_check_just), 1, mpred_listing, mpred_listing).
index((mpred_ask), 2, mpred_listing, mpred_listing).
index((mpred_classify_facts), 4, mpred_listing, mpred_listing).
index((mpred_command), 3, mpred_listing, mpred_listing).
index((mpred_contains_term), 2, mpred_listing, mpred_listing).
index((mpred_interactive_why), 0, mpred_listing, mpred_listing).
index((mpred_interactive_why), 1, mpred_listing, mpred_listing).
index((mpred_list_triggers_0), 1, mpred_listing, mpred_listing).
index((mpred_list_triggers_1), 1, mpred_listing, mpred_listing).
index((mpred_list_triggers_nlc), 1, mpred_listing, mpred_listing).
index((mpred_list_triggers_types), 1, mpred_listing, mpred_listing).
index((lqu), 0, mpred_listing, mpred_listing).
index((mpred_select_justificationNode), 3, mpred_listing, mpred_listing).
index((mpred_trace_item), 2, mpred_listing, mpred_listing).
index((mpred_why), 0, mpred_listing, mpred_listing).
index((get_clause_vars_for_print), 2, mpred_listing, mpred_listing).
index((mpred_why), 1, mpred_listing, mpred_listing).
index((mpred_why1), 1, mpred_listing, mpred_listing).
index((mpred_whyBrouse), 2, mpred_listing, mpred_listing).
index((mpred_why_command), 3, mpred_listing, mpred_listing).
index((nth_mpred_call), 3, mpred_listing, mpred_listing).
index((pp_facts), 0, mpred_listing, mpred_listing).
index((pp_facts), 1, mpred_listing, mpred_listing).
index((pp_facts), 2, mpred_listing, mpred_listing).
index((pp_item), 2, mpred_listing, mpred_listing).
index((pp_items), 2, mpred_listing, mpred_listing).
index((pp_justification1), 2, mpred_listing, mpred_listing).
index((pp_justifications), 2, mpred_listing, mpred_listing).
index((pp_justifications2), 3, mpred_listing, mpred_listing).
index((pp_rules), 0, mpred_listing, mpred_listing).
index((pp_supports), 0, mpred_listing, mpred_listing).
index((pp_triggers), 0, mpred_listing, mpred_listing).
index((pp_why), 1, mpred_listing, mpred_listing).
index((pppfc), 0, mpred_listing, mpred_listing).
index((whymemory), 2, mpred_listing, mpred_listing).
index((print_db_items), 1, mpred_listing, mpred_listing).
index((print_db_items), 2, mpred_listing, mpred_listing).
index((print_db_items), 3, mpred_listing, mpred_listing).
index((print_db_items), 4, mpred_listing, mpred_listing).
index((print_db_items_and_neg), 3, mpred_listing, mpred_listing).
index((show_pred_info), 1, mpred_listing, mpred_listing).
index((show_pred_info_0), 1, mpred_listing, mpred_listing).
index((why), 1, mpred_listing, mpred_listing).
index((add_from_file), 1, mpred_loader, mpred_loader).
index((add_term), 2, mpred_loader, mpred_loader).
index((assert_kif), 1, mpred_loader, mpred_loader).
index((assert_kif_dolce), 1, mpred_loader, mpred_loader).
index((assert_until_eof), 1, mpred_loader, mpred_loader).
index((decl_mpred_user_kb), 1, mpred_loader, mpred_loader).
index((set_mpred_user_kb), 1, mpred_loader, mpred_loader).
index((get_mpred_user_kb), 1, mpred_loader, mpred_loader).
index((begin_pfc), 0, mpred_loader, mpred_loader).
index((call_file_command), 4, mpred_loader, mpred_loader).
index((call_with_module), 2, mpred_loader, mpred_loader).
index((call_with_source_module), 2, mpred_loader, mpred_loader).
index((can_be_dynamic), 1, mpred_loader, mpred_loader).
index((cl_assert), 2, mpred_loader, mpred_loader).
index((clear_predicates), 1, mpred_loader, mpred_loader).
index((collect_expansions), 3, mpred_loader, mpred_loader).
index((compile_clause), 1, mpred_loader, mpred_loader).
index((compile_this), 4, mpred_loader, mpred_loader).
index((convert_side_effect), 2, mpred_loader, mpred_loader).
index((convert_side_effect), 3, mpred_loader, mpred_loader).
index((convert_side_effect_buggy), 2, mpred_loader, mpred_loader).
index((current_context_module), 1, mpred_loader, mpred_loader).
index((current_op_alias), 2, mpred_loader, mpred_loader).
index((decache_file_type), 1, mpred_loader, mpred_loader).
index((mpred_process_input_1), 1, mpred_loader, mpred_loader).
index((mpred_ops), 0, mpred_loader, mpred_loader).
index((declare_load_dbase), 1, mpred_loader, mpred_loader).
index((disable_mpred_expansion), 0, mpred_loader, mpred_loader).
index((disable_mpreds_in_current_file), 0, mpred_loader, mpred_loader).
index((do_end_of_file_actions), 4, mpred_loader, mpred_loader).
index((do_end_of_file_actions_real), 0, mpred_loader, mpred_loader).
index((doall_and_fail), 1, mpred_loader, mpred_loader).
index((dyn_begin), 0, mpred_loader, mpred_loader).
index((dyn_end), 0, mpred_loader, mpred_loader).
index((enable_mpred_expansion), 0, mpred_loader, mpred_loader).
index((end_module_type), 1, mpred_loader, mpred_loader).
index((end_module_type), 2, mpred_loader, mpred_loader).
index((ensure_loaded_no_mpreds), 1, mpred_loader, mpred_loader).
index((ensure_mpred_file_consulted), 2, mpred_loader, mpred_loader).
index((ensure_mpred_file_loaded), 1, mpred_loader, mpred_loader).
index((ensure_mpred_file_loaded), 2, mpred_loader, mpred_loader).
index((ensure_prolog_file_consulted), 2, mpred_loader, mpred_loader).
index((etrace), 0, mpred_loader, mpred_loader).
index((expand_in_mpred_kb_module), 2, mpred_loader, mpred_loader).
index((expanded_already_functor), 1, mpred_loader, mpred_loader).
index((file_begin), 1, mpred_loader, mpred_loader).
index((file_end), 1, mpred_loader, mpred_loader).
index((finish_processing_world), 0, mpred_loader, mpred_loader).
index((force_reload_mpred_file), 1, mpred_loader, mpred_loader).
index((force_reload_mpred_file), 2, mpred_loader, mpred_loader).
index((from_kif_string), 2, mpred_loader, mpred_loader).
index((convert_if_kif_string), 4, mpred_loader, mpred_loader).
index((get_file_type), 2, mpred_loader, mpred_loader).
index((get_lang), 1, mpred_loader, mpred_loader).
index((get_last_time_file), 3, mpred_loader, mpred_loader).
index((get_op_alias), 2, mpred_loader, mpred_loader).
index((gload), 0, mpred_loader, mpred_loader).
index((guess_file_type_loader), 2, mpred_loader, mpred_loader).
index((hdr_debug), 2, mpred_loader, mpred_loader).
index((in_include_file), 0, mpred_loader, mpred_loader).
index((in_mpred_kb_module), 0, mpred_loader, mpred_loader).
index((include_mpred_files), 1, mpred_loader, mpred_loader).
index((inside_file), 1, mpred_loader, mpred_loader).
index((is_code_body), 1, mpred_loader, mpred_loader).
index((is_compiling), 0, mpred_loader, mpred_loader).
index((is_compiling_sourcecode), 0, mpred_loader, mpred_loader).
index((is_kif_string), 1, mpred_loader, mpred_loader).
index((is_prolog_xform), 1, mpred_loader, mpred_loader).
index((is_mpred_file), 1, mpred_loader, mpred_loader).
index((lang_op_alias), 3, mpred_loader, mpred_loader).
index((load_file_dir), 2, mpred_loader, mpred_loader).
index((load_file_some_type), 2, mpred_loader, mpred_loader).
index((load_file_term_to_command_or_fail), 2, mpred_loader, mpred_loader).
index((mpred_expander_now_physically), 4, mpred_loader, mpred_loader).
index((load_init_world), 2, mpred_loader, mpred_loader).
index((load_language_file), 1, mpred_loader, mpred_loader).
index((load_mpred_files), 0, mpred_loader, mpred_loader).
index((load_mpred_on_file_end), 2, mpred_loader, mpred_loader).
index((loader_side_effect_capture_only), 2, mpred_loader, mpred_loader).
index((loader_side_effect_verify_only), 2, mpred_loader, mpred_loader).
index((loader_term_expansion), 2, mpred_loader, mpred_loader).
index((loading_source_file), 1, mpred_loader, mpred_loader).
index((make_db_listing), 0, mpred_loader, mpred_loader).
index((make_dynamic), 1, mpred_loader, mpred_loader).
index((with_ukb), 2, mpred_loader, mpred_loader).
index((module_typed_term_expand), 2, mpred_loader, mpred_loader).
index((module_typed_term_expand), 5, mpred_loader, mpred_loader).
index((mpred_begin), 0, mpred_loader, mpred_loader).
index((mpred_directive_expansion), 2, mpred_loader, mpred_loader).
index((mpred_expand_inside_file_anyways), 0, mpred_loader, mpred_loader).
index((mpred_expand_inside_file_anyways), 1, mpred_loader, mpred_loader).
index((mpred_expander), 4, mpred_loader, mpred_loader).
index((mpred_expander_now), 2, mpred_loader, mpred_loader).
index((mpred_expander_now_one), 4, mpred_loader, mpred_loader).
index((mpred_expander_now_one_cc), 4, mpred_loader, mpred_loader).
index((mpred_implode_varnames), 1, mpred_loader, mpred_loader).
index((mpred_loader_file), 0, mpred_loader, mpred_loader).
index((mpred_prolog_only_file), 1, mpred_loader, mpred_loader).
index((mpred_may_expand), 0, mpred_loader, mpred_loader).
index((mpred_may_expand_module), 1, mpred_loader, mpred_loader).
index((mpred_maybe_skip), 1, mpred_loader, mpred_loader).
index((mpred_process_input), 2, mpred_loader, mpred_loader).
index((mpred_term_expansion), 2, mpred_loader, mpred_loader).
index((mpred_use_module), 1, mpred_loader, mpred_loader).
index((must_compile_special_clause), 1, mpred_loader, mpred_loader).
index((must_load_file_term_to_command), 2, mpred_loader, mpred_loader).
index((must_locate_file), 2, mpred_loader, mpred_loader).
index((myDebugOnError), 1, mpred_loader, mpred_loader).
index((onEndOfFile), 1, mpred_loader, mpred_loader).
index((onEndOfFile), 2, mpred_loader, mpred_loader).
index((op_alias), 2, mpred_loader, mpred_loader).
index((op_lang), 1, mpred_loader, mpred_loader).
index((pl_to_mpred_syntax), 2, mpred_loader, mpred_loader).
index((pl_to_mpred_syntax_h), 2, mpred_loader, mpred_loader).
index((pop_predicates), 2, mpred_loader, mpred_loader).
index((process_this_script), 0, mpred_loader, mpred_loader).
index((process_this_script), 1, mpred_loader, mpred_loader).
index((process_this_script0), 1, mpred_loader, mpred_loader).
index((prolog_load_file_loop_checked), 2, mpred_loader, mpred_loader).
index((prolog_load_file_nlc), 2, mpred_loader, mpred_loader).
index((push_predicates), 2, mpred_loader, mpred_loader).
index((read_one_term), 2, mpred_loader, mpred_loader).
index((read_one_term), 3, mpred_loader, mpred_loader).
index((register_module_type), 1, mpred_loader, mpred_loader).
index((register_module_type), 2, mpred_loader, mpred_loader).
index((rsavedb), 0, mpred_loader, mpred_loader).
index((savedb), 0, mpred_loader, mpred_loader).
index((scan_updates), 0, mpred_loader, mpred_loader).
index((show_bool), 1, mpred_loader, mpred_loader).
index((show_interesting_cl), 2, mpred_loader, mpred_loader).
index((show_load_context), 0, mpred_loader, mpred_loader).
index((simplify_why), 2, mpred_loader, mpred_loader).
index((simplify_why_r), 4, mpred_loader, mpred_loader).
index((stream_pos), 1, mpred_loader, mpred_loader).
index((term_expand_local_each), 5, mpred_loader, mpred_loader).
index((transform_opers), 3, mpred_loader, mpred_loader).
index((use_file_type_loader), 2, mpred_loader, mpred_loader).
index((use_was_isa), 3, mpred_loader, mpred_loader).
index((was_exported_content), 3, mpred_loader, mpred_loader).
index((with_mpred_expansions), 1, mpred_loader, mpred_loader).
index((with_no_mpred_expansions), 1, mpred_loader, mpred_loader).
index((with_source_module), 2, mpred_loader, mpred_loader).
index((current_op_alias), 2, mpred_loader, mpred_loader).
index((kb_dynamic), 1, mpred_loader, mpred_loader).
index((make_declared), 1, mpred_loader, mpred_loader).
index((make_reachable), 2, mpred_loader, mpred_loader).
index((import_predicate), 2, mpred_loader, mpred_loader).
index((prolog_load_file_loop_checked), 2, mpred_loader, mpred_loader).
index((registered_mpred_file), 1, mpred_loader, mpred_loader).
index((never_registered_mpred_file), 1, mpred_loader, mpred_loader).
index((registered_module_type), 2, mpred_loader, mpred_loader).
index((mpred_loader_module_transparent), 1, mpred_loader, mpred_loader).
index((convert_side_effect_0a), 2, mpred_loader, mpred_loader).
index((convert_side_effect_0b), 2, mpred_loader, mpred_loader).
index((convert_side_effect_0c), 2, mpred_loader, mpred_loader).
index((is_mpred_file0), 1, mpred_loader, mpred_loader).
index((load_file_term_to_command_0c), 2, mpred_loader, mpred_loader).
index((load_file_term_to_command_1), 3, mpred_loader, mpred_loader).
index((load_file_term_to_command_1b), 3, mpred_loader, mpred_loader).
index((load_file_term_to_command_2), 3, mpred_loader, mpred_loader).
index((mpred_process_input_1), 1, mpred_loader, mpred_loader).
index((must_mpred_term_expansion_2), 2, mpred_loader, mpred_loader).
index((pl_to_mpred_syntax0), 2, mpred_loader, mpred_loader).
index((process_this_script0), 1, mpred_loader, mpred_loader).
index((prolog_load_file_loop_checked_0), 2, mpred_loader, mpred_loader).
index((prolog_load_file_nlc_0), 2, mpred_loader, mpred_loader).
index((transform_opers_0), 2, mpred_loader, mpred_loader).
index((transform_opers_1), 2, mpred_loader, mpred_loader).
index((xfile_module_term_expansion_pass_3), 7, mpred_loader, mpred_loader).
index((add_reprop), 2, mpred_pfc, mpred_pfc).
index((add_side_effect), 2, mpred_pfc, mpred_pfc).
index((all_closed), 1, mpred_pfc, mpred_pfc).
index((append_as_first_arg), 3, mpred_pfc, mpred_pfc).
index((assert_eq_quitely), 1, mpred_pfc, mpred_pfc).
index((assert_i), 1, mpred_pfc, mpred_pfc).
index((assert_u), 1, mpred_pfc, mpred_pfc).
index((assert_u), 3, mpred_pfc, mpred_pfc).
index((asserta_i), 1, mpred_pfc, mpred_pfc).
index((assertz_i), 1, mpred_pfc, mpred_pfc).
index((assertz_u), 1, mpred_pfc, mpred_pfc).
index((check_context_module), 0, mpred_pfc, mpred_pfc).
index((assertz_u), 3, mpred_pfc, mpred_pfc).
index((assumption), 1, mpred_pfc, mpred_pfc).
index((assumptions), 2, mpred_pfc, mpred_pfc).
index((assumptions1), 2, mpred_pfc, mpred_pfc).
index((attvar_op), 2, mpred_pfc, mpred_pfc).
index((baseable), 2, mpred_pfc, mpred_pfc).
index((baseable_list), 2, mpred_pfc, mpred_pfc).
index((brake), 1, mpred_pfc, mpred_pfc).
index((build_code_test), 3, mpred_pfc, mpred_pfc).
index((build_consequent), 3, mpred_pfc, mpred_pfc).
index((build_neg_test), 4, mpred_pfc, mpred_pfc).
index((build_rhs), 3, mpred_pfc, mpred_pfc).
index((build_rule), 3, mpred_pfc, mpred_pfc).
index((build_trigger), 4, mpred_pfc, mpred_pfc).
index((bwc), 0, mpred_pfc, mpred_pfc).
index((call_i), 1, mpred_pfc, mpred_pfc).
index((call_prologsys), 1, mpred_pfc, mpred_pfc).
index((call_u), 1, mpred_pfc, mpred_pfc).
index((call_u), 2, mpred_pfc, mpred_pfc).
index((call_with_bc_triggers), 1, mpred_pfc, mpred_pfc).
index((clause_asserted_local), 1, mpred_pfc, mpred_pfc).
index((clause_i), 2, mpred_pfc, mpred_pfc).
index((clause_i), 3, mpred_pfc, mpred_pfc).
index((clause_or_call), 2, mpred_pfc, mpred_pfc).
index((clause_u), 2, mpred_pfc, mpred_pfc).
index((clause_u), 3, mpred_pfc, mpred_pfc).
index((cnstrn), 1, mpred_pfc, mpred_pfc).
index((cnstrn), 2, mpred_pfc, mpred_pfc).
index((cnstrn0), 2, mpred_pfc, mpred_pfc).
index((code_sentence_op), 1, mpred_pfc, mpred_pfc).
index((compute_resolve), 3, mpred_pfc, mpred_pfc).
index((compute_resolve), 5, mpred_pfc, mpred_pfc).
index((correctify_support), 2, mpred_pfc, mpred_pfc).
index((cwc), 0, mpred_pfc, mpred_pfc).
index((defaultmpred_select), 2, mpred_pfc, mpred_pfc).
index((if_missing_mask), 3, mpred_pfc, mpred_pfc).
index((if_missing_mask), 4, mpred_pfc, mpred_pfc).
index((which_missing_argnum), 2, mpred_pfc, mpred_pfc).
index((erase_w_attvars), 2, mpred_pfc, mpred_pfc).
index((exact_args), 1, mpred_pfc, mpred_pfc).
index((fc_eval_action), 2, mpred_pfc, mpred_pfc).
index((fcnt), 2, mpred_pfc, mpred_pfc).
index((mmsg), 2, mpred_pfc, mpred_pfc).
index((fcnt0), 2, mpred_pfc, mpred_pfc).
index((fcpt), 2, mpred_pfc, mpred_pfc).
index((f_to_mfa), 4, mpred_pfc, mpred_pfc).
index((fa_to_p), 3, mpred_pfc, mpred_pfc).
index((w_get_fa), 3, mpred_pfc, mpred_pfc).
index((fcpt0), 2, mpred_pfc, mpred_pfc).
index((foreachl_do), 2, mpred_pfc, mpred_pfc).
index((fwc), 0, mpred_pfc, mpred_pfc).
index((fwd_ok), 1, mpred_pfc, mpred_pfc).
index((get_fa), 3, mpred_pfc, mpred_pfc).
index((get_next_fact), 2, mpred_pfc, mpred_pfc).
index((get_source_ref), 1, mpred_pfc, mpred_pfc).
index((get_source_ref1), 1, mpred_pfc, mpred_pfc).
index((get_why), 4, mpred_pfc, mpred_pfc).
index((has_body_atom), 2, mpred_pfc, mpred_pfc).
index((has_cl), 1, mpred_pfc, mpred_pfc).
index((has_db_clauses), 1, mpred_pfc, mpred_pfc).
index((has_functor), 1, mpred_pfc, mpred_pfc).
index((is_action_body), 1, mpred_pfc, mpred_pfc).
index((is_already_supported), 3, mpred_pfc, mpred_pfc).
index((is_bc_body), 1, mpred_pfc, mpred_pfc).
index((is_disabled_clause), 1, mpred_pfc, mpred_pfc).
index((is_fc_body), 1, mpred_pfc, mpred_pfc).
index((is_mpred_action), 1, mpred_pfc, mpred_pfc).
index((is_relative), 1, mpred_pfc, mpred_pfc).
index((is_reprop), 1, mpred_pfc, mpred_pfc).
index((is_reprop_0), 1, mpred_pfc, mpred_pfc).
index((is_resolved), 1, mpred_pfc, mpred_pfc).
index((is_retract_first), 1, mpred_pfc, mpred_pfc).
index((is_side_effect_disabled), 0, mpred_pfc, mpred_pfc).
index((justification), 2, mpred_pfc, mpred_pfc).
index((justifications), 2, mpred_pfc, mpred_pfc).
index((loop_check_nr), 1, mpred_pfc, mpred_pfc).
index((make_uu_remove), 1, mpred_pfc, mpred_pfc).
index((map_literals), 2, mpred_pfc, mpred_pfc).
index((map_literals), 3, mpred_pfc, mpred_pfc).
index((map_unless), 4, mpred_pfc, mpred_pfc).
index((match_source_ref1), 1, mpred_pfc, mpred_pfc).
index((maybeSupport), 2, mpred_pfc, mpred_pfc).
index((meta_wrapper_rule), 1, mpred_pfc, mpred_pfc).
index((ain), 1, mpred_pfc, mpred_pfc).
index((ain), 2, mpred_pfc, mpred_pfc).
index((mpred_ain), 1, mpred_pfc, mpred_pfc).
index((mpred_aina), 1, mpred_pfc, mpred_pfc).
index((mpred_ainz), 1, mpred_pfc, mpred_pfc).
index((mpred_ainz), 2, mpred_pfc, mpred_pfc).
index((mpred_ain), 2, mpred_pfc, mpred_pfc).
index((ain_actiontrace), 2, mpred_pfc, mpred_pfc).
index((ain_db_to_head), 2, mpred_pfc, mpred_pfc).
index((ain_fast), 1, mpred_pfc, mpred_pfc).
index((ain_fast), 2, mpred_pfc, mpred_pfc).
index((ain_fast_sp), 2, mpred_pfc, mpred_pfc).
index((ain_fast_sp0), 2, mpred_pfc, mpred_pfc).
index((ain_fast_timed), 2, mpred_pfc, mpred_pfc).
index((ain_minfo), 1, mpred_pfc, mpred_pfc).
index((ain_minfo), 2, mpred_pfc, mpred_pfc).
index((ain_minfo_2), 2, mpred_pfc, mpred_pfc).
index((ain_rule0), 1, mpred_pfc, mpred_pfc).
index((ain_rule_if_rule), 1, mpred_pfc, mpred_pfc).
index((ain_support), 2, mpred_pfc, mpred_pfc).
index((ain_t), 2, mpred_pfc, mpred_pfc).
index((ain_trigger), 2, mpred_pfc, mpred_pfc).
index((ain_trigger_0), 3, mpred_pfc, mpred_pfc).
index((aina_i), 2, mpred_pfc, mpred_pfc).
index((ainz_i), 2, mpred_pfc, mpred_pfc).
index((mpred_axiom), 1, mpred_pfc, mpred_pfc).
index((mpred_bc_only), 1, mpred_pfc, mpred_pfc).
index((mpred_call_with_no_triggers_uncaugth), 1, mpred_pfc, mpred_pfc).
index((mpred_bt_pt_combine), 3, mpred_pfc, mpred_pfc).
index((req), 1, mpred_pfc, mpred_pfc).
index((mpred_call_0), 1, mpred_pfc, mpred_pfc).
index((mpred_call_1), 3, mpred_pfc, mpred_pfc).
index((mpred_call_only_facts), 1, mpred_pfc, mpred_pfc).
index((mpred_call_only_facts), 2, mpred_pfc, mpred_pfc).
index((mreq), 1, mpred_pfc, mpred_pfc).
index((mpred_call_t_exact), 1, mpred_pfc, mpred_pfc).
index((mpred_call_with_no_triggers), 1, mpred_pfc, mpred_pfc).
index((mpred_call_with_no_triggers_bound), 1, mpred_pfc, mpred_pfc).
index((mpred_child), 2, mpred_pfc, mpred_pfc).
index((mpred_children), 2, mpred_pfc, mpred_pfc).
index((mpred_clause), 3, mpred_pfc, mpred_pfc).
index((mpred_clause_i), 1, mpred_pfc, mpred_pfc).
index((mpred_clause_is_asserted), 2, mpred_pfc, mpred_pfc).
index((mpred_clause_is_asserted_hb_nonunify), 2, mpred_pfc, mpred_pfc).
index((mpred_cleanup), 0, mpred_pfc, mpred_pfc).
index((mpred_cleanup), 2, mpred_pfc, mpred_pfc).
index((mpred_cleanup_0), 1, mpred_pfc, mpred_pfc).
index((mpred_compile_rhsTerm), 3, mpred_pfc, mpred_pfc).
index((mpred_connective), 1, mpred_pfc, mpred_pfc).
index((mpred_current), 0, mpred_pfc, mpred_pfc).
index((mpred_current_db), 1, mpred_pfc, mpred_pfc).
index((mpred_current_op_support), 1, mpred_pfc, mpred_pfc).
index((mpred_database_item), 1, mpred_pfc, mpred_pfc).
index((mpred_database_term), 1, mpred_pfc, mpred_pfc).
index((mpred_db_type), 2, mpred_pfc, mpred_pfc).
index((mpred_deep_support), 2, mpred_pfc, mpred_pfc).
index((mpred_deep_support0), 2, mpred_pfc, mpred_pfc).
index((mpred_define_bc_rule), 3, mpred_pfc, mpred_pfc).
index((mpred_descendant), 2, mpred_pfc, mpred_pfc).
index((mpred_descendant1), 3, mpred_pfc, mpred_pfc).
index((mpred_descendants), 2, mpred_pfc, mpred_pfc).
index((mpred_each_literal), 2, mpred_pfc, mpred_pfc).
index((mpred_enqueue), 2, mpred_pfc, mpred_pfc).
index((mpred_error), 1, mpred_pfc, mpred_pfc).
index((mpred_error), 2, mpred_pfc, mpred_pfc).
index((mpred_eval_lhs), 2, mpred_pfc, mpred_pfc).
index((mpred_eval_lhs0), 2, mpred_pfc, mpred_pfc).
index((mpred_eval_rhs1), 2, mpred_pfc, mpred_pfc).
index((mpred_eval_rhs_0), 2, mpred_pfc, mpred_pfc).
index((mpred_fact), 1, mpred_pfc, mpred_pfc).
index((mpred_fact), 2, mpred_pfc, mpred_pfc).
index((mpred_facts), 1, mpred_pfc, mpred_pfc).
index((mpred_facts), 2, mpred_pfc, mpred_pfc).
index((mpred_facts), 3, mpred_pfc, mpred_pfc).
index((mpred_facts_and_universe), 1, mpred_pfc, mpred_pfc).
index((mpred_facts_only), 1, mpred_pfc, mpred_pfc).
index((mpred_file_expansion_0), 2, mpred_pfc, mpred_pfc).
index((mpred_freeLastArg), 2, mpred_pfc, mpred_pfc).
index((mpred_fwd), 1, mpred_pfc, mpred_pfc).
index((mpred_fwd), 2, mpred_pfc, mpred_pfc).
index((mpred_fwd1), 2, mpred_pfc, mpred_pfc).
index((mpred_fwd2), 2, mpred_pfc, mpred_pfc).
index((mpred_get_support), 2, mpred_pfc, mpred_pfc).
index((mpred_get_support_neg), 2, mpred_pfc, mpred_pfc).
index((mpred_get_support_one), 2, mpred_pfc, mpred_pfc).
index((mpred_get_support_precanonical), 2, mpred_pfc, mpred_pfc).
index((mpred_get_support_precanonical_plus_more), 2, mpred_pfc, mpred_pfc).
index((mpred_get_support_via_clause_db), 2, mpred_pfc, mpred_pfc).
index((mpred_get_support_via_sentence), 2, mpred_pfc, mpred_pfc).
index((mpred_get_trigger_quick), 1, mpred_pfc, mpred_pfc).
index((mpred_had_support), 2, mpred_pfc, mpred_pfc).
index((mpred_halt), 0, mpred_pfc, mpred_pfc).
index((mpred_halt), 1, mpred_pfc, mpred_pfc).
index((mpred_halt), 2, mpred_pfc, mpred_pfc).
index((mpred_hide_msg), 1, mpred_pfc, mpred_pfc).
index((mpred_ignored), 1, mpred_pfc, mpred_pfc).
index((mpred_init_i), 2, mpred_pfc, mpred_pfc).
index((mpred_is_builtin), 1, mpred_pfc, mpred_pfc).
index((mpred_is_info), 1, mpred_pfc, mpred_pfc).
index((mpred_is_silient), 0, mpred_pfc, mpred_pfc).
index((mpred_is_taut), 1, mpred_pfc, mpred_pfc).
index((mpred_is_tautology), 1, mpred_pfc, mpred_pfc).
index((mpred_is_tracing_exec), 0, mpred_pfc, mpred_pfc).
index((mpred_literal), 1, mpred_pfc, mpred_pfc).
index((mpred_literal_nv), 1, mpred_pfc, mpred_pfc).
index((mpred_maptree), 2, mpred_pfc, mpred_pfc).
index((mpred_maptree), 3, mpred_pfc, mpred_pfc).
index((mpred_mark_as), 4, mpred_pfc, mpred_pfc).
index((mpred_mark_fa_as), 6, mpred_pfc, mpred_pfc).
index((mpred_mpred_file), 0, mpred_pfc, mpred_pfc).
index((mpred_negated_literal), 1, mpred_pfc, mpred_pfc).
index((mpred_negated_literal), 2, mpred_pfc, mpred_pfc).
index((mpred_negation), 2, mpred_pfc, mpred_pfc).
index((mpred_negation_w_neg), 2, mpred_pfc, mpred_pfc).
index((mpred_nf), 2, mpred_pfc, mpred_pfc).
index((mpred_nf1), 2, mpred_pfc, mpred_pfc).
index((mpred_nf1_negation), 2, mpred_pfc, mpred_pfc).
index((mpred_nf_negation), 2, mpred_pfc, mpred_pfc).
index((mpred_nf_negations), 2, mpred_pfc, mpred_pfc).
index((mpred_no_chaining), 1, mpred_pfc, mpred_pfc).
index((mpred_no_spy), 0, mpred_pfc, mpred_pfc).
index((mpred_no_spy), 1, mpred_pfc, mpred_pfc).
index((mpred_no_spy), 3, mpred_pfc, mpred_pfc).
index((mpred_no_spy_all), 0, mpred_pfc, mpred_pfc).
index((mpred_no_trace), 0, mpred_pfc, mpred_pfc).
index((mpred_no_trace_all), 0, mpred_pfc, mpred_pfc).
index((mpred_no_warnings), 0, mpred_pfc, mpred_pfc).
index((mpred_no_watch), 0, mpred_pfc, mpred_pfc).
index((mpred_non_neg_literal), 1, mpred_pfc, mpred_pfc).
index((mpred_pbody), 5, mpred_pfc, mpred_pfc).
index((mpred_pbody_f), 5, mpred_pfc, mpred_pfc).
index((mpred_positive_literal), 1, mpred_pfc, mpred_pfc).
index((mpred_post), 2, mpred_pfc, mpred_pfc).
index((mpred_post1), 2, mpred_pfc, mpred_pfc).
index((mpred_post1_sp_0), 2, mpred_pfc, mpred_pfc).
index((mpred_post1_sp_1), 2, mpred_pfc, mpred_pfc).
index((mpred_post_sp), 2, mpred_pfc, mpred_pfc).
index((mpred_post_sp_zzz), 2, mpred_pfc, mpred_pfc).
index((mpred_post_sp_zzzz), 2, mpred_pfc, mpred_pfc).
index((mpred_prove_neg), 1, mpred_pfc, mpred_pfc).
index((pfc_provide_storage_op), 2, mpred_pfc, mpred_pfc).
index((mpred_rem), 1, mpred_pfc, mpred_pfc).
index((mpred_rem1), 1, mpred_pfc, mpred_pfc).
index((mpred_rem1), 2, mpred_pfc, mpred_pfc).
index((mpred_rem2), 1, mpred_pfc, mpred_pfc).
index((mpred_rem2a), 1, mpred_pfc, mpred_pfc).
index((mpred_rem2a), 2, mpred_pfc, mpred_pfc).
index((mpred_rem_actiontrace), 2, mpred_pfc, mpred_pfc).
index((mpred_rem_support), 3, mpred_pfc, mpred_pfc).
index((mpred_remove3), 1, mpred_pfc, mpred_pfc).
index((mpred_remove_old_version), 1, mpred_pfc, mpred_pfc).
index((mpred_remove_supports_f_l), 2, mpred_pfc, mpred_pfc).
index((mpred_remove_supports_quietly), 1, mpred_pfc, mpred_pfc).
index((mpred_reset), 0, mpred_pfc, mpred_pfc).
index((mpred_retract_db_type), 1, mpred_pfc, mpred_pfc).
index((mpred_retract_db_type), 2, mpred_pfc, mpred_pfc).
index((mpred_retract_or_warn_i), 1, mpred_pfc, mpred_pfc).
index((mpred_retract_support_relations), 2, mpred_pfc, mpred_pfc).
index((mpred_rewrap_h), 2, mpred_pfc, mpred_pfc).
index((mpred_rule_hb), 3, mpred_pfc, mpred_pfc).
index((mpred_rule_hb_0), 3, mpred_pfc, mpred_pfc).
index((mpred_run), 0, mpred_pfc, mpred_pfc).
index((mpred_run0), 0, mpred_pfc, mpred_pfc).
index((mpred_run_maybe), 0, mpred_pfc, mpred_pfc).
index((mpred_scan_tms), 1, mpred_pfc, mpred_pfc).
index((mpred_slow_search), 0, mpred_pfc, mpred_pfc).
index((mpred_is_spying), 2, mpred_pfc, mpred_pfc).
index((mpred_spy), 1, mpred_pfc, mpred_pfc).
index((mpred_spy), 2, mpred_pfc, mpred_pfc).
index((mpred_spy), 3, mpred_pfc, mpred_pfc).
index((mpred_spy1), 3, mpred_pfc, mpred_pfc).
index((mpred_spy_all), 0, mpred_pfc, mpred_pfc).
index((mpred_step), 0, mpred_pfc, mpred_pfc).
index((mpred_step0), 0, mpred_pfc, mpred_pfc).
index((mpred_test), 1, mpred_pfc, mpred_pfc).
index((mpred_tms_supported), 2, mpred_pfc, mpred_pfc).
index((mpred_tms_supported), 3, mpred_pfc, mpred_pfc).
index((mpred_tms_supported0), 3, mpred_pfc, mpred_pfc).
index((mpred_trace), 0, mpred_pfc, mpred_pfc).
index((mpred_trace), 1, mpred_pfc, mpred_pfc).
index((mpred_trace), 2, mpred_pfc, mpred_pfc).
index((mpred_trace_add), 2, mpred_pfc, mpred_pfc).
index((mpred_trace_addPrint), 2, mpred_pfc, mpred_pfc).
index((mpred_trace_addPrint_0), 2, mpred_pfc, mpred_pfc).
index((mpred_trace_exec), 0, mpred_pfc, mpred_pfc).
index((mpred_notrace_exec), 0, mpred_pfc, mpred_pfc).
index((mpred_trace_break), 2, mpred_pfc, mpred_pfc).
index((mpred_trace_msg), 1, mpred_pfc, mpred_pfc).
index((mpred_trace_msg), 2, mpred_pfc, mpred_pfc).
index((mpred_trace_rem), 2, mpred_pfc, mpred_pfc).
index((mpred_is_tracing), 1, mpred_pfc, mpred_pfc).
index((mpred_undo), 2, mpred_pfc, mpred_pfc).
index((mpred_undo_e), 2, mpred_pfc, mpred_pfc).
index((mpred_undo_u), 2, mpred_pfc, mpred_pfc).
index((mpred_unfwc), 1, mpred_pfc, mpred_pfc).
index((mpred_unfwc1), 1, mpred_pfc, mpred_pfc).
index((mpred_unfwc_check_triggers), 2, mpred_pfc, mpred_pfc).
index((mpred_union), 3, mpred_pfc, mpred_pfc).
index((mpred_unique_i), 1, mpred_pfc, mpred_pfc).
index((mpred_unique_u), 1, mpred_pfc, mpred_pfc).
index((mpred_untrace), 0, mpred_pfc, mpred_pfc).
index((mpred_untrace), 1, mpred_pfc, mpred_pfc).
index((mpred_update_literal), 4, mpred_pfc, mpred_pfc).
index((mpred_user_fact), 1, mpred_pfc, mpred_pfc).
index((mpred_warn), 0, mpred_pfc, mpred_pfc).
index((mpred_warn), 1, mpred_pfc, mpred_pfc).
index((mpred_warn), 2, mpred_pfc, mpred_pfc).
index((mpred_warnings), 0, mpred_pfc, mpred_pfc).
index((mpred_warnings), 1, mpred_pfc, mpred_pfc).
index((mpred_watch), 0, mpred_pfc, mpred_pfc).
index((mpred_wff), 3, mpred_pfc, mpred_pfc).
index((mpred_wfflist), 2, mpred_pfc, mpred_pfc).
index((no_side_effects), 1, mpred_pfc, mpred_pfc).
index((nompred_warn), 0, mpred_pfc, mpred_pfc).
index((nonfact_metawrapper), 1, mpred_pfc, mpred_pfc).
index((not_cond), 2, mpred_pfc, mpred_pfc).
index((pfcBC_Cache), 1, mpred_pfc, mpred_pfc).
index((pfcBC_NoFacts), 1, mpred_pfc, mpred_pfc).
index((pfcBC_NoFacts_TRY), 1, mpred_pfc, mpred_pfc).
index((pfcVerifyMissing), 3, mpred_pfc, mpred_pfc).
index((pfcVersion), 1, mpred_pfc, mpred_pfc).
index((pfcl_do), 1, mpred_pfc, mpred_pfc).
index((physical_side_effect), 1, mpred_pfc, mpred_pfc).
index((pred_all), 1, mpred_pfc, mpred_pfc).
index((pred_head), 2, mpred_pfc, mpred_pfc).
index((pred_head_all), 1, mpred_pfc, mpred_pfc).
index((pred_r0), 1, mpred_pfc, mpred_pfc).
index((pred_t0), 1, mpred_pfc, mpred_pfc).
index((pred_u0), 1, mpred_pfc, mpred_pfc).
index((pred_u1), 1, mpred_pfc, mpred_pfc).
index((pred_u2), 1, mpred_pfc, mpred_pfc).
index((process_rule), 3, mpred_pfc, mpred_pfc).
index((record_se), 0, mpred_pfc, mpred_pfc).
index((reduce_clause_from_fwd), 2, mpred_pfc, mpred_pfc).
index((rem_list), 1, mpred_pfc, mpred_pfc).
index((remove_if_unsupported), 2, mpred_pfc, mpred_pfc).
index((remove_if_unsupported_verbose), 3, mpred_pfc, mpred_pfc).
index((remove_selection), 2, mpred_pfc, mpred_pfc).
index((repropagate), 1, mpred_pfc, mpred_pfc).
index((repropagate_0), 1, mpred_pfc, mpred_pfc).
index((repropagate_1), 1, mpred_pfc, mpred_pfc).
index((repropagate_meta_wrapper_rule), 1, mpred_pfc, mpred_pfc).
index((rescan_pfc), 0, mpred_pfc, mpred_pfc).
index((retract_eq_quitely), 1, mpred_pfc, mpred_pfc).
index((retract_eq_quitely_f), 1, mpred_pfc, mpred_pfc).
index((retract_i), 1, mpred_pfc, mpred_pfc).
index((retract_t), 1, mpred_pfc, mpred_pfc).
index((retract_u), 1, mpred_pfc, mpred_pfc).
index((retractall_i), 1, mpred_pfc, mpred_pfc).
index((retractall_u), 1, mpred_pfc, mpred_pfc).
index((rewritten_metawrapper), 1, mpred_pfc, mpred_pfc).
index((ruleBackward), 2, mpred_pfc, mpred_pfc).
index((ruleBackward0), 2, mpred_pfc, mpred_pfc).
index((select_next_fact), 2, mpred_pfc, mpred_pfc).
index((set_prolog_stack_gb), 1, mpred_pfc, mpred_pfc).
index((should_call_for_facts), 1, mpred_pfc, mpred_pfc).
index((should_call_for_facts), 3, mpred_pfc, mpred_pfc).
index((show_if_debug), 1, mpred_pfc, mpred_pfc).
index((spft_precanonical), 3, mpred_pfc, mpred_pfc).
index((sub_term_eq), 2, mpred_pfc, mpred_pfc).
index((sub_term_v), 2, mpred_pfc, mpred_pfc).
index((support_ok_via_clause_body), 1, mpred_pfc, mpred_pfc).
index((support_ok_via_clause_body), 3, mpred_pfc, mpred_pfc).
index((supports_f_l), 2, mpred_pfc, mpred_pfc).
index((to_addable_form), 2, mpred_pfc, mpred_pfc).
index((to_addable_form_wte), 3, mpred_pfc, mpred_pfc).
index((to_predicate_isas), 2, mpred_pfc, mpred_pfc).
index((to_predicate_isas0), 2, mpred_pfc, mpred_pfc).
index((to_predicate_isas_each), 2, mpred_pfc, mpred_pfc).
index((trigger_supports_f_l), 2, mpred_pfc, mpred_pfc).
index((undoable), 1, mpred_pfc, mpred_pfc).
index((update_single_valued_arg), 2, mpred_pfc, mpred_pfc).
index((use_presently), 0, mpred_pfc, mpred_pfc).
index((user_atom), 1, mpred_pfc, mpred_pfc).
index((wac), 0, mpred_pfc, mpred_pfc).
index((wellFounded), 2, mpred_pfc, mpred_pfc).
index((with_mpred_trace_exec), 1, mpred_pfc, mpred_pfc).
index((wlmuser), 1, mpred_pfc, mpred_pfc).
index((add_mpred_prop_gleaned), 2, mpred_props, mpred_props).
index((add_mpred_prop_gleaned_4), 4, mpred_props, mpred_props).
index((assert_arity), 2, mpred_props, mpred_props).
index((bad_pred_relation_name0), 2, mpred_props, mpred_props).
index((bad_pred_relation_name1), 2, mpred_props, mpred_props).
index((decl_mpred), 1, mpred_props, mpred_props).
index((decl_mpred), 2, mpred_props, mpred_props).
index((decl_mpred), 3, mpred_props, mpred_props).
index((decl_mpred_0), 2, mpred_props, mpred_props).
index((decl_mpred_2), 2, mpred_props, mpred_props).
index((decl_mpred_4), 3, mpred_props, mpred_props).
index((decl_mpred_4), 4, mpred_props, mpred_props).
index((decl_mpred_hybrid), 1, mpred_props, mpred_props).
index((decl_mpred_hybrid), 2, mpred_props, mpred_props).
index((decl_mpred_hybrid), 3, mpred_props, mpred_props).
index((decl_mpred_hybrid), 4, mpred_props, mpred_props).
index((decl_mpred_hybrid_ilc), 4, mpred_props, mpred_props).
index((decl_mpred_hybrid_ilc_0), 4, mpred_props, mpred_props).
index((decl_mpred_mfa), 3, mpred_props, mpred_props).
index((decl_mpred_pi), 1, mpred_props, mpred_props).
index((decl_mpred_prolog), 1, mpred_props, mpred_props).
index((decl_mpred_prolog), 2, mpred_props, mpred_props).
index((decl_mpred_prolog), 3, mpred_props, mpred_props).
index((decl_mpred_prolog), 4, mpred_props, mpred_props).
index((decl_mpred_prolog_ilc), 4, mpred_props, mpred_props).
index((decl_mpred_prolog_ilc_0), 4, mpred_props, mpred_props).
index((ensure_arity), 2, mpred_props, mpred_props).
index((functor_check_univ), 3, mpred_props, mpred_props).
index((get_arity), 3, mpred_props, mpred_props).
index((get_mpred_prop), 2, mpred_props, mpred_props).
index((get_mpred_prop), 3, mpred_props, mpred_props).
index((glean_pred_props_maybe), 1, mpred_props, mpred_props).
index((glean_pred_props_maybe_some), 1, mpred_props, mpred_props).
index((good_pred_relation_name), 2, mpred_props, mpred_props).
index((listprolog), 0, mpred_props, mpred_props).
index((pred_type_test), 2, mpred_props, mpred_props).
index((pred_type_test), 3, mpred_props, mpred_props).
index((pred_type_test2), 2, mpred_props, mpred_props).
index((add_fast), 1, mpred_storage, mpred_storage).
index((call_props), 2, mpred_storage, mpred_storage).
index((clr), 1, mpred_storage, mpred_storage).
index((clr0), 1, mpred_storage, mpred_storage).
index((compound_functor), 2, mpred_storage, mpred_storage).
index((confirm_hook), 1, mpred_storage, mpred_storage).
index((database_modify_0), 2, mpred_storage, mpred_storage).
index((database_modify_assert), 2, mpred_storage, mpred_storage).
index((db_must_asserta_confirmed_sv), 3, mpred_storage, mpred_storage).
index((deduceEachArgType), 1, mpred_storage, mpred_storage).
index((deduceEachArgType), 3, mpred_storage, mpred_storage).
index((deduceEachArg_WithArgIsa), 3, mpred_storage, mpred_storage).
index((deduceEachArg_WithType), 2, mpred_storage, mpred_storage).
index((del), 1, mpred_storage, mpred_storage).
index((del0), 1, mpred_storage, mpred_storage).
index((ensure_dynamic), 1, mpred_storage, mpred_storage).
index((equals_call), 2, mpred_storage, mpred_storage).
index((fact_checked), 2, mpred_storage, mpred_storage).
index((fact_loop_checked), 2, mpred_storage, mpred_storage).
index((forall_setof), 2, mpred_storage, mpred_storage).
index((get_body_functor), 3, mpred_storage, mpred_storage).
index((get_pifunctor), 2, mpred_storage, mpred_storage).
index((get_pifunctor), 3, mpred_storage, mpred_storage).
index((get_pifunctor), 4, mpred_storage, mpred_storage).
index((hooked_asserta), 1, mpred_storage, mpred_storage).
index((hooked_assertz), 1, mpred_storage, mpred_storage).
index((hooked_retract), 1, mpred_storage, mpred_storage).
index((hooked_retractall), 1, mpred_storage, mpred_storage).
index((idel), 1, mpred_storage, mpred_storage).
index((if_main), 1, mpred_storage, mpred_storage).
index((implied_skipped), 1, mpred_storage, mpred_storage).
index((infSecondOrderCheck), 0, mpred_storage, mpred_storage).
index((infThirdOrderCheck), 0, mpred_storage, mpred_storage).
index((iprops), 2, mpred_storage, mpred_storage).
index((ireq), 1, mpred_storage, mpred_storage).
index((is_asserted), 1, mpred_storage, mpred_storage).
index((is_asserted), 2, mpred_storage, mpred_storage).
index((is_asserted), 3, mpred_storage, mpred_storage).
index((is_asserted_1), 1, mpred_storage, mpred_storage).
index((is_asserted_2), 2, mpred_storage, mpred_storage).
index((is_asserted_2a), 2, mpred_storage, mpred_storage).
index((is_asserted_3), 3, mpred_storage, mpred_storage).
index((is_asserted_3a), 3, mpred_storage, mpred_storage).
index((is_asserted_eq), 1, mpred_storage, mpred_storage).
index((is_source_proof), 1, mpred_storage, mpred_storage).
index((is_static_pred), 1, mpred_storage, mpred_storage).
index((make_body_clause), 3, mpred_storage, mpred_storage).
index((may_storage_op), 2, mpred_storage, mpred_storage).
index((mdel), 1, mpred_storage, mpred_storage).
index((mpred_modify), 2, mpred_storage, mpred_storage).
index((must_storage_op), 2, mpred_storage, mpred_storage).
index((nonground_throw_else_fail), 1, mpred_storage, mpred_storage).
index((not_asserted), 1, mpred_storage, mpred_storage).
index((not_variant), 2, mpred_storage, mpred_storage).
index((padd), 2, mpred_storage, mpred_storage).
index((padd), 3, mpred_storage, mpred_storage).
index((preq), 2, mpred_storage, mpred_storage).
index((prolog_modify), 2, mpred_storage, mpred_storage).
index((prolog_mpred_provide_storage_op), 2, mpred_storage, mpred_storage).
index((prolog_op), 2, mpred_storage, mpred_storage).
index((prop), 3, mpred_storage, mpred_storage).
index((prop_or), 4, mpred_storage, mpred_storage).
index((requires_storage), 2, mpred_storage, mpred_storage).
index((requires_storage), 3, mpred_storage, mpred_storage).
index((rescan_argIsa), 3, mpred_storage, mpred_storage).
index((rescan_meta_argtypes), 1, mpred_storage, mpred_storage).
index((retract_all), 1, mpred_storage, mpred_storage).
index((side_effect_prone), 0, mpred_storage, mpred_storage).
index((singletons_throw_else_fail), 1, mpred_storage, mpred_storage).
index((skip_is_asserted_expansion), 1, mpred_storage, mpred_storage).
index((special_head), 3, mpred_storage, mpred_storage).
index((special_head0), 2, mpred_storage, mpred_storage).
index((special_wrapper_body), 2, mpred_storage, mpred_storage).
index((special_wrapper_functor), 2, mpred_storage, mpred_storage).
index((test_expand_units), 1, mpred_storage, mpred_storage).
index((upprop), 1, mpred_storage, mpred_storage).
index((upprop), 2, mpred_storage, mpred_storage).
index((use_if_modify_new), 0, mpred_storage, mpred_storage).
index((with_assert_op_override), 2, mpred_storage, mpred_storage).
index((with_fail_is_asserted), 2, mpred_storage, mpred_storage).
index((with_fallbacks), 1, mpred_storage, mpred_storage).
index((with_fallbacksg), 1, mpred_storage, mpred_storage).
index((with_kb_assertions), 2, mpred_storage, mpred_storage).
index((with_logical_functor), 3, mpred_storage, mpred_storage).
index((with_no_db_hooks), 1, mpred_storage, mpred_storage).
index((with_no_fallbacks), 1, mpred_storage, mpred_storage).
index((with_no_fallbacksg), 1, mpred_storage, mpred_storage).
index((with_no_modifications), 1, mpred_storage, mpred_storage).
index((world_clear), 1, mpred_storage, mpred_storage).
index((agenda_rescan_mpred_props), 0, mpred_stubs, mpred_stubs).
index((assert_mpred_t), 1, mpred_stubs, mpred_stubs).
index((call_for_literal), 3, mpred_stubs, mpred_stubs).
index((call_for_literal_db), 3, mpred_stubs, mpred_stubs).
index((call_for_literal_db0), 3, mpred_stubs, mpred_stubs).
index((call_for_literal_db00), 3, mpred_stubs, mpred_stubs).
index((call_for_literal_ideep_ilc), 1, mpred_stubs, mpred_stubs).
index((call_mpred_body), 2, mpred_stubs, mpred_stubs).
index((call_mpred_body_ilc), 2, mpred_stubs, mpred_stubs).
index((call_provided_mpred_storage_op), 3, mpred_stubs, mpred_stubs).
index((call_rule_db), 3, mpred_stubs, mpred_stubs).
index((call_wdmsg), 2, mpred_stubs, mpred_stubs).
index((call_wdmsg), 4, mpred_stubs, mpred_stubs).
index((constrain_args), 1, mpred_stubs, mpred_stubs).
index((constrain_args), 2, mpred_stubs, mpred_stubs).
index((create_stub_body), 2, mpred_stubs, mpred_stubs).
index((create_stub_body), 3, mpred_stubs, mpred_stubs).
index((cwdl), 2, mpred_stubs, mpred_stubs).
index((ensure_universal_stub), 1, mpred_stubs, mpred_stubs).
index((ensure_universal_stub4), 4, mpred_stubs, mpred_stubs).
index((ensure_universal_stub5), 5, mpred_stubs, mpred_stubs).
index((ensure_universal_stub_plus_2), 2, mpred_stubs, mpred_stubs).
index((ensure_universal_stub_plus_minus_2), 2, mpred_stubs, mpred_stubs).
index((ensure_universal_stub_plus_minus_2_HIDE), 2, mpred_stubs, mpred_stubs).
index((erase_mpred_storage_op), 1, mpred_stubs, mpred_stubs).
index((first_mpred_props), 1, mpred_stubs, mpred_stubs).
index((get_cc), 2, mpred_stubs, mpred_stubs).
index((has_storage_stub), 1, mpred_stubs, mpred_stubs).
index((hybrid_tPredStubImpl), 1, mpred_stubs, mpred_stubs).
index((is_asserted_mpred_t), 1, mpred_stubs, mpred_stubs).
index((is_call_op), 1, mpred_stubs, mpred_stubs).
index((is_mpred_change_op), 1, mpred_stubs, mpred_stubs).
index((is_mpred_op), 1, mpred_stubs, mpred_stubs).
index((is_non_call_op), 1, mpred_stubs, mpred_stubs).
index((is_proc), 1, mpred_stubs, mpred_stubs).
index((is_same_clauses), 2, mpred_stubs, mpred_stubs).
index((is_same_clauses), 3, mpred_stubs, mpred_stubs).
index((is_tCol), 1, mpred_stubs, mpred_stubs).
index((last_arg_ground), 1, mpred_stubs, mpred_stubs).
index((last_arg_ground), 3, mpred_stubs, mpred_stubs).
index((make_builtin), 1, mpred_stubs, mpred_stubs).
index((maybe_storage_stub), 2, mpred_stubs, mpred_stubs).
index((missing_stub), 1, mpred_stubs, mpred_stubs).
index((mpred_missing_stubs), 2, mpred_stubs, mpred_stubs).
index((mpred_prop_ordered), 2, mpred_stubs, mpred_stubs).
index((mpred_t_call_op), 2, mpred_stubs, mpred_stubs).
index((mpred_t_mpred_storage_clauses_facts), 3, mpred_stubs, mpred_stubs).
index((mpred_t_storage_op), 2, mpred_stubs, mpred_stubs).
index((mud_call_store_op), 2, mpred_stubs, mpred_stubs).
index((mustIsa), 2, mpred_stubs, mpred_stubs).
index((must_have_storage_stub), 1, mpred_stubs, mpred_stubs).
index((must_op), 2, mpred_stubs, mpred_stubs).
index((must_same_clauses), 2, mpred_stubs, mpred_stubs).
index((no_rescans), 0, mpred_stubs, mpred_stubs).
index((out_of_mpred_t), 1, mpred_stubs, mpred_stubs).
index((provide_clauses_list), 2, mpred_stubs, mpred_stubs).
index((really_add_mpred_storage_op), 1, mpred_stubs, mpred_stubs).
index((registerCycPredPlus2), 1, mpred_stubs, mpred_stubs).
index((registerCycPredPlus2_3), 3, mpred_stubs, mpred_stubs).
index((registerCycPredPlus2_3), 4, mpred_stubs, mpred_stubs).
index((renumbervarZ), 2, mpred_stubs, mpred_stubs).
index((rescan_missing_stubs), 0, mpred_stubs, mpred_stubs).
index((rescan_missing_stubs_ilc), 0, mpred_stubs, mpred_stubs).
index((rescan_mpred_props_ilc), 0, mpred_stubs, mpred_stubs).
index((scan_missing_stubs), 1, mpred_stubs, mpred_stubs).
index((test_call_cut), 0, mpred_stubs, mpred_stubs).
index((wff_check_failed), 3, mpred_stubs, mpred_stubs).
index((wff_check_mpred_t_throw), 1, mpred_stubs, mpred_stubs).
index((any_to_number), 2, mpred_type_args, mpred_type_args).
index((any_to_relation), 2, mpred_type_args, mpred_type_args).
index((any_to_value), 2, mpred_type_args, mpred_type_args).
index((argIsa_call_0), 3, mpred_type_args, mpred_type_args).
index((argIsa_call_3), 2, mpred_type_args, mpred_type_args).
index((argIsa_call_6), 3, mpred_type_args, mpred_type_args).
index((argIsa_call_7), 3, mpred_type_args, mpred_type_args).
index((argIsa_call_9), 3, mpred_type_args, mpred_type_args).
index((argIsa_ft), 3, mpred_type_args, mpred_type_args).
index((argIsa_known), 3, mpred_type_args, mpred_type_args).
index((argIsa_op_call), 4, mpred_type_args, mpred_type_args).
index((argisa_nodebug), 0, mpred_type_args, mpred_type_args).
index((as_one_of), 2, mpred_type_args, mpred_type_args).
index((assert_argIsa), 3, mpred_type_args, mpred_type_args).
index((assert_predArgTypes), 1, mpred_type_args, mpred_type_args).
index((assert_predArgTypes_fa), 2, mpred_type_args, mpred_type_args).
index((assert_predArgTypes_from_left), 3, mpred_type_args, mpred_type_args).
index((assert_predArgTypes_from_right), 3, mpred_type_args, mpred_type_args).
index((assert_predArgTypes_l), 3, mpred_type_args, mpred_type_args).
index((asserted_argIsa_known), 3, mpred_type_args, mpred_type_args).
index((atom_to_value), 2, mpred_type_args, mpred_type_args).
index((checkAnyType), 4, mpred_type_args, mpred_type_args).
index((coerce), 4, mpred_type_args, mpred_type_args).
index((correctAnyType), 4, mpred_type_args, mpred_type_args).
index((correctAnyTypeOrFail), 4, mpred_type_args, mpred_type_args).
index((correctArgsIsa), 2, mpred_type_args, mpred_type_args).
index((correctArgsIsa), 3, mpred_type_args, mpred_type_args).
index((correctArgsIsa), 4, mpred_type_args, mpred_type_args).
index((correctArgsIsa0), 3, mpred_type_args, mpred_type_args).
index((correctArgsIsa00), 3, mpred_type_args, mpred_type_args).
index((correctFormatType), 4, mpred_type_args, mpred_type_args).
index((correctType), 4, mpred_type_args, mpred_type_args).
index((correctType0), 4, mpred_type_args, mpred_type_args).
index((correctTypeArg), 4, mpred_type_args, mpred_type_args).
index((correctType_gripe), 4, mpred_type_args, mpred_type_args).
index((deduced_is_tCol), 1, mpred_type_args, mpred_type_args).
index((discoverAndCorrectArgsIsa), 5, mpred_type_args, mpred_type_args).
index((discoverAndCorrectArgsIsa_from_left), 5, mpred_type_args, mpred_type_args).
index((discoverAndCorrectArgsIsa_from_right), 5, mpred_type_args, mpred_type_args).
index((evaluatableArg), 2, mpred_type_args, mpred_type_args).
index((evaluatableFunctor), 1, mpred_type_args, mpred_type_args).
index((grab_argsIsa), 2, mpred_type_args, mpred_type_args).
index((grab_argsIsa_6), 1, mpred_type_args, mpred_type_args).
index((is_boolean), 1, mpred_type_args, mpred_type_args).
index((is_declarations), 1, mpred_type_args, mpred_type_args).
index((is_ephemeral), 1, mpred_type_args, mpred_type_args).
index((is_ftText), 1, mpred_type_args, mpred_type_args).
index((is_id), 1, mpred_type_args, mpred_type_args).
index((is_list_of), 2, mpred_type_args, mpred_type_args).
index((is_renamed_to), 2, mpred_type_args, mpred_type_args).
index((is_rest), 1, mpred_type_args, mpred_type_args).
index((is_rest_of), 2, mpred_type_args, mpred_type_args).
index((is_spec), 1, mpred_type_args, mpred_type_args).
index((is_valuespec), 1, mpred_type_args, mpred_type_args).
index((list_to_callform), 3, mpred_type_args, mpred_type_args).
index((maybe_argtypes), 1, mpred_type_args, mpred_type_args).
index((mpred_arity_pred), 1, mpred_type_args, mpred_type_args).
index((mpred_full_arity), 2, mpred_type_args, mpred_type_args).
index((must_equals), 2, mpred_type_args, mpred_type_args).
index((must_equals_correct), 3, mpred_type_args, mpred_type_args).
index((pl_arg_type), 2, mpred_type_args, mpred_type_args).
index((roll_dice), 4, mpred_type_args, mpred_type_args).
index((term_is_ft), 2, mpred_type_args, mpred_type_args).
index((term_is_ft_how), 2, mpred_type_args, mpred_type_args).
index((to_format_type), 2, mpred_type_args, mpred_type_args).
index((trans_subft), 2, mpred_type_args, mpred_type_args).
index((add_iza), 2, mpred_type_constraints, mpred_type_constraints).
index((arg_to_var), 3, mpred_type_constraints, mpred_type_constraints).
index((attempt_attribute_args), 3, mpred_type_constraints, mpred_type_constraints).
index((attempt_attribute_args), 5, mpred_type_constraints, mpred_type_constraints).
index((attempt_attribute_one_arg), 4, mpred_type_constraints, mpred_type_constraints).
index((attribs_to_atoms), 2, mpred_type_constraints, mpred_type_constraints).
index((attribs_to_atoms0), 2, mpred_type_constraints, mpred_type_constraints).
index((cmp_memberchk), 2, mpred_type_constraints, mpred_type_constraints).
index((cmp_memberchk0), 2, mpred_type_constraints, mpred_type_constraints).
index((comp_type), 3, mpred_type_constraints, mpred_type_constraints).
index((domain), 2, mpred_type_constraints, mpred_type_constraints).
index((extend_dom), 2, mpred_type_constraints, mpred_type_constraints).
index((extend_domain), 2, mpred_type_constraints, mpred_type_constraints).
index((init_dom), 2, mpred_type_constraints, mpred_type_constraints).
index((inst_isac), 2, mpred_type_constraints, mpred_type_constraints).
index((isa_pred_l), 3, mpred_type_constraints, mpred_type_constraints).
index((isa_pred_l), 4, mpred_type_constraints, mpred_type_constraints).
index((isac), 2, mpred_type_constraints, mpred_type_constraints).
index((isac_chk), 2, mpred_type_constraints, mpred_type_constraints).
index((isac_gen), 2, mpred_type_constraints, mpred_type_constraints).
index((iza_to_isa), 2, mpred_type_constraints, mpred_type_constraints).
index((map_subterms), 3, mpred_type_constraints, mpred_type_constraints).
index((max_isa), 3, mpred_type_constraints, mpred_type_constraints).
index((max_isa_l), 2, mpred_type_constraints, mpred_type_constraints).
index((mdif), 2, mpred_type_constraints, mpred_type_constraints).
index((min_isa), 3, mpred_type_constraints, mpred_type_constraints).
index((min_isa_l), 2, mpred_type_constraints, mpred_type_constraints).
index((promp_yn), 2, mpred_type_constraints, mpred_type_constraints).
index((same), 2, mpred_type_constraints, mpred_type_constraints).
index((same_arg), 3, mpred_type_constraints, mpred_type_constraints).
index((samef), 2, mpred_type_constraints, mpred_type_constraints).
index((to_functor), 2, mpred_type_constraints, mpred_type_constraints).
index((type_size), 2, mpred_type_constraints, mpred_type_constraints).
index((a), 2, mpred_type_isa, mpred_type_isa).
index((assert_compound_isa), 3, mpred_type_isa, mpred_type_isa).
index((assert_hasInstance), 2, mpred_type_isa, mpred_type_isa).
index((assert_isa), 2, mpred_type_isa, mpred_type_isa).
index((assert_isa_hooked), 2, mpred_type_isa, mpred_type_isa).
index((assert_isa_hooked_after), 2, mpred_type_isa, mpred_type_isa).
index((assert_isa_i), 2, mpred_type_isa, mpred_type_isa).
index((assert_isa_ilc), 2, mpred_type_isa, mpred_type_isa).
index((assert_isa_ilc_unchecked), 2, mpred_type_isa, mpred_type_isa).
index((assert_isa_reversed), 2, mpred_type_isa, mpred_type_isa).
index((assert_isa_safe), 2, mpred_type_isa, mpred_type_isa).
index((assert_p_safe), 3, mpred_type_isa, mpred_type_isa).
index((assert_subclass), 2, mpred_type_isa, mpred_type_isa).
index((assert_subclass_safe), 2, mpred_type_isa, mpred_type_isa).
index((asserted_subclass), 2, mpred_type_isa, mpred_type_isa).
index((atom_prefix_other), 3, mpred_type_isa, mpred_type_isa).
index((atom_type_prefix_other), 4, mpred_type_isa, mpred_type_isa).
index((cached_isa), 2, mpred_type_isa, mpred_type_isa).
index((callOr), 3, mpred_type_isa, mpred_type_isa).
index((chk_ft), 1, mpred_type_isa, mpred_type_isa).
index((compound_isa), 3, mpred_type_isa, mpred_type_isa).
index((decl_type), 1, mpred_type_isa, mpred_type_isa).
index((decl_type_safe), 1, mpred_type_isa, mpred_type_isa).
index((decl_type_unsafe), 1, mpred_type_isa, mpred_type_isa).
index((define_ft), 1, mpred_type_isa, mpred_type_isa).
index((define_ft_0), 1, mpred_type_isa, mpred_type_isa).
index((disjointWith0), 2, mpred_type_isa, mpred_type_isa).
index((disjointWithT), 2, mpred_type_isa, mpred_type_isa).
index((dont_call_type_arity_one), 1, mpred_type_isa, mpred_type_isa).
index((get_mpred_arg), 3, mpred_type_isa, mpred_type_isa).
index((guess_supertypes), 1, mpred_type_isa, mpred_type_isa).
index((guess_supertypes_0), 1, mpred_type_isa, mpred_type_isa).
index((guess_types), 1, mpred_type_isa, mpred_type_isa).
index((guess_types), 2, mpred_type_isa, mpred_type_isa).
index((guess_types_0), 2, mpred_type_isa, mpred_type_isa).
index((guess_typetypes), 1, mpred_type_isa, mpred_type_isa).
index((guess_typetypes_0), 1, mpred_type_isa, mpred_type_isa).
index((has_free_args), 1, mpred_type_isa, mpred_type_isa).
index((into_single_class), 2, mpred_type_isa, mpred_type_isa).
index((is_Template), 1, mpred_type_isa, mpred_type_isa).
index((is_known_false), 1, mpred_type_isa, mpred_type_isa).
index((is_known_false0), 1, mpred_type_isa, mpred_type_isa).
index((is_known_trew), 1, mpred_type_isa, mpred_type_isa).
index((is_known_true), 1, mpred_type_isa, mpred_type_isa).
index((is_never_type), 1, mpred_type_isa, mpred_type_isa).
index((is_non_skolem), 1, mpred_type_isa, mpred_type_isa).
index((is_non_unit), 1, mpred_type_isa, mpred_type_isa).
index((is_sk_functor), 1, mpred_type_isa, mpred_type_isa).
index((is_sk_unit), 1, mpred_type_isa, mpred_type_isa).
index((is_typef), 1, mpred_type_isa, mpred_type_isa).
index((isa_asserted), 2, mpred_type_isa, mpred_type_isa).
index((isa_asserted_1), 2, mpred_type_isa, mpred_type_isa).
index((isa_atom_call), 2, mpred_type_isa, mpred_type_isa).
index((isa_atom_call_ilc), 2, mpred_type_isa, mpred_type_isa).
index((isa_backchaing), 2, mpred_type_isa, mpred_type_isa).
index((isa_backchaing_0), 2, mpred_type_isa, mpred_type_isa).
index((isa_from_morphology), 2, mpred_type_isa, mpred_type_isa).
index((isa_w_type_atom), 2, mpred_type_isa, mpred_type_isa).
index((ain_guess), 1, mpred_type_isa, mpred_type_isa).
index((mpred_types_loaded), 0, mpred_type_isa, mpred_type_isa).
index((never_type_f), 1, mpred_type_isa, mpred_type_isa).
index((never_type_why), 2, mpred_type_isa, mpred_type_isa).
index((noncol_type), 1, mpred_type_isa, mpred_type_isa).
index((not_ft), 1, mpred_type_isa, mpred_type_isa).
index((not_ft_quick), 1, mpred_type_isa, mpred_type_isa).
index((not_mud_isa), 2, mpred_type_isa, mpred_type_isa).
index((not_mud_isa), 3, mpred_type_isa, mpred_type_isa).
index((not_mud_isa0), 2, mpred_type_isa, mpred_type_isa).
index((onLoadPfcRule), 1, mpred_type_isa, mpred_type_isa).
index((pfcNeverTrue), 1, mpred_type_isa, mpred_type_isa).
index((tCol_gen), 1, mpred_type_isa, mpred_type_isa).
index((to_isa_out), 3, mpred_type_isa, mpred_type_isa).
index((transitive_P), 4, mpred_type_isa, mpred_type_isa).
index((transitive_P_l_r), 4, mpred_type_isa, mpred_type_isa).
index((transitive_P_r_l), 4, mpred_type_isa, mpred_type_isa).
index((transitive_subclass_or_same), 2, mpred_type_isa, mpred_type_isa).
index((type_deduced), 2, mpred_type_isa, mpred_type_isa).
index((type_isa), 2, mpred_type_isa, mpred_type_isa).
index((was_isa), 3, mpred_type_isa, mpred_type_isa).
index((was_isa0), 3, mpred_type_isa, mpred_type_isa).
index((isa_asserted_0), 2, mpred_type_isa, mpred_type_isa).
index((new_was_isa), 0, mpred_type_isa, mpred_type_isa).
index((type_prefix), 2, mpred_type_isa, mpred_type_isa).
index((type_suffix), 2, mpred_type_isa, mpred_type_isa).
index((convertOneSpawnArg), 4, mpred_type_naming, mpred_type_naming).
index((convertSpawnArgs), 4, mpred_type_naming, mpred_type_naming).
index((convertToInstance), 3, mpred_type_naming, mpred_type_naming).
index((createByNameMangle), 3, mpred_type_naming, mpred_type_naming).
index((createByNameMangle0), 3, mpred_type_naming, mpred_type_naming).
index((createByNameMangle_compound), 3, mpred_type_naming, mpred_type_naming).
index((create_from_type), 3, mpred_type_naming, mpred_type_naming).
index((create_meta), 4, mpred_type_naming, mpred_type_naming).
index((get_source_suffix), 1, mpred_type_naming, mpred_type_naming).
index((i_name), 2, mpred_type_naming, mpred_type_naming).
index((i_name), 3, mpred_type_naming, mpred_type_naming).
index((i_name_lc), 2, mpred_type_naming, mpred_type_naming).
index((modality), 3, mpred_type_naming, mpred_type_naming).
index((onSpawn), 1, mpred_type_naming, mpred_type_naming).
index((onSpawn_0), 2, mpred_type_naming, mpred_type_naming).
index((onSpawn_f_args), 3, mpred_type_naming, mpred_type_naming).
index((spawnOneSpawnArg), 4, mpred_type_naming, mpred_type_naming).
index((split_name_type), 3, mpred_type_naming, mpred_type_naming).
index((split_name_type_0), 3, mpred_type_naming, mpred_type_naming).
index((toCamelAtom0), 2, mpred_type_naming, mpred_type_naming).
index((toUpperCamelcase), 2, mpred_type_naming, mpred_type_naming).
index((to_atomic_name), 3, mpred_type_naming, mpred_type_naming).
index((to_iname), 2, mpred_type_naming, mpred_type_naming).
index((to_prefixed), 3, mpred_type_naming, mpred_type_naming).
index((typename_to_iname0), 3, mpred_type_naming, mpred_type_naming).
index((head_singletons), 2, mpred_type_wff, mpred_type_wff).
index((head_singles0), 2, mpred_type_wff, mpred_type_wff).
index((head_singles01), 2, mpred_type_wff, mpred_type_wff).
index((append_termlist), 3, mpred_type_wff, mpred_type_wff).
index((call_last_is_var), 1, mpred_type_wff, mpred_type_wff).
index((contains_negs), 1, mpred_type_wff, mpred_type_wff).
index((contains_no_negs), 1, mpred_type_wff, mpred_type_wff).
index((contains_t_var), 3, mpred_type_wff, mpred_type_wff).
index((contains_type_lits), 3, mpred_type_wff, mpred_type_wff).
index((contains_var_lits), 3, mpred_type_wff, mpred_type_wff).
index((correct_negations), 3, mpred_type_wff, mpred_type_wff).
index((current_hilog), 1, mpred_type_wff, mpred_type_wff).
index((defunctionalize), 2, mpred_type_wff, mpred_type_wff).
index((defunctionalize), 3, mpred_type_wff, mpred_type_wff).
index((ensure_quantifiers), 2, mpred_type_wff, mpred_type_wff).
index((function_to_predicate), 3, mpred_type_wff, mpred_type_wff).
index((get_isa), 3, mpred_type_wff, mpred_type_wff).
index((get_isa0), 3, mpred_type_wff, mpred_type_wff).
index((get_kv), 3, mpred_type_wff, mpred_type_wff).
index((get_pred), 2, mpred_type_wff, mpred_type_wff).
index((hilog_functor), 1, mpred_type_wff, mpred_type_wff).
index((isBodyConnective), 1, mpred_type_wff, mpred_type_wff).
index((isEntityFunction), 3, mpred_type_wff, mpred_type_wff).
index((isEntitySlot), 1, mpred_type_wff, mpred_type_wff).
index((isEntityref), 2, mpred_type_wff, mpred_type_wff).
index((isHiddenSlot), 1, mpred_type_wff, mpred_type_wff).
index((isLiteralTerm), 1, mpred_type_wff, mpred_type_wff).
index((isLiteralTerm_util), 1, mpred_type_wff, mpred_type_wff).
index((isNonCompound), 1, mpred_type_wff, mpred_type_wff).
index((isNonVar), 1, mpred_type_wff, mpred_type_wff).
index((isObject), 2, mpred_type_wff, mpred_type_wff).
index((isQualifiableAs), 3, mpred_type_wff, mpred_type_wff).
index((isQualifiableAsClass), 1, mpred_type_wff, mpred_type_wff).
index((isQualifiedAndKnownAs), 3, mpred_type_wff, mpred_type_wff).
index((isQualifiedAndVarAndUnifiable), 3, mpred_type_wff, mpred_type_wff).
index((isQualifiedAndVarAs), 3, mpred_type_wff, mpred_type_wff).
index((isQualifiedAs), 3, mpred_type_wff, mpred_type_wff).
index((isQualifiedAs), 4, mpred_type_wff, mpred_type_wff).
index((isSlot), 1, mpred_type_wff, mpred_type_wff).
index((isSlot), 2, mpred_type_wff, mpred_type_wff).
index((isVarObject), 1, mpred_type_wff, mpred_type_wff).
index((isVarObject), 2, mpred_type_wff, mpred_type_wff).
index((isVarProlog), 1, mpred_type_wff, mpred_type_wff).
index((is_2nd_order_holds), 1, mpred_type_wff, mpred_type_wff).
index((is_colection_name), 3, mpred_type_wff, mpred_type_wff).
index((is_ftEquality), 1, mpred_type_wff, mpred_type_wff).
index((is_function), 1, mpred_type_wff, mpred_type_wff).
index((is_function), 3, mpred_type_wff, mpred_type_wff).
index((is_gaf), 1, mpred_type_wff, mpred_type_wff).
index((is_holds_false), 1, mpred_type_wff, mpred_type_wff).
index((is_holds_false0), 1, mpred_type_wff, mpred_type_wff).
index((is_holds_true), 1, mpred_type_wff, mpred_type_wff).
index((is_holds_true0), 1, mpred_type_wff, mpred_type_wff).
index((is_holds_true_not_hilog), 1, mpred_type_wff, mpred_type_wff).
index((is_kif_rule), 1, mpred_type_wff, mpred_type_wff).
index((is_log_op), 1, mpred_type_wff, mpred_type_wff).
index((is_log_sent), 1, mpred_type_wff, mpred_type_wff).
index((is_logical_functor), 1, mpred_type_wff, mpred_type_wff).
index((is_logical_functor0), 1, mpred_type_wff, mpred_type_wff).
index((is_modal), 2, mpred_type_wff, mpred_type_wff).
index((is_neg), 1, mpred_type_wff, mpred_type_wff).
index((is_pos), 1, mpred_type_wff, mpred_type_wff).
index((is_sentence_functor), 1, mpred_type_wff, mpred_type_wff).
index((is_svo_functor), 1, mpred_type_wff, mpred_type_wff).
index((kb_nlit), 2, mpred_type_wff, mpred_type_wff).
index((lastImproperMember), 3, mpred_type_wff, mpred_type_wff).
index((leave_as_is), 1, mpred_type_wff, mpred_type_wff).
index((leave_as_is_db), 1, mpred_type_wff, mpred_type_wff).
index((leave_as_is_functor), 1, mpred_type_wff, mpred_type_wff).
index((logical_functor_ft), 1, mpred_type_wff, mpred_type_wff).
index((non_assertable), 2, mpred_type_wff, mpred_type_wff).
index((non_compound), 1, mpred_type_wff, mpred_type_wff).
index((not_log_op), 1, mpred_type_wff, mpred_type_wff).
index((prequent), 1, mpred_type_wff, mpred_type_wff).
index((put_singles), 4, mpred_type_wff, mpred_type_wff).
index((set_is_lit), 1, mpred_type_wff, mpred_type_wff).
index((subst_except), 4, mpred_type_wff, mpred_type_wff).
index((term_singletons), 2, mpred_type_wff, mpred_type_wff).
index((term_singletons), 3, mpred_type_wff, mpred_type_wff).
index((term_singletons), 5, mpred_type_wff, mpred_type_wff).
index((term_slots), 2, mpred_type_wff, mpred_type_wff).
index((wrap_in_neg_functor), 3, mpred_type_wff, mpred_type_wff).
index((::::), 2, baseKB, mpred_userkb).
index((<-), 2, baseKB, mpred_userkb).
index((<==>), 2, baseKB, mpred_userkb).
index((==>), 1, baseKB, mpred_userkb).
index((==>), 2, baseKB, mpred_userkb).
index((neg), 1, baseKB, mpred_userkb).
index((nesc), 1, baseKB, mpred_userkb).
index((add_args), 15, baseKB, mpred_userkb).
index((addTiny_added), 1, baseKB, mpred_userkb).
index((agent_call_command), 2, baseKB, mpred_userkb).
index((argGenl), 3, baseKB, mpred_userkb).
index((argIsa), 3, baseKB, mpred_userkb).
index((argQuotedIsa), 3, baseKB, mpred_userkb).
index((argsQuoted), 1, baseKB, mpred_userkb).
index((arity), 2, baseKB, mpred_userkb).
index((asserted_mpred_f), 2, baseKB, mpred_userkb).
index((asserted_mpred_f), 3, baseKB, mpred_userkb).
index((asserted_mpred_f), 4, baseKB, mpred_userkb).
index((asserted_mpred_f), 5, baseKB, mpred_userkb).
index((asserted_mpred_f), 6, baseKB, mpred_userkb).
index((asserted_mpred_f), 7, baseKB, mpred_userkb).
index((asserted_mpred_t), 2, baseKB, mpred_userkb).
index((asserted_mpred_t), 3, baseKB, mpred_userkb).
index((asserted_mpred_t), 4, baseKB, mpred_userkb).
index((asserted_mpred_t), 5, baseKB, mpred_userkb).
index((asserted_mpred_t), 6, baseKB, mpred_userkb).
index((asserted_mpred_t), 7, baseKB, mpred_userkb).
index((assertion_f), 1, baseKB, mpred_userkb).
index((call_mt_t), 11, baseKB, mpred_userkb).
index((call_OnEachLoad), 1, baseKB, mpred_userkb).
index((call_which_t), 9, baseKB, mpred_userkb).
index((coerce), 3, baseKB, mpred_userkb).
index((completelyAssertedCollection), 1, baseKB, mpred_userkb).
index((conflict), 1, baseKB, mpred_userkb).
index((constrain_args_pttp), 2, baseKB, mpred_userkb).
index((contract_output_proof), 2, baseKB, mpred_userkb).
index((current_world), 1, baseKB, mpred_userkb).
index((cyc_to_plarkc), 2, baseKB, mpred_userkb).
index((cyckb_t), 3, baseKB, mpred_userkb).
index((cycPrepending), 2, baseKB, mpred_userkb).
index((decided_not_was_isa), 2, baseKB, mpred_userkb).
index((deduceFromArgTypes), 1, baseKB, mpred_userkb).
index((default_type_props), 3, baseKB, mpred_userkb).
index((defnSufficient), 2, baseKB, mpred_userkb).
index((did_learn_from_name), 1, baseKB, mpred_userkb).
index((elInverse), 2, baseKB, mpred_userkb).
index((feature_test), 0, baseKB, mpred_userkb).
index((formatted_resultIsa), 2, baseKB, mpred_userkb).
index((function_corisponding_predicate), 2, baseKB, mpred_userkb).
index((functorDeclares), 1, baseKB, mpred_userkb).
index((genls), 2, baseKB, mpred_userkb).
index((grid_key), 1, baseKB, mpred_userkb).
index((holds_f_p2), 2, baseKB, mpred_userkb).
index((if_missing), 2, baseKB, mpred_userkb).
index((is_edited_clause), 3, baseKB, mpred_userkb).
index((is_wrapper_pred), 1, baseKB, mpred_userkb).
index((isa), 2, baseKB, mpred_userkb).
index((isCycAvailable_known), 0, baseKB, mpred_userkb).
index((isCycUnavailable_known), 1, baseKB, mpred_userkb).
index((never_assert_u), 2, baseKB, mpred_userkb).
index((never_retract_u), 2, baseKB, mpred_userkb).
index((lambda), 5, baseKB, mpred_userkb).
index((localityOfObject), 2, baseKB, mpred_userkb).
index((logical_functor_pttp), 1, baseKB, mpred_userkb).
index((meta_argtypes), 1, baseKB, mpred_userkb).
index((mpred_action), 1, baseKB, mpred_userkb).
index((mpred_default), 1, baseKB, mpred_userkb).
index((mpred_do_and_undo_method), 2, baseKB, mpred_userkb).
index((mpred_f), 1, baseKB, mpred_userkb).
index((mpred_f), 2, baseKB, mpred_userkb).
index((mpred_f), 3, baseKB, mpred_userkb).
index((mpred_f), 4, baseKB, mpred_userkb).
index((mpred_f), 5, baseKB, mpred_userkb).
index((mpred_f), 6, baseKB, mpred_userkb).
index((mpred_f), 7, baseKB, mpred_userkb).
index((mpred_isa), 2, baseKB, mpred_userkb).
index((mpred_manages_unknowns), 0, baseKB, mpred_userkb).
index((mpred_mark), 4, baseKB, mpred_userkb).
index((mpred_module), 2, baseKB, mpred_userkb).
index((mpred_univ), 1, baseKB, mpred_userkb).
index((mpred_univ), 3, baseKB, mpred_userkb).
index((mudKeyword), 2, baseKB, mpred_userkb).
index((now_unused), 1, baseKB, mpred_userkb).
index((only_if_pttp), 0, baseKB, mpred_userkb).
index((pddlSomethingIsa), 2, baseKB, mpred_userkb).
index((pfcControlled), 1, baseKB, mpred_userkb).
index((pfcRHS), 1, baseKB, mpred_userkb).
index((predCanHaveSingletons), 1, baseKB, mpred_userkb).
index((prologBuiltin), 1, baseKB, mpred_userkb).
index((prologDynamic), 1, baseKB, mpred_userkb).
index((prologDynamic), 2, baseKB, mpred_userkb).
index((prologHybrid), 1, baseKB, mpred_userkb).
index((prologHybrid), 2, baseKB, mpred_userkb).
index((prologKIF), 1, baseKB, mpred_userkb).
index((prologListValued), 1, baseKB, mpred_userkb).
index((prologMacroHead), 1, baseKB, mpred_userkb).
index((prologMultiValued), 1, baseKB, mpred_userkb).
index((prologNegByFailure), 1, baseKB, mpred_userkb).
index((prologOrdered), 1, baseKB, mpred_userkb).
index((prologPTTP), 1, baseKB, mpred_userkb).
index((prologSideEffects), 1, baseKB, mpred_userkb).
index((prologSingleValued), 1, baseKB, mpred_userkb).
index((props), 2, baseKB, mpred_userkb).
index((ptReformulatorDirectivePredicate), 1, baseKB, mpred_userkb).
index((pttp1a_wid), 3, baseKB, mpred_userkb).
index((pttp_builtin), 2, baseKB, mpred_userkb).
index((pttp_nnf_pre_clean_functor), 3, baseKB, mpred_userkb).
index((quasiQuote), 1, baseKB, mpred_userkb).
index((relationMostInstance), 3, baseKB, mpred_userkb).
index((relax_term), 6, baseKB, mpred_userkb).
index((resolveConflict), 1, baseKB, mpred_userkb).
index((resolverConflict_robot), 1, baseKB, mpred_userkb).
index((resultIsa), 2, baseKB, mpred_userkb).
index((retractall_wid), 1, baseKB, mpred_userkb).
index((ruleRewrite), 2, baseKB, mpred_userkb).
index((search), 7, baseKB, mpred_userkb).
index((singleValuedInArg), 2, baseKB, mpred_userkb).
index((startup_option), 2, baseKB, mpred_userkb).
index((subFormat), 2, baseKB, mpred_userkb).
index((support_hilog), 2, baseKB, mpred_userkb).
index((t), 1, baseKB, mpred_userkb).
index((t), 10, baseKB, mpred_userkb).
index((t), 11, baseKB, mpred_userkb).
index((t), 2, baseKB, mpred_userkb).
index((t), 3, baseKB, mpred_userkb).
index((t), 4, baseKB, mpred_userkb).
index((t), 5, baseKB, mpred_userkb).
index((t), 6, baseKB, mpred_userkb).
index((t), 7, baseKB, mpred_userkb).
index((t), 8, baseKB, mpred_userkb).
index((t), 9, baseKB, mpred_userkb).
index((tCol), 1, baseKB, mpred_userkb).
index((tFarthestReachableItem), 1, baseKB, mpred_userkb).
index((tFunction), 1, baseKB, mpred_userkb).
index((tNearestReachableItem), 1, baseKB, mpred_userkb).
index((tNotForUnboundPredicates), 1, baseKB, mpred_userkb).
index((ptSymmetric), 1, baseKB, mpred_userkb).
index((tPred), 1, baseKB, mpred_userkb).
index((tPredType), 1, baseKB, mpred_userkb).
index((tRegion), 1, baseKB, mpred_userkb).
index((tRelation), 1, baseKB, mpred_userkb).
index((tried_guess_types_from_name), 1, baseKB, mpred_userkb).
index((tSet), 1, baseKB, mpred_userkb).
index((ttFormatType), 1, baseKB, mpred_userkb).
index((ttPredType), 1, baseKB, mpred_userkb).
index((ttTemporalType), 1, baseKB, mpred_userkb).
index((ttUnverifiableType), 1, baseKB, mpred_userkb).
index((type_action_info), 3, baseKB, mpred_userkb).
index((typeProps), 2, baseKB, mpred_userkb).
index((use_ideep_swi), 0, baseKB, mpred_userkb).
index((vtUnreifiableFunction), 1, baseKB, mpred_userkb).
index((was_chain_rule), 1, baseKB, mpred_userkb).
index((wid), 3, baseKB, mpred_userkb).
index((prologEquality), 1, baseKB, mpred_userkb).
index((pfcBcTrigger), 1, baseKB, mpred_userkb).
index((meta_argtypes), 1, baseKB, mpred_userkb).
index((pfcDatabaseTerm), 1, baseKB, mpred_userkb).
index((pfcControlled), 1, baseKB, mpred_userkb).
index((pfcWatched), 1, baseKB, mpred_userkb).
index((pfcMustFC), 1, baseKB, mpred_userkb).
index((predIsFlag), 1, baseKB, mpred_userkb).
index((tPred), 1, baseKB, mpred_userkb).
index((prologMultiValued), 1, baseKB, mpred_userkb).
index((prologSingleValued), 1, baseKB, mpred_userkb).
index((prologMacroHead), 1, baseKB, mpred_userkb).
index((notAssertable), 1, baseKB, mpred_userkb).
index((prologBuiltin), 1, baseKB, mpred_userkb).
index((prologDynamic), 1, baseKB, mpred_userkb).
index((prologOrdered), 1, baseKB, mpred_userkb).
index((prologNegByFailure), 1, baseKB, mpred_userkb).
index((prologPTTP), 1, baseKB, mpred_userkb).
index((prologKIF), 1, baseKB, mpred_userkb).
index((prologEquality), 1, baseKB, mpred_userkb).
index((prologPTTP), 1, baseKB, mpred_userkb).
index((prologSideEffects), 1, baseKB, mpred_userkb).
index((prologHybrid), 1, baseKB, mpred_userkb).
index((prologListValued), 1, baseKB, mpred_userkb).
