%
% This file is generated - do not edit
% bip(Name, Arity, Group, Library, Filename)
%

bip(call_goal, 3, ., game_description, '').
bip(closelogs, 0, ., logger, 'closelogs-0').
bip(compute_best_move, 2, ., compute_best_move, 'compute_best_move-2').
bip(compute_best_move, index, ., compute_best_move, '').
bip(convert_to_gdl_string, 2, ., gdl_parser, '').
bip(current_time, 1, ., time_sync, '').
bip(debug_player, index, ., debug_player, '').
bip(does, 3, ., game_description, '').
bip(external_time_to_local, 2, ., time_sync, '').
bip(game_description, index, ., game_description, '').
bip(game_play, 4, ., gameplayer, 'game_play-4').
bip(game_play_timed_part, 2, ., gameplayer, 'game_play_timed_part-2').
bip(game_rule, 4, ., game_description, '').
bip(game_start, 6, ., gameplayer, 'game_start-6').
bip(game_start_timed_part, 2, ., gameplayer, 'game_start_timed_part-2').
bip(game_stop, 3, ., gameplayer, 'game_stop-3').
bip(gameplayer, index, ., gameplayer, '').
bip(gdl_parser, index, ., gdl_parser, '').
bip(get_current_best_move, 1, ., match_info, '').
bip(get_current_state, 1, ., match_info, '').
bip(get_deadline, 1, ., time_sync, '').
bip(get_match_id, 1, ., match_info, '').
bip(get_our_role, 1, ., match_info, '').
bip(get_playclock, 1, ., match_info, '').
bip(get_rules, 1, ., game_description, '').
bip(get_startclock, 1, ., match_info, '').
bip(goal, 3, ., game_description, '').
bip(handle_message, 3, ., message_handler, '').
bip(header, 3, ., http_grammar, '').
bip(http_client, 7, ., http_client, 'http_client-7').
bip(http_client, index, ., http_client, '').
bip(http_grammar, index, ., http_grammar, '').
bip(http_method, index, ., http_method, '').
bip(http_server, 1, ., http_server, 'http_server-1').
bip(http_server, 2, ., http_server, 'http_server-2').
bip(http_server, index, ., http_server, '').
bip(init, 1, ., game_description, '').
bip(initial_state, 1, ., game_description, '').
bip(legal, 3, ., game_description, '').
bip(list_to_token, 2, ., http_grammar, '').
bip(load_rules, 1, ., game_description, '').
bip(load_rules_from_file, 1, ., game_description, '').
bip(local_time_to_external, 2, ., time_sync, '').
bip(log_printf, 3, ., logger, 'log_printf-3').
bip(logger, index, ., logger, '').
bip(logln, 2, ., logger, 'logln-2').
bip(main, index, ., main, '').
bip(match_info, index, ., match_info, '').
bip(message_handler, index, ., message_handler, '').
bip(next, 3, ., game_description, '').
bip(number_of_roles, 1, ., game_description, '').
bip(parse_gdl_description_string, 2, ., gdl_parser, '').
bip(parse_gdl_message_string, 2, ., gdl_parser, '').
bip(parse_gdl_term_string, 2, ., gdl_parser, '').
bip(play_game, 4, ., debug_player, 'play_game-4').
bip(role, 1, ., game_description, '').
bip(role2index, 2, ., game_description, '').
bip(roles, 1, ., game_description, '').
bip(send_kill_message, index, ., send_kill_message, '').
bip(set_current_best_move, 1, ., match_info, '').
bip(set_current_state, 1, ., match_info, '').
bip(set_deadline, 1, ., time_sync, '').
bip(set_log_prefix, 1, ., logger, 'set_log_prefix-1').
bip(set_match_id, 1, ., match_info, '').
bip(set_our_role, 1, ., match_info, '').
bip(set_playclock, 1, ., match_info, '').
bip(set_startclock, 1, ., match_info, '').
bip(setup_game, 1, ., debug_player, 'setup_game-1').
bip(start_game_player, 0, ., main, 'start_game_player-0').
bip(start_game_player, 1, ., main, 'start_game_player-1').
bip(state_update, 3, ., game_description, '').
bip(status, 5, ., http_grammar, '').
bip(sync_time, 1, ., time_sync, '').
bip(terminal, 1, ., game_description, '').
bip(time_sync, index, ., time_sync, '').
bip(time_to_deadline, 1, ., time_sync, '').
bip(token_to_list, 2, ., http_grammar, '').
bip(true, 2, ., game_description, '').
