
% TESTS
htn_task(0,
	 goal([ transport(pk_1,city3_cl1,city1_cl1) ] ,[],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),moveable(truck_1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]).

htn_task(1,goal([ transport(pk_1,city3_cl1,city1_cl1) ] ,[],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ] 
            ).

htn_task(2,
	 goal([achieve(ss(traincar,traincar1,[at(traincar1,city1_ts1)]))],[],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ] 
            ).
htn_task(3,goal([ transport(pk_2,city3_cl1,city2_cl1), % hp1
             transport(pk_1,city3_cl1,city1_cl1)],  % hp2
             [before(1,2)],
             [ ]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]  
            ).

htn_task(4,goal([ transport(pk_1,city3_cl1,city1_cl1), 
            transport(pk_2,city3_cl1,CL) ],
            [],
            [in_city(CL,X),ne(X,city1)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]  
            ).

% transport to two different cities..
htn_task(5,goal([ transport(pk_1,city3_cl1,X), 
            transport(pk_2,city3_cl1,Y) ],
            [before(1,2)],
            [in_city(X,CT1),in_city(Y,CT2),ne(CT1,CT2)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]  
            ).

htn_task(6,goal([ transport(pk_1,city3_cl1,X), 
            transport(pk_2,city3_cl1,Y) ],
            [before(1,2)],
            [in_city(X,CT1),in_city(Y,CT2),ne(CT1,CT2),ne(CT1,city3),ne(CT2,city3)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]  
            ).


htn_task(7,goal([ achieve(ss(traincar,traincar1,[at(traincar1,city1_ts1)])),
	 transport(pk_6,city1_ts1,C) ],[],[ne(C,city2_ts1)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ] 
            ).

htn_task(8,goal([ 
             transport(pk_6,city1_ts1,city2_ts1) ],[],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ] 
            ).

htn_task(9,goal([ transport(pk_2,city3_cl1,city1_cl1), 
            transport(pk_4,city1_cl1,city2_cl1), 
            transport(pk_1,city3_cl1,city1_cl1)],[],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]  
            ).


htn_task(10,goal([ achieve(ss(traincar,traincar1,[at(traincar1,city1_ts1)])),
            transport(pk_1,city3_cl1,city2_cl1),
            achieve(ss(package,pk_5,[at(pk_5,X),delivered(pk_5)] )) ],
          [before(1,3)],
          [serves(X,city3)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]  
            ).

htn_task(11,goal([ achieve(ss(traincar,traincar1,[at(traincar1,city1_ts1)])),
            transport(pk_1,city3_cl1,city2_cl1),
            transport(pk_3,city3_cl1,city1_cl1),
            achieve(ss(package,pk_5,[at(pk_5,X),delivered(pk_5)] )) ],
          [before(1,3),before(2,3)],
          [serves(X,city3)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]  
            ).
htn_task(12,goal([ achieve(ss(traincar,traincar1,[at(traincar1,city1_ts1)])),
             transport(pk_6,city1_ts1,C),
           transport(pk_1,city3_cl1,city2_cl1) ],
       [],[ne(C,city2_ts1)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]
            ).

htn_task(13,goal([ transport(pk_1,city3_cl1,city1_cl1),
            transport(pk_2,city3_cl1,city2_cl1),
            transport(pk_3,city3_cl1,city1_cl1),
            transport(pk_4,city1_cl1,city3_cl1)],
            [before(1,3),before(2,3) ],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]
             ).
htn_task(14,goal([ transport(Y,city3_cl1,city2_cl1), % hp1
             transport(X,city3_cl1,city1_cl1)],  % hp2
             [before(1,2)],
             [ne(X,Y)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]
            ).
htn_task(15,goal([ transport(pk_1,city3_cl1,city1_cl1),
            transport(pk_3,city3_cl1,city1_cl1),
            transport(pk_4,city1_cl1,city3_cl1),
            transport(pk_2,city3_cl1,CL) ],
            [],
            [in_city(CL,X),ne(X,city1)]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]
            ).

htn_task(16,goal([ transport(pk_1,city3_cl1,city1_cl1),
            transport(pk_2,city3_cl1,city2_cl1),
            transport(pk_3,city3_cl1,city1_cl1),
            transport(pk_4,city1_cl1,city3_cl1)],
            [ ],[ ]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]     
             ).

htn_task(17,goal([ transport(pk_1,city3_cl1,city1_cl1),
            transport(pk_2,city3_cl1,city2_cl1),
            transport(pk_3,city3_cl1,city1_cl1),
            transport(pk_4,city1_cl1,city3_cl1),
            transport(pk_5,city3_cl1,city1_cl1) ],
            [ ],[ ]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]     
             ).

htn_task(18,goal([achieve(ss(package,pk_1,[waiting(pk_1),certified(pk_1)])),
             carry_direct(pk_1,city3_cl1,city1_cl2)],[],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]     
           ).

htn_task(19,goal([ transport(pk_1,city3_cl1,city1_cl1),
            transport(pk_2,city3_cl1,city2_cl1),
            transport(pk_3,city3_cl1,city1_cl1),
            achieve(ss(traincar,traincar1,[at(traincar1,city1_ts1)])),
            transport(pk_4,city1_cl1,city3_cl1),
            transport(pk_5,city3_cl1,city1_cl1) ],
            [before(1,2),before(3,2)],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]).
		
 htn_task(20,goal([ transport(pk_1,city3_cl1,city1_cl1),
             transport(pk_2,city3_cl1,city2_cl1),
             transport(pk_3,city3_cl1,city1_ts1),
             transport(pk_4,city1_cl1,city3_cl1),
             transport(pk_6,city1_ts1,city3_ts1),
             transport(pk_5,city3_cl1,city1_cl1) ],
             [before(1,2),before(3,2)],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)]) 

   ]).
		
htn_task(21,goal([ transport(pk_5,city3_cl1,city3_ts1)],
             [],[]),
	 [ 
                  ss(package,pk_1, [at(pk_1,city3_cl1),
                                    uncertified(pk_1)]),
                  ss(package,pk_2, [at(pk_2,city3_cl1),
                                    uncertified(pk_2)]),
                  ss(package,pk_3, [at(pk_3,city3_cl1),
                                    uncertified(pk_3)]),
                  ss(package,pk_4, [at(pk_4,city1_cl1),
                                    uncertified(pk_4)]),
                  ss(package,pk_5, [at(pk_5,city3_cl1),
                                    uncertified(pk_5)]),
                  ss(package,pk_6, [at(pk_6,city1_ts1),
                                    uncertified(pk_6)]),
                  ss(truck,truck_1, [at(truck_1,city1_cl1),
                                     available(truck_1)]),
                  ss(truck,truck_11, [at(truck_11,city1_cl1),
                                     moveable(truck_11),
                                     available(truck_11)]),
                  ss(truck,truck_2, [at(truck_2,city2_cl1),
                                     moveable(truck_2),
                                     available(truck_2)]),
                  ss(truck,truck_22, [at(truck_22,city2_cl1),
                                     moveable(truck_22),
                                     available(truck_22)]),
                  ss(truck,truck_3, [at(truck_3,city3_cl1),
                                     moveable(truck_3),
                                     available(truck_3)]),
                  ss(truck,truck_33, [at(truck_33,city3_cl1),
                                     moveable(truck_33),
                                     available(truck_33)]),
                  ss(traincar,traincar1, [at(traincar1,city2_ts1),
                                     unattached(traincar1),
                                     moveable(traincar1),available(traincar1)]),
                  ss(train,train2, [at(train2,city2_ts1),
                                     unattached(train2),
                                    moveable(train2),available(train2)]),
                  ss(train,train1, [at(train1,city1_ts1),
                                     unattached(train1),
                                    moveable(train1),available(train1)])]
            ).

% 
