(define (problem blocksworld_problem)
  (:domain blockworld_domain)
  (:objects a b c d e f)
  (:goal (on a f))
  (:init (clear table)
	 (on a b)
	 (on b c) 
	 (on c table)
	 (clear a)
	 (on d table)
	 (on f d)
	 (clear f)
	 (clear e)
	 (on e table))
)
