#!/bin/bash

# What the crazy large dev tree might look like 
export GITRC="--recursive"

if [ $# -eq 0 ] 
 then
    export MUDPACK=.
 else
    export MUDPACK="$1"
fi

# must have at least
git clone $GITRC https://github.com/TeamSPoon/hMUD $MUDPACK/hMUD
if [ ! -d /var/www/html/hmud/ ]; then
 sudo ln -s `pwd`/$MUDPACK/hMUD /var/www/html/hmud/
fi
sudo adduser --gecos "PrologMUD User" --disabled-login --disabled-password prologmud

# very usefull for seeing what is going on
git clone $GITRC https://github.com/TeamSPoon/ClioPatria $MUDPACK/ClioPatria
git clone $GITRC https://github.com/TeamSPoon/swish $MUDPACK/swish
git clone $GITRC https://github.com/TeamSPoon/trill_on_swish $MUDPACK/trill_on_swish
git clone $GITRC https://gitlab.prologmoo.com/prologmud_data/pldata_larkc.git $MUDPACK/pldata_larkc

exit 0

# git clone $GITRC https://prologmoo.com/TeamSPoon/swish $MUDPACK/swish

EXTERNAL PACKAGES
=========
Initial starter Docs https://github.com/TeamSPoon/PrologMUD/wiki

Installation see.. https://docs.google.com/document/d/1fkOxnmI1LqxadvZuCRS-fGIEweIKyPn6AVGp5Yjse1I/edit

![AdoptedFromKnowRob](http://www.prologmoo.com/downloads/screenshots/KnowRobOnto.png)

