/*
 * GIPO COPYRIGHT NOTICE, LICENSE AND DISCLAIMER.
 *
 * Copyright 2001 - 2003 by R.M.Simpson W.Zhao T.L.McCLuskey D Liu D. Kitchin
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose and without fee is hereby granted,
 * provided that the above copyright notice appear in all copies and that
 * both the copyright notice and this permission notice and warranty
 * disclaimer appear in supporting documentation, and that the names of
 * the authors or their employers not be used in advertising or publicity 
 * pertaining to distribution of the software without specific, written 
 * prior permission.
 *
 * The authors and their employers disclaim all warranties with regard to 
 * this software, including all implied warranties of merchantability and 
 * fitness.  In no event shall the authors or their employers be liable 
 * for any special, indirect or consequential damages or any damages 
 * whatsoever resulting from loss of use, data or profits, whether in an 
 * action of contract, negligence or other tortious action, arising out of 
 * or in connection with the use or performance of this software.
 */


//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Wed Jan 24 14:05:52 GMT+00:00 2001
//----------------------------------------------------

package jplan.pddl;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQ = 5;
  public static final int REQS = 4;
  public static final int FORDOMAIN = 21;
  public static final int DEL = 17;
  public static final int PROBLEM = 19;
  public static final int Q = 27;
  public static final int CONSTANTS = 7;
  public static final int PREDS = 8;
  public static final int CONDEFF = 36;
  public static final int NAME = 28;
  public static final int DEFINE = 9;
  public static final int MINUS = 31;
  public static final int WHEN = 35;
  public static final int DOMAIN = 10;
  public static final int RBRA = 2;
  public static final int TYPES = 30;
  public static final int TYPING = 29;
  public static final int EOF = 0;
  public static final int EFFECTS = 15;
  public static final int PARALLEL = 26;
  public static final int LENGTH = 24;
  public static final int RKET = 3;
  public static final int error = 1;
  public static final int INITIALLY = 22;
  public static final int GOALS = 23;
  public static final int STRIPS = 6;
  public static final int SITUATION = 18;
  public static final int ARGS = 13;
  public static final int STATICS = 11;
  public static final int INTEGER = 33;
  public static final int ACTION = 12;
  public static final int AND = 16;
  public static final int SERIAL = 25;
  public static final int VARS = 20;
  public static final int PRE = 14;
  public static final int EITHER = 32;
  public static final int OBJECTS = 34;
}

