
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu May 26 21:18:52 BST 2005
//----------------------------------------------------

package jplan.ocl;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PREDICATES = 14;
  public static final int INCREASE = 42;
  public static final int DATEL = 31;
  public static final int SS = 22;
  public static final int MULT = 46;
  public static final int TASK = 26;
  public static final int EVENT = 58;
  public static final int EQUALS = 51;
  public static final int DATEC = 30;
  public static final int HTNGOAL = 35;
  public static final int INCONCONST = 18;
  public static final int DOUBLE = 60;
  public static final int TIME = 56;
  public static final int GREATER = 52;
  public static final int SE = 20;
  public static final int SC = 21;
  public static final int IMPINVAR = 11;
  public static final int ACHIEVE = 24;
  public static final int ATOMINVAR = 17;
  public static final int LESS = 53;
  public static final int MINUS = 45;
  public static final int HTNTASK = 34;
  public static final int BEFORE = 25;
  public static final int OBJECTS = 13;
  public static final int NOT = 50;
  public static final int AND = 48;
  public static final int DESCDET = 32;
  public static final int OPTION = 36;
  public static final int FUNCTORS = 15;
  public static final int OR = 49;
  public static final int COMMA = 3;
  public static final int DIV = 47;
  public static final int DESCEND = 33;
  public static final int PLUS = 44;
  public static final int LESSEQ = 55;
  public static final int ASSIGN = 39;
  public static final int PROCESS = 57;
  public static final int EOF = 0;
  public static final int DOMNAME = 10;
  public static final int METHOD = 23;
  public static final int TEST = 38;
  public static final int SSCLASSES = 16;
  public static final int error = 1;
  public static final int RKET = 5;
  public static final int RBRA = 4;
  public static final int NUMBER = 59;
  public static final int DECREASE = 43;
  public static final int SCALEUP = 40;
  public static final int NAME = 8;
  public static final int SCALEDOWN = 41;
  public static final int INSTITUTION = 29;
  public static final int STOP = 2;
  public static final int STATETRANS = 27;
  public static final int AUTHOR = 28;
  public static final int GREATEREQ = 54;
  public static final int OPERATOR = 19;
  public static final int VALUE = 37;
  public static final int SORTS = 12;
  public static final int VAR = 9;
  public static final int SKET = 7;
  public static final int SBRA = 6;
}

